.gitignore, CODEOWNERS, src/main.tf
=> [PAG-287] init repo infra TF oncloud

src/README.md, src/api/base_policy.tpl, src/api/base_policy.xml, src/api/monitor/mock_policy.xml, src/api/monitor/openapi.json.tpl, src/apim.tf, src/data.tf, src/database.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/monitor.tf, src/network.tf, src/outputs.tf, src/redis_cache.tf, src/security.tf, src/variables.tf
The purpose of this PR is to add APIM according to [Nuova architettura pagoPA](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/384141796/Nuova+architettura+pagoPA)
---
=> [PAG-710] add apim

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml, src/.terraform.lock.hcl, src/azure_devops_agent.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
1. add azure devops agent
2. add code review, deploy pipelines (deploy must be improved to start deploy on merge)
devops pipeline use private self hosted agent to improve parallel jobs
Azure DevOps pagopa-iac project defined in https://github.com/pagopa/gitops/pull/134
devops bottleneck :)
---
=> Add iac pipeline

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml
add pipeline timeout to prevent lock
prevent locks when some vars are missing like in https://github.com/pagopa/pagopa-infra/pull/22#issuecomment-929072630
---
=> add pipeline timeout

src/apim.tf, src/redis_cache.tf, src/variables.tf
Temporary disabling of the redis cache for apim
---
=> temp disable redis cache apim

src/mock_psp.tf
- add `AZURE_API_STATIC_RES` in mock-psp configuration;
- update `SERVER_PUBLIC_URL` in mock-psp configuration;
---
=> [PM-163] update env for mock-psp

src/mock_psp.tf
- delete `AZURE_API_STATIC_RES` env for mock-psp
- update healthcheck endpoint for mock-psp
---
=> [PM-163] update healthcheck for mockpsp

src/README.md, src/aks.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/outputs.tf, src/variables.tf
The purpose of this PR is to add a AZ Container registry.
---
=> [PAG-973] create acr

src/env/uat/terraform.tfvars
=> downgrade checkout function UAT plan

src/README.md, src/checkout_function.tf, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
use app service plan for azure functions
need this PR https://github.com/pagopa/azurerm/pull/111
APPLY IN PROD WILL DESTROY THE FUNCTION
cost savings
---
=> Change function to use app service plan

src/api/apiconfig_api/v1/_base_policy.xml, src/api/apiconfig_api/v1/_openapi.json.tpl, src/api_config.tf, src/apim.tf, src/apim_api_config.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
- added configuration to `apiconfig` for SIA DB
- added read-only policy to API
To set the configuration for dev, uat, prod
---
=> [PCFG-82] SIA Database configuration

src/api/apiconfig_api/v1/_base_policy.xml, src/api/apiconfig_api/v1/_base_policy.xml.tpl, src/api_config.tf, src/apim_api_config.tf
- added CORS configuration in the app_setting of `api-config`
- updated README.md with `precommit`
To configure CORS: only accept the  requests from the frontend.
---
=> `api-config` CORS Configuration

CODEOWNERS, src/api/nodopagamenti_api/v1/activate_nm3.xml, src/env/dev/terraform.tfvars
The purpose of this PR is to manage option field `expirationTime` in activate payment request
---
=> [PAG-1038] add `expirationTime` field in nodo apim policy

src/appgateway.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
Created app_gateway_sku_tier variable and modified `app_gw` module
- created app_gateway_sku_tier variable for dev/uat/prod
---
=> Sku_tier variable in dev/uat/prod env

src/README.md, src/api/nodopagamenti_api/v1/activate_nm3.xml, src/appgateway.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
=> fix disable waf and lint

README.md, src/README.md, src/checkout_fe.tf, src/checkout_function.tf
- add `azurerm_application_insights_web_test`to monitor frontend;
- add `azurerm_monitor_scheduled_query_rules_alert` to monitor checkout availability;
- add `azurerm_monitor_metric_alert` to monitor 5xx of checkout function app;
The goal of this PR is to create some alarms for the checkout API.
---
=> [IOPAY-346] alerts for monitoring

src/appgateway.tf, src/checkout_function.tf
- update node version for checkout api
- increase timeout for apim in app gtw
- update availability alert
---
=> [IOPAY] Update node version for checkout and increase apim timeout

src/api_config_fe.tf
Added dynamic rule regarding `url_file_extension_condition` in order to manage routing through React and avoid to find resource in the Azure Storage
---
=> [PCFG-94] Routing

src/appgateway.tf, src/checkout_fe.tf, src/checkout_function.tf
=> Disable app gtw alert on response time

src/api_config.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
Added a variable regarding XSD schema in order to validate XML.
---
=> [PCFG-85] XML Schema for ICA variable

src/api/checkout/checkout_payments/v1/_swagger.json.tpl, src/api/checkout/checkout_transactions/v1/_swagger.json.tpl
- Update swagger for checkout API
- Update status codes for redirect
- Update refs in swagger
---
=> [IOPAY-345][IOPAY-390] Update swagger with new status codes

src/README.md, src/api_config_fe.tf, src/checkout_fe.tf, src/monitor.tf, src/terraform.sh
=> Web availability tests with SSL expiry check

src/.terraform.lock.hcl, src/aks.tf, src/api_config.tf
The purpose of this PR is to add custom container retrieves form pagoPA ACR for api-config backend.
---
=> [PCFG.103] add custom container to api-config app service

src/env/dev/terraform.tfvars
Add `nodo-dei-pagamenti-sia-rx` consumer group for in dev subscription for SIA test
---
=> [PAG-1098] add sas sia for test RE su ehub

src/README.md, src/api/apiconfig_api/v1/_openapi.json.tpl, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
- changed DNS name
- updated swagger apiconfig
---
=> DB Sit Nodo Pagamenti

src/apim_checkout.tf
1. Add wsdl_selector for cdInfoWisp api conf
2. add project prefix for new checkout api
---
=> [IOPAY-405] fix cdInfoWisp Apim configuration & add project prefix checkout api

src/api/apiconfig_api/v1/_openapi.json.tpl
- updated swagger apiconfig
---
=> `apiconfig` new swagger definition

src/apim_api_config.tf, src/apim_nodo_services.tf
The purpose of this PR is to add ignore tfsec check for some not real critical issues.
Updated 
- ignore tfsec for `token_endpoint` of  `azurerm_api_management_authorization_server`
- ignore tfsec for  `xml_content` of  api_operation_policy `nm3_activate_verify_policy`
---
=> [INFRA-485] Add ingnore tfsec check

src/security.tf
=> [INFRA-499] Send key vault log to security

src/monitor.tf
=> [INFRA-500] Send activity log to security

src/apim.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/monitor.tf, src/variables.tf
standard alerts for apim
monitoring/alerting
---
=> [INFRA-501] Apim standard alerts

src/env/prod/terraform.tfvars, src/pagopa_proxy.tf
- add scheduled updates (night)
- sku for prod
Prod configs
---
=> pagopa proxy redis prod configs

src/apim_checkout.tf
=> fix api_name in checkout policy

src/api/nodopagamenti_api/nodoPerPa/v1/NodoPerPa.wsdl, src/api/nodopagamenti_api/nodoPerPa/v1/_base_policy.xml, src/api/nodopagamenti_api/nodoPerPsp/v1/nodoPerPsp.wsdl, src/apim_nodo_services.tf
The purpose of this PR is to add a new WS `nodoInviaFlussoRendicontazione` needed for [Monitoraggio Flussi Di Rendicontazione](https://pagopa.atlassian.net/wiki/spaces/MF/pages/442990630/Design+Review+Monitoraggio+FdR) for nodo-dei-pagament and `nodoChiediFlussoRendicontazione` , `nodoChiediElencoFlussiRendicontazione` needed to [Gestion PD Rendicontazione](https://pagopa.atlassian.net/wiki/spaces/PPD/pages/456525211/Design+Review+-+Rendicontazione)
Updated 
- `nodoPerPsp.wsdl` wsdl operation `nodoInviaFlussoRendicontazione`
- update `nm3_activate_verify_policy` for `prod` env
- udpate nodo apim path accordin to [Configurazione API Nodo su APIM pagoPA](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/459636892/Configurazione+API+Nodo+su+APIM+pagoPA#Nodo-Full-path-definitions-%F0%9F%8E%A2 …
=> [PMF-8] add nodo Fdr WS + rename services path name convention

src/api_logs.tf, src/apim.tf, src/apim_checkout.tf
- add full log for apim api
this PR depends on https://github.com/pagopa/azurerm/pull/170
---
=> [INFRA-502] Full log nodo api

src/README.md, src/env/dev/terraform.tfvars, src/env/uat/terraform.tfvars, src/nodo_dei_pagamenti_test.tf, src/outputs.tf, src/variables.tf
Added CDN endpoint and storage account resources.
- added resource configuration for cdn and storage account
---
=> [PPR-291] Infra for pagopa-nodo-dei-pagamenti-test

src/nodo_dei_pagamenti_test.tf
=> [PPR-291] Fix automation

src/api/checkout/checkout_payment_activations/v1/_base_policy.xml.tpl
=> fix checkout policy

src/api/payment_manager_api/admin-panel/_swagger.json.tpl, src/api/payment_manager_api/logging/v1/_swagger.json.tpl, src/api/payment_manager_api/restapi-cd/v1/_swagger.json.tpl, src/api/payment_manager_api/restapi-cd/v2/_swagger.json.tpl, src/api/payment_manager_api/restapi-cd/v3/_swagger.json.tpl, src/api/payment_manager_api/restapi-rtd/v1/_openapi.json.tpl, src/api/payment_manager_api/restapi-rtd/v2/_openapi.json.tpl, src/api/payment_manager_api/restapi/v4/_swagger.json.tpl, src/api/payment_manager_api/webview-cd/_swagger.json.tpl, src/api/payment_manager_api/wisp/_swagger.json.tpl
=> fix swagger title

src/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml, src/apim.tf, src/apim_nodo_services.tf, src/data.tf, src/env/dev/terraform.tfvars, src/fdr.tf, src/variables.tf
The purpose of this PR is to add a blob storage to save the streams [Flussi di rendicontazione](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/305136147/Flussi+di+rendicontazione)
Added : 
- storage account for Fdr
- role base access policy to blob contributor for apim to Fdr storage
- add Fdp apim policy for [nodoInviaFlussoRendicontazione](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/211585234/nodoInviaFlussoRendicontazione)
Implements [Monitoraggio Flussi Di Rendicontazione](https://pagopa.atlassian.net/wiki/spaces/MF/pages/442990630/Design+Review+Monitoraggio+FdR)
```
curl --location --request POST 'https://api.uat.platform.pagopa.it/nodo/nodo-per-psp/v1' \
--header 'SOAPAction: nodoInviaFlussoRendicontazione' \
--header 'Content-Type: application/xml' \
--header 'Cookie: …
```
=> [PMF-7] add fdr blob storage

src/appgateway.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
add deny paths on app gateway
protect apis
---
=> add deny paths on app gateway

src/env/prod/terraform.tfvars
- add internal PM services in `app_gateway_deny_paths`, only for PROD env.
---
=> [IOPAY-400] Disable PM internal service

src/pagopa_proxy.tf
- add staging slot for `pagopa-proxy`
The goal of this PR is to add staging slot for `pagopa-proxy` app service in order to improve the releases.
---
=> [IOPAY-404] add slot staging for pagopa-proxy

src/apim_nodo_services.tf
The purpose of this PR is to create n apim product related to nodo-dei-pagamenti's services exposed on apim
Added : 
- `apim_nodo_dei_pagamenti_product`
- list `api_nodo_product` of api related to above apim product 
---
=> [INFRA-490] add apim_nodo_dei_pagamenti_product

src/network.tf
- add routes to pm
pm cloud migration
---
=> Add routes to Payment Manager

src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
The purpose of this PR is to add a new topic `nodo-dei-pagamenti-fdr` to publish a “datiSingoloPagamento” json event according to [Monitoraggio FdR](https://pagopa.atlassian.net/wiki/spaces/MF/pages/442990630/Design+Review+Monitoraggio+FdR#Struttura-dati-da-scrivere-su-eventHub)
Added : 
- `nodo-dei-pagamenti-fdr` topic ehub
---
=> [PMF-15] Add nodo-dei-pagamenti-fdr ehub topic

src/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/reporting_function.tf, src/variables.tf
The purpose of this PR is to add a FdR function service to read [nodoInviaFlussoRendicontazione](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/211585234/nodoInviaFlussoRendicontazione), parsing it and publish on pagoPA's event hub as several `json` events
Added : 
- _Flussi Di Rendicontazione_ `reporting_function.tf`
Updated : 
- update Fdr apim policy
---
=> [PMF-13] Add FdR function

src/api/mockec_api/v1/_swagger.json.tpl
=> Fix Swagger Mock EC

src/api/mockec_api/v1/_swagger.json.tpl
=> fix swagger basepath

src/pagopa_proxy.tf, src/variables.tf
- add autoscale for pagopa-proxy
---
=> [IOPAY-417] add autoscale for pagopa-proxy

src/api/checkout/checkout_payment_activations/v1/_recaptcha_check.xml.tpl
=> Fix recaptcha policy - checkout

src/messages.tf, src/reporting_function.tf
The purpose of this PR is to add ehub connection string to Fdr function in order to publish message on it
Update : 
- add `EHUB_FDR_CONNECTION_STRING` to Fdr function vars
---
=> [PMF-15] add fdr ehub topic var to fdr function

src/README.md, src/api/apiconfig_api/v1/_base_policy.xml.tpl, src/api_config.tf, src/variables.tf
=> [PCFG-144] Api Config Update policy 

src/api/nodopagamenti_api/nodoPerPM/_base_policy.xml.tpl, src/api/payment_manager_api/clients/bpd/v1/_base_policy.xml.tpl, src/api/payment_manager_api/clients/cobadge/v4/_base_policy.xml.tpl, src/api/payment_manager_api/clients/fesp/_base_policy.xml.tpl, src/api/payment_manager_api/clients/io-bpd/_base_policy.xml.tpl, src/api/payment_manager_api/clients/paypal-psp/v1/_base_policy.xml.tpl, src/api/payment_manager_api/clients/xpay/v1/_base_policy.xml.tpl, src/api/payment_manager_api/logging/v1/_base_policy.xml.tpl, src/api/payment_manager_api/restapi-rtd/v1/_base_policy.xml.tpl, src/api/payment_manager_api/restapi-rtd/v2/_base_policy.xml.tpl, src/apim_payment_manager.tf
-  fix `restapi-rtd` basepath;
- Disable ip filter for Payment Manager API
---
=>  fix restapi-rtd basepath & disable ip filter for pm

README.md, src/README.md, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/gpd_reporting.tf, src/variables.tf
The purpose of this PR is to create resources for [Gestione Posizioni Debitorie Rendicontazione'](https://pagopa.atlassian.net/wiki/spaces/PPD/pages/456525211/Design+Review+-+Rendicontazione) service
depends on #162
Add : 
- 3 fn app : 
- `reporting_batch_function`
- `reporting_service_function`
- `reporting_analysis_function`
- with same service plan #162 
- storage account with : 
- table storage
- queue storage flows
- queue storage organizations
- queue storage flows
- blob container flows
---
=> [PPD-58] rendicontazione GPD

src/README.md, src/env/dev/terraform.tfvars, src/gpd.tf, src/gpd_reporting.tf, src/variables.tf
=> fix function reporting

src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
The purpose of this PR is to align subnet in all environments 
Update : 
- all cidr address 
---
=> [INFRA-511] align subnets for envs

src/api/checkout/checkout_payment_activations_auth/v1/_base_policy.xml.tpl, src/api/checkout/checkout_payment_activations_auth/v2/_base_policy.xml.tpl, src/apim.tf, src/apim_checkout.tf
- Delete rate limit for api for io-backend
- Ad ip-filter for checkout auth
- add `detail_v2` in checkout auth policy
---
=> [IOPAY-485] Delete rate limit for api for io-backend

src/api/nodopagamenti_api/nodoPerPa/v1/NodoPerPa.wsdl
The purpose of this PR is to fix `nodoPerPA` wsdl action import on apim
- [] Yes, users may be impacted applying this change
---
=> fix nodoPerPA apim import

src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
The purpose of this PR is to update ehub config : 
- align UAT to PROD
- change partition for topic `nodo-dei-pagamenti-re` from `32` to `30` to achieve best performance for PDND 
Update : 
- event hub config
---
=> [PAG-1297] fix ehub config

src/api/checkout/checkout_payment_activations_auth/v1/_base_policy.xml.tpl, src/api/checkout/checkout_payment_activations_auth/v2/_base_policy.xml.tpl, src/apim.tf
=> Fix pagopa-proxy (checkout) policy and add client-io group

src/api_logs.tf, src/apim_checkout.tf
=> Add apim logs for pagopaproxy

src/api/gpd_api/payments/v1/_base_policy.xml.tpl, src/api/gpd_api/payments/v1/paForNode.wsdl, src/api_product/gpd/payments/_base_policy.xml, src/apim_payments.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/gpd.tf, src/gpd_payments.tf, src/variables.tf
GPD Payments:
- app service
- apim
- wsdl
- base policy
---
=> [PPD-78] GPD Payments

src/checkout_function.tf
=> fix checkout alert availability

src/apim_donazione_ucraina.tf
The purpose of this PR is to fix api_operation_policy ref for "donazioni"
---
=> fix azurerm_api_management_api_operation_policy donazioni

.github/workflows/main.yml
created a guthub action to auto assign a PR
---
=> Auto Assignee

src/api/checkout/checkout_payment_activations/v1/_base_policy_dev.xml.tpl, src/apim.tf, src/apim_checkout.tf
- mock dev for checkout (pagopa-proxy)
The goal of this PR is to have a mock for `pagopa-proxy` in order to activate a payment in  `nodo SIT`, also valid for the  `PM SIT`
---
=> Add mock dev for checkout (pagopa-proxy)

src/canoneunico.tf, src/variables.tf
The purpose of this pr is to fix typo name of CU fn name
Upd : 
- name of `canoneunico_function` 
---
=> fix cu fn name

src/checkout_function.tf, src/env/prod/terraform.tfvars
- delete old `pagopa_proxy_enabled`;
- update callback url for xpay flow in pagoPA - checkout
---
=> Iopay 532 update xpay endpoint

src/apim.tf, src/buyerbanks_function.tf, src/env/prod/terraform.tfvars, src/variables.tf
=> App-apim-autoscale

src/api/gpd_api/reporting_analysis/v1/_base_policy.xml, src/api/gpd_api/reporting_analysis/v1/_openapi.json.tpl, src/api_logs.tf, src/api_product/gpd/reporting_analysis/_base_policy.xml, src/apim_gpd_reporting.tf, src/apim_payments.tf, src/env/dev/terraform.tfvars, src/gpd.tf, src/gpd_payments.tf, src/variables.tf
=> [PPD-115] fix gdp deploy

src/api/gpd_api/reporting_analysis/v1/_openapi.json.tpl, src/api/gpd_api/v1/_openapi.json.tpl, src/api_config.tf, src/api_logs.tf, src/apim_gpd_reporting.tf, src/gpd.tf, src/gpd_payments.tf
- reporting-analysis: fix swagger and url
- api logs
---
=> [PPD-115] GPD and CU Infra improvements

src/canoneunico.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/gpd.tf, src/gpd_payments.tf
- set env vars
- set alert 
---
=> GPD / Canone Unico - UAT

src/gpd.tf, src/gpd_payments.tf, src/monitor.tf
The purpose of this PR is to add autoscaling x requests for GPD and PAYMENTs app service
---
=> [GPD] Autoscaling

.pre-commit-config.yaml, src/apim_checkout.tf, src/azure_devops_agent.tf
removed kv policy for azure devops
---
=> removed kv policy for azure devops

src/env/uat/terraform.tfvars, src/mock_ec.tf
Update mock-ec configuration
---
=> update mock ec config

src/fdr.tf, src/reporting_function.tf
The purpose of this PR is to add new blob container for [Monitoraggio FdR](https://pagopa.atlassian.net/wiki/spaces/MF/pages/442990630/Design+Review+Monitoraggio+FdR)
---
=> add fdr out blob

src/psql/migrations/DEV-pagoPA/mock_psp/V7__PM_744_ADD_OUTCOME_CONFIGS.sql
- update mock-psp db scripts
---
=> [PM-774] update mock-psp scripts

src/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml, src/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
The purpose of this PR is to resolve [concurrents activate request](https://pagopa.atlassian.net/browse/PAG-1295) as shown below : 
extending the current behavior of [VERIFICATORE](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/433914753/Verificatore+APIM+policy)
The error response in case **activate reservation**  of is following
```xml
<fault>
<faultCode>PPT_ATTIVAZIONE_IN_CORSO</faultCode>
<faultString>E' in corso un'altra attivazione per lo stesso avviso</faultString>
<id>NodoDeiPagamentiSPC</id>
<description>E' in corso un'altra attivazione per lo stesso avviso</description>
</fault>
```
Upd : 
- apim policy `activate_nm3.xml`
---
=> [PAG-1561] activate reservation

src/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml, src/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
The purpose of this PR is to  : 
- set delete cache activate reservation on pre-request verify KO response
- change retention timeout activate reservation from `60` sec to `30` sec
- add `text/xml` to fdr policy
---
=> fix delete cache activate reservation + fix content type fdr

src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
The purpose of this PR is to add new topic `nodo-dei-pagamenti-biz-evt ` according to [Design Review- Evento di pagamento](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/497746877/Design+Review-+Evento+di+pagamento)
---
=> [PAG-1526] add nodo-dei-pagamenti-biz-evt topic on ehub

src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
Add following consumer to `nodo-dei-pagamenti-biz-evt` topic
SAS | used by
-- | --
pagopa-biz-evt-rx-pdnd | PDND team
pagopa-biz-evt-rx | pagoPA team
pagopa-biz-evt-rx-io | io-core team
---
=> [PAG-1526] add consumer to nodo-dei-pagamenti-biz-evt

src/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
The purpose of this PR is to remove useless [namespace (un)declaration](https://stackoverflow.com/questions/13220095/remove-unwanted-empty-xmlns-attribute-added-by-appendchild) 
---
=> replace undeclaration xml namespace

src/api/apiconfig_api/v1/_openapi.json.tpl
=> ApiConfig-swagger-update

src/api/apiconfig_api/checkout/v1/_base_policy.xml.tpl, src/api/apiconfig_api/checkout/v1/_openapi.json.tpl, src/api/apiconfig_api/v1/_base_policy.xml.tpl, src/api_product/apiconfig_api/_base_policy_checkout.xml, src/apim_api_config.tf
This pr creare a custom product of API Config for Checkout.
The exposed API are a subset of the entire project. 
- adopt subscription-key to expose api of API Config for Checkout
- improved rate-limit in the API Config policy
---
=> [PCFG-203] APIM API Config for Checkout

src/gpd_payments.tf
- added alert for Payments-GPD inconsistency error
- highlight a dirty condition that needs remediation
---
=> [PPD-180] Payments az alert

src/README.md, src/api_config.tf, src/apim_api_config.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
- Added auto-scaling to ApiConfig
- removed variable api_config_enabled -> apiconfig enabled in all environments
To deploy in production
---
=> [PCFG-225] Enabled ApiConfig for Production

src/api_config.tf
depends on https://github.com/pagopa/pagopa-infra/pull/277
It needed to add autoscale configuration after that plan id is created
---
=> [ApiConfig] added AutoScaling

src/api_config.tf
Add vnet integration to _api-config_ appservice 
---
=> upd apiconfig vnet integration

src/api/checkout/checkout_payment_activations_auth/v1/_base_policy.xml.tpl, src/api/checkout/checkout_payment_activations_auth/v2/_base_policy.xml.tpl, src/apim_checkout.tf
- disable ip filter for checkout auth;
The goal of this PR is to use only subscription key for the Checkout Auth API.
---
=> feat: disable ip filter for checkout auth

src/api/checkout/checkout_payment_activations_auth/v2/_swagger.json.tpl
=> Update Checkout API v2 documentation with new `category` error field

src/api/checkout/checkout_payment_activations_auth/v2/_swagger.json.tpl
=> [CHK-464] update error code for auth v2

src/env/prod/terraform.tfvars
Add DNS A-record to DNS PROD DB nodo-dei-pagamenti
---
=> upd dns_a_reconds_dbnodo_ips

src/api/nodopagamenti_api/paForNode/v1/donazioni_ucraina_activate.xml, src/api/nodopagamenti_api/paForNode/v1/donazioni_ucraina_verify.xml
=> fix payments info

src/container_registry.tf
According to [PagoPA devops guidelines](https://pagopa.atlassian.net/wiki/spaces/DEVOPS/pages/489619457/Container+Registry) ACR shall be public
---
=> set acr public

src/container_registry.tf
=> fix acr perm

src/gpd_payments.tf
Add `API_CONFIG_HOST` configuration parameters for **Payments** 
---
=> feat: Upd payments configuration

src/fdr.tf, src/variables.tf
=> feat: Add azurerm_storage_management_policy fdr

src/api/nodopagamenti_api/nodeForPsp/v1/nodeForPsp.wsdl
The purpose of this PR is to configure under pagoPA apim new nodo-dei-pagamenti's webservices 
1. `demandPaymentNotice`
1. `nodoChiediCatalogoServiziV2`
⚠️ The second one it's new version of "older" `nodoChiediCatalogoServizi` available at 
```
POST https://api.<ENV>.platform.pagopa.it/nodo/nodo-per-psp-richiesta-avvisi/v1 HTTP/1.1
SOAPAction: "nodoChiediCatalogoServizi"
```
Add to **Node for PSP WS (NM3)** products apis : 
- `demandPaymentNotice`
```
POST https://api.<ENV>.platform.pagopa.it/nodo/node-for-psp/v1 HTTP/1.1
SOAPAction: "demandPaymentNotice" 
```
- `nodoChiediCatalogoServiziV2`
```
POST https://api.<ENV>.platform.pagopa.it/nodo/node-for-psp/v1 HTTP/1.1
SOAPAction: "nodoChiediCatalogoServiziV2"
```
---
=> feat: Add demandPaymentNotice nodoChiediCatalogoServiziV2 nodeForPsp

src/monitor.tf
Add availabilty test for status.pagopa.gov.it
Need to check if status page is available
---
=> add avaliabilty test status page

src/api_config.tf, src/env/uat/terraform.tfvars, src/variables.tf
Reduce min scale instances to reduce costs
---
=> Fix app service autoscale instances

src/api/payment_manager_api/mock-services-api/v1/_base_policy.xml.tpl, src/api/payment_manager_api/mock-services-api/v1/_openapi.json.tpl, src/api/payment_manager_api/mock-services-fe/v1/_base_policy.xml.tpl, src/api/payment_manager_api/mock-services-fe/v1/_openapi.json.tpl, src/apim_payment_manager.tf
- add pm mock-services in APIM pagopa; 
---
=> feat: add pm mock services

src/apim_payment_manager.tf
=> fix mock  services v1

src/advanced_fees_management.tf
- added archived container to cosmosdb configuration
- change of requirements
---
=> [PPR-351] AFM Marketplace - Add archived container

src/aks/env/weu-prod/backend.ini, src/aks/env/weu-prod/backend.tfvars, src/aks/env/weu-prod/terraform.tfvars, src/aks/env/weu-uat/backend.ini, src/aks/env/weu-uat/backend.tfvars, src/aks/env/weu-uat/terraform.tfvars
=> init uat aks

src/apim_api_config.tf
The purpose of this PR is to "link" openapi spec [auto-generate from spring](https://www.baeldung.com/spring-rest-openapi-documentation) for api-config service , in DEV and UAT stages
> PROD : static
---
=> feat: Add openapi-link for apim_api_config_api

src/api/tkm_api/tkm-ms-test-utility/v1/_base_policy.xml.tpl, src/api/tkm_api/tkm-ms-test-utility/v1/_openapi.json.tpl, src/apim_tkm.tf, src/ecommerce/README.md
- add test utility api for TKM;
The goal of this PR is to add (only for dev environment) api exposed by https://github.com/pagopa/tkm-ms-test-utility with the following base path:
- `tkm/tkm-ms-test-utility/v1/`
To invoke the APIs a subscription key is required.
---
=> feat: add test utility api for TKM

src/gps-common/02_security.tf, src/gps-common/README.md, src/gps/02_namespace.tf
=> minor fix aks gps for deploy

src/api/tkm_api/tkm-ms-consent-manager-internal/v1/_base_policy.xml.tpl, src/api/tkm_api/tkm-ms-consent-manager-internal/v1/_openapi.json.tpl, src/apim_tkm.tf, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
- add new internal API for [consent-manger](https://github.com/pagopa/tkm-ms-consent-manager/tree/develop);
The goal of this PR is to add new internal api of [consent-manger](https://github.com/pagopa/tkm-ms-consent-manager/tree/develop), exposed for [card-manager](https://github.com/pagopa/tkm-ms-card-manager) with subscription-key.
---
=> PM-944 internal API for consent-manger

src/api/payment_manager_api/test-utility/v1/_base_policy.xml.tpl, src/api/payment_manager_api/test-utility/v1/_openapi.json.tpl, src/apim.tf, src/apim_payment_manager.tf
- add test utility api for Payment Manager, in order to get valid `sessionToken` and `idPayment`.
---
=> feat: test utilty for Payment Manager

src/gps/api/gps-donation-service/v1/_base_policy.xml, src/gps/api/gps-donation-service/v1/_openapi.json.tpl
=> fix gps donations

src/gps/api/gps-donation-service/v1/_openapi.json.tpl
=> [GPS Donation] Swagger Update

src/gps/04_apim_gps.tf, src/gps/04_apim_gps_donation.tf
=> add subkey + devportal for GPS and DONATIONS

src/gps/04_apim_gps_enrollments.tf, src/gps/api/spontaneous-payments-enrollments/v1/_base_policy.xml, src/gps/api/spontaneous-payments-enrollments/v1/_openapi.json.tpl
The purpose of this pr is to add `spontaneous-payments-enrollments`
Add : 
- apim `spontaneous-payments-enrollments` product
- policy to re-write and add `organizationCode` in to url service path
---
=> [PPD-259] spontaneous-payments-enrollments PRODUCT

src/gps/04_apim_gps.tf, src/gps/04_apim_gps_donation.tf, src/gps/04_apim_payments_receipts.tf, src/gps/api/payments-receipts/v1/_base_policy.xml, src/gps/api/payments-receipts/v1/_openapi.json.tpl, src/shared/04_apim_iuvgenerator.tf
=> [PPD-259] add payments-receipts apim product

src/gps/04_apim_debt_positions.tf, src/gps/api/debt-position-services/v1/_base_policy.xml, src/gps/api/debt-position-services/v1/_openapi.json.tpl
=> [PPD-259] add debt-position product

src/gps-common/env/weu-uat/backend.ini, src/gps-common/env/weu-uat/backend.tfvars, src/gps-common/env/weu-uat/terraform.tfvars, src/gps/env/weu-uat/backend.ini, src/gps/env/weu-uat/backend.tfvars, src/gps/env/weu-uat/terraform.tfvars
=> feat: Add uat env gps aks namespace

src/gps/99_locals.tf
=> fix gps hostname internal ref

src/shared-common/env/weu-uat/backend.ini, src/shared-common/env/weu-uat/backend.tfvars, src/shared-common/env/weu-uat/terraform.tfvars, src/shared/env/weu-uat/backend.ini, src/shared/env/weu-uat/backend.tfvars, src/shared/env/weu-uat/terraform.tfvars
=> add shared aks uat namespace

src/README.md, src/data.tf
=> Storage account to backup apim

.devops/backup-apim-deploy-pipelines.yml
=> Apim backup pipeline

src/api/gpd_api/payments/v1/soap/paForNode.wsdl
update Payments wsdl:
- added paDemandPaymentNoticeRequest
to apply it partially 
```
sh terraform.sh apply dev -target=azurerm_api_management_api.apim_api_gpd_payments_api
```
---
=> New Payments WSDL

src/aks/02_aks.tf, src/aks/03_ingress.tf, src/aks/env/weu-prod/terraform.tfvars
The purpose of this PR is to create AKS in PROD env
---
=> feat: Fix aks prod

src/gps-common/env/weu-prod/backend.ini, src/gps-common/env/weu-prod/backend.tfvars, src/gps-common/env/weu-prod/terraform.tfvars, src/gps/env/weu-prod/backend.ini, src/gps/env/weu-prod/backend.tfvars, src/gps/env/weu-prod/terraform.tfvars, src/shared-common/env/weu-prod/backend.ini, src/shared-common/env/weu-prod/backend.tfvars, src/shared-common/env/weu-prod/terraform.tfvars, src/shared/env/weu-prod/backend.ini, src/shared/env/weu-prod/backend.tfvars, src/shared/env/weu-prod/terraform.tfvars
The purpose of this pr is to add profiles `gps` and `shared` in to pagopa AKS prod
Add : 
- `gps` and `gps-common` env prod 
- `shared` and `shared-common` env prod 
---
=> feat: Add `gps` and  `shared` ns to pagopa AKS prod

src/gps/99_locals.tf, src/shared/99_locals.tf
=> feat: Fix internal platform reference

src/gps-common/03_cosmosdb.tf, src/shared-common/03_cosmosdb_iuvgenerator.tf
=> upd cosmos vnet rules

src/apim_gpd.tf, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
=> feat: Fix deploy gpd gps to prod

src/api/apiconfig_api/auth/v1/_base_policy.xml.tpl, src/api/apiconfig_api/checkout/v1/_openapi.json.tpl, src/api_product/apiconfig_api/_base_policy_auth.xml, src/apim_api_config.tf, src/gpd_payments.tf, src/security.tf
=> add subkey for apiconfig

src/apim.tf
=> add gps grp

src/gpd_payments.tf
=> fix payments gps host

src/aks/03_ingress.tf, src/aks/99_variables.tf, src/aks/README.md, src/aks/env/weu-dev/backend.ini, src/aks/env/weu-dev/terraform.tfvars, src/aks/env/weu-prod/terraform.tfvars, src/aks/env/weu-uat/terraform.tfvars, src/aks/ingress/autoscaling.yaml.tpl
The purpose of this PR is to : 
- add autoscaling to nginx ingress
- pin nginx ingress version as security best practice
Update helm nginx controller
---
=> feat: Add aks ingress autoscaling + pin nginx ingress version as security best practice

src/advanced_fees_management.tf, src/apim_advanced_fees_management.tf, src/variables.tf
Add  cdn and storage account for frontend app.
---
=> [PPR-362] AFM Marketplace (PoC) - FE

src/ecommerce/04_apim_ecommerce.tf, src/ecommerce/api/ecommerce-payment-requests-service/v1/_base_policy.xml.tpl, src/ecommerce/api/ecommerce-payment-requests-service/v1/_openapi.json.tpl
- new ecommerce API to support payment requests, so verificaRPT and verifyPaymentNotice with nodo;
---
=> Chk 585 payment requests

src/shared/api/pagopa-notifications-service/v1/_base_policy.xml.tpl, src/shared/api/pagopa-notifications-service/v1/_openapi.json.tpl
- update API and API policy for `pagopa-notifications-service` in order to handle multi client.
---
=> feat(api): update notifications-service

src/gps-common/02_security.tf, src/gps-common/03_cosmosdb.tf, src/gps-common/README.md, src/gps-common/env/weu-dev/terraform.tfvars, src/gps-common/env/weu-uat/terraform.tfvars, src/outputs.tf
=> fix gps ai conn str

src/appgateway.tf, src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/variables.tf
The purpose of this pr is to overcome size limit of app gtw rewrite rules
> needs to be less than 512 characters. For more details refer to the documentation here: https://aka.ms/appgwheadercrud."
---
=> fix: Split deny path strings

src/api/payment_transactions_gateway_api/external/v1/_base_policy.xml.tpl, src/api/payment_transactions_gateway_api/internal/v1/_base_policy.xml.tpl, src/api/payment_transactions_gateway_api/update/v1/_base_policy.xml.tpl, src/apim_payment_transactions_gateway.tf
- update policy for payment-transaction-gateway-api.
---
=> fix: update policy for pgs

src/api/payment_manager_api/restapi-cd/v3/_swagger.json.tpl
=> feat(api-pec): new searchPsp

src/apim_api_config.tf, src/apim_payment_transactions_gateway.tf
The purpose of this pr is to create separated app registrations for environment for api-config
Depend on https://github.com/pagopa/pagopa-authorization/pull/246
---
=> feat: Apiconfig multi env auth

src/gps/api/spontaneous-payments-service/v1/_openapi.json.tpl
=> feat: Upd swagger payments

src/core/mock_psp.tf
=> feat: add  env profile for mock-psp

.devops/core-code-review-pipelines.yml, src/aks-platform/99_main.tf, src/core/99_main.tf, src/core/README.md, src/domains/afm-app/99_main.tf, src/domains/afm-common/99_main.tf, src/domains/ecommerce-app/99_main.tf, src/domains/ecommerce-common/99_main.tf, src/domains/gps-app/99_main.tf, src/domains/gps-common/99_main.tf, src/domains/shared-app/99_main.tf, src/domains/shared-common/99_main.tf
- now iac code review exclude lock.hcl files
- added purge_soft_delete_on_destroy = false to avoid fails during kv deletes
Allow better control on iac pipelines and kv destruction records
---
=> Minor-fix-tf

src/domains/afm-app/env/weu-dev/terraform.tfvars, src/domains/afm-app/env/weu-uat/terraform.tfvars, src/domains/afm-common/env/weu-uat/terraform.tfvars
=> feat: Dix afm common and app domain env uat vars

src/core/dns_public.tf
=> Reduce DNS TTL for app gateway migration

src/core/api/payment_manager_api/restapi-cd/v3/_base_policy.xml.tpl, src/core/api/payment_manager_api/restapi/v4/_base_policy.xml.tpl, src/core/api/payment_manager_api/wisp/_base_policy.xml.tpl, src/core/apim_payment_manager.tf
- rewrite location header in 302 for `WISP` and `webview payment manager ` when configured for onprem, so only for `pm-host` is configured with ip onprem.
- fix cors configuration for restapi for checkout;
---
=> Rewrite location header for WISP and webview payment manager

src/domains/gps-app/api/spontaneous-payments-service/v1/_openapi.json.tpl
SpontaneousPayments-swagger-update
=> SpontaneousPayments-swagger-update

src/domains/shared-app/api/iuv-generator-service/v1/_openapi.json.tpl
IuvGeneratorService-swagger-update
=> IuvGeneratorService-swagger-update

src/core/README.md, src/core/appgateway.tf, src/core/dns_public.tf, src/core/dns_wisp2_public.tf, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/monitor.tf, src/core/security.tf, src/core/terraform.sh, src/core/variables.tf
```sh
my_env=[dev|uat|prod]
bash terraform.sh apply $my_env \
-target=module.app_gw \
-target=azurerm_dns_a_record.dns_a_api \
-target=azurerm_dns_a_record.dns_a_wisp2_at \
-target=module.web_test_api
```
---
=> [PPR-431] - Add wisp2 endpoint

src/core/api/nodopagamenti_api/nodoPerPM/v2/_swagger.json.tpl
- update swagger NodoPerPM for closepaymentv2
---
=> [PM-1070] update swagger for closepaymentv2

src/core/README.md, src/core/apim.tf, src/domains/afm-app/04_apim_afm_calculator.tf, src/domains/afm-app/04_apim_afm_calculator_data.tf, src/domains/afm-app/04_apim_afm_marketplace.tf, src/domains/afm-app/README.md, src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml, src/domains/afm-app/api/calculator-service/node/v1/_openapi.json.tpl
Added a new product in the APIM: "AFM calculator for Node"
We want expose a subset of the APIs to Nodo dei pagamenti with subscription required
---
=> feat: [AFM] new Product in APIM

src/core/env/prod/terraform.tfvars, src/domains/afm-app/api/marketplace-service/v1/_openapi.json.tpl, src/domains/afm-common/01_network.tf, src/domains/afm-common/02_security.tf, src/domains/afm-common/03_storage.tf, src/domains/afm-common/99_locals.tf, src/domains/afm-common/99_variables.tf, src/domains/afm-common/README.md, src/domains/afm-common/env/weu-dev/terraform.tfvars, src/domains/afm-common/env/weu-prod/terraform.tfvars, src/domains/afm-common/env/weu-uat/terraform.tfvars
- added azure blob container for AFM
---
=> feat: [AFM] Blob container

src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
=> AFM-Calculator-swagger-update

src/domains/afm-app/api/calculator-service/node/v1/_openapi.json.tpl
AFM-Calculator-Node-swagger-update
=> AFM-Calculator-Node-swagger-update

src/core/README.md, src/core/appgateway.tf, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/monitor.tf, src/core/security.tf, src/core/variables.tf
=> [Devops 554] Add endpoint wisp2.pagopa.gov.it

src/domains/afm-app/04_apim_afm_marketplace.tf, src/domains/afm-common/02_security.tf
- enabled product subscription
- added kv
---
=> feat: [AFM] Product subscription, kv

src/core/README.md, src/core/appgateway.tf
=> feat: Add `X-Orginal-Host-For` header in app-gw rewrite rules

src/core/README.md, src/core/api/mockpspservice_api/v1/_base_policy.xml, src/core/api/mockpspservice_api/v1/_swagger.json.tpl, src/core/api_product/mockpspservice_api/_base_policy.xml, src/core/apim_mock_psp_nexi.tf, src/core/env/dev/terraform.tfvars, src/core/variables.tf
Add apim service `https://api.dev.platform.pagopa.it/mock-psp-service/api/v1` pointing out to mock PSP Nexi service
---
=> feat: Add apim mock psp service NEXI sit env

src/domains/selc-app/api/pagopa_token_exchange/jwt_exchange.xml.tpl
changed audience in selfcare token exchange policy
previous audience was wrong
---
=> fix audience for token exchange

src/domains/shared-app/04_apim_pagopa_notifications_service.tf
- Fix wrong api management group
---
=> [CHK-617] fix: apim group

src/core/README.md, src/core/appgateway.tf, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/variables.tf
Add ACL to enable access to web-bo and admin-panel from PagoPA on prem vpn
On cloud migration
---
=> Add ACL to enable access to web-bo and admin-panel from PagoPA on prem vpn

src/domains/afm-app/04_apim_afm_calculator.tf, src/domains/afm-app/README.md
- added `afm-calculator` group
- added relationship between `afm-calculator` and `AFM Calculator pagoPA for Node` product
---
=> feat: [AFM] Added group to product

src/domains/afm-app/99_variables.tf, src/domains/afm-app/README.md
=> fix missing var

src/domains/afm-app/env/weu-prod/terraform.tfvars, src/domains/afm-common/env/weu-prod/terraform.tfvars
=> fix: Add missing lb vars for prod

src/domains/afm-common/env/weu-dev/terraform.tfvars
- env:DEV changed snet to `10.1.155.0`
---
=> feat: [AFM] Change SNET

src/core/api/payment_manager_api/restapi-rtd/v2/_base_policy.xml.tpl, src/core/api/payment_manager_api/restapi-server/v4/_base_policy.xml.tpl, src/core/api/payment_manager_api/restapi/v4/_base_policy.xml.tpl
- fix policy to handle prf env
- fix policy for cors restapi - checkout
---
=> feat: fix policy for Payment Manager

src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
=> fix: Deny path rules on appge UAT and PROD env

src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/domains/afm-app/04_apim_afm_calculator.tf, src/domains/afm-app/04_apim_afm_calculator_data.tf, src/domains/afm-app/04_apim_afm_marketplace.tf, src/domains/afm-common/02_security.tf, src/domains/afm-common/03_cosmosdb_marketplace.tf, src/domains/afm-common/env/weu-prod/terraform.tfvars, src/domains/afm-common/env/weu-uat/terraform.tfvars
=> feat: Add privatelink to cosmo afm , fix db container partitionkey name , disable change for kv value subskey with `lifecycle`

src/domains/gps-common/env/weu-prod/terraform.tfvars, src/domains/gps-common/env/weu-uat/terraform.tfvars
=> fix: Gps cosmos config

src/core/mock_payment_gateway.tf
=> fix: env for prf

src/core/README.md, src/core/apim.tf
=> feat: Add custom domain prf cert on apim

src/core/api/mockec_api/v1/_base_policy.xml, src/core/api/nodopagamenti_api/nodoServices/v1/_base_policy_uat_prf.xml, src/core/apim_mock_ec.tf
=> fix: nodo UAT PRF policy

src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
=> fix deny path GPD GPS Donations IUVGen Payments )

src/core/README.md, src/core/api/apiconfig_api/auth/v1/_base_policy.xml.tpl, src/core/apim.tf
- Creation of grp api-config-be-writer
- Updated policy of apiconfig for Auth.
[Jira Task](https://pagopa.atlassian.net/browse/PCFG-287)
---
=> [ApiConfig] Add group for Writer

src/core/api/nodopagamenti_api/nodoServices/web-bo/v1/_base_policy.xml, src/core/api/payment_manager_api/admin-panel/_base_policy.xml.tpl, src/core/apim_nodo_3p_services.tf, src/core/apim_payment_manager.tf, src/core/appgateway.tf
Enforce IP ACLs from PagoPA VPN using apim policy.
Policy is disabled in UAT until Microsoft ticket response.
---
=> Allow admin-panel and web-bo only from onprem vpn

src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml
- improved mock policy according to [GEC Mock](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/553254913/GEC+Mock)
---
=> feat: [AFM Calculator] Mock policy

src/core/api/checkout/checkout_payment_activations/v1/_swagger.json.tpl, src/core/api/checkout/checkout_payment_activations_auth/v1/_swagger.json.tpl, src/core/api/checkout/checkout_payment_activations_auth/v2/_swagger.json.tpl
=> feat: add due date optional

src/domains/selc-app/04_apim_token_exchange.tf
=> fix selfcare issuer

src/core/README.md, src/core/apim_payment_manager.tf, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/monitor.tf, src/core/observability.tf, src/core/scripts/create_tables.dexp, src/core/variables.tf
The purpose of this PR is to [Ingest data from event hub into Azure Data Explorer](https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub) for Nodo dei Pagamenti RE events
---
=> feat: Add data explorer for RE event

src/core/api/payment_manager_api/admin-panel/_base_policy.xml.tpl, src/core/apim_payment_manager.tf, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
- add `cstar` ip in `admin-panel` withelist;
The goal of this PR is to allow `cstar` to call the `admin-panel` api ( protected with basic authentication).
---
=> [CHK-688] feat: Enable cstar --> admin panel connection

src/core/README.md, src/core/api/mockec_api/secondary_v1/_base_policy.xml, src/core/api/mockec_api/secondary_v1/_swagger.json.tpl, src/core/api/mockec_api/v1/_swagger.json.tpl, src/core/apim_mock_ec.tf, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/variables.tf
=> feat: Secondary mock ec nexi sit

src/core/README.md, src/core/apim_mock_psp_nexi.tf
=> feat: Secondary mock psp sit nexi

src/domains/ecommerce-app/api/ecommerce-sessions-service/v1/_base_policy.xml.tpl
=> feat: add beta blue backend in sesssions policy

src/core/api/checkout/checkout_ecommerce/v1/_openapi.json.tpl
=> fix: delete status update api for ecommerce-checkout

src/core/api/payment_transactions_gateway_api/internal/v1/_openapi.json.tpl
=> fix: delete xclientid in pgs internal

src/domains/ecommerce-app/04_apim_ecommerce.tf, src/domains/ecommerce-app/api/ecommerce-notifications-service/v1/_swagger.json.tpl
=> feat: add api key in notifications service specs

src/core/api/checkout/checkout_ecommerce/v1/_openapi.json.tpl
=> Checkout for eCommerce fix swagger

src/core/mock_payment_gateway.tf
=> fix: env for mock pgs

src/core/api_config.tf, src/core/apim_api_config.tf, src/core/env/prod/terraform.tfvars
- fix autoscaling rules
- fix dns DB nodo dei pagamenti
- changed source of the swagger
---
=> [Api Config] fix ApiConfig

src/domains/afm-common/03_cosmosdb_marketplace.tf, src/domains/afm-common/README.md, src/domains/bizevents-app/99_locals.tf, src/domains/bizevents-app/README.md, src/domains/bizevents-common/env/weu-dev/terraform.tfvars, src/domains/bizevents-common/env/weu-prod/terraform.tfvars, src/domains/bizevents-common/env/weu-uat/terraform.tfvars
- Add cosmosDB container for `afm-marketplace-be`
- Support touchpoint persistency
---
=> [PGEC-83] Add touchpoint container

src/core/README.md, src/core/outputs.tf, src/domains/bizevents-common/02_security.tf, src/domains/bizevents-common/03_storage_account_fn.tf, src/domains/bizevents-common/99_variables.tf, src/domains/bizevents-common/README.md
The purpose of this PR is to add new secret in to kv of bizevents and storage account for az fn trigger
---
=> feat: Add kv secret for biz event data store + storage 4 fn trigger

src/domains/bizevents-app/04_apim_bizevents.tf, src/domains/bizevents-app/api/bizevents-service/v1/_base_policy.xml, src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl, src/domains/bizevents-app/api_product/_base_policy.xml, src/domains/bizevents-app/api_product/bizevents-service/_base_policy.xml, src/domains/bizevents-common/02_security.tf
- Add the cosmos db key secret in key vault definition
- Add apim for biz events service, policy and openapi
---
=> [BizEvents] feat: PPR-497 add cosmos db key secret in kv

src/core/apim_mock_ec_psp_pm_nexi.tf
Expose on apim SIT mock Nexi PM
---
=> feat: Expose on apim SIT mock Nexi PM

src/domains/selfcare-common/02_security.tf, src/domains/selfcare-common/README.md
- [ x Update configuration to existing resources
---
=> fix: Missing kv secrets for selfcare

src/core/api/checkout/checkout_ecommerce/v1/_openapi.json.tpl, src/domains/ecommerce-app/04_apim_ecommerce.tf, src/domains/ecommerce-app/api/ecommerce-payment-requests-service/v1/_base_policy.xml.tpl, src/domains/ecommerce-app/api/ecommerce-payment-requests-service/v1/_openapi.json.tpl
Added new GET carts api for pagopa-ecommerce-payment-requests project
This change was made to give the visibility of a new pagopa-ecommerce-payment-requests project api to the outside world.
---
=> Feat : added GET carts endpoint into payments requests service

src/core/README.md, src/core/apim_payment_manager.tf
=> feat: respapi for backwards compatibility

src/core/README.md, src/core/api/payment_manager_api/restapi-cd/v3/_base_policy.xml.tpl, src/core/api/payment_manager_api/wisp/_base_policy.xml.tpl, src/core/api/payment_manager_api/wisp/_swagger.json.tpl, src/core/apim_payment_manager.tf
=> Location wisp only for gov-it

src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl, src/core/api/nodopagamenti_api/nodeForPsp/v1/nodeForPsp.wsdl, src/core/apim_nodo_services_dev.tf
=> feat: Add sendPaymentOutcomeV2 activatePaymentNoticeV2 nodeForPsp

src/core/api/payment_manager_api/admin-panel/_base_policy.xml.tpl
=> fix: location for admin panel

src/core/README.md, src/core/api/nodopagamenti_api/nodoServices/web-bo-on-prem/v1/_NodoDeiPagamenti.openapi.json.tpl, src/core/api/nodopagamenti_api/nodoServices/web-bo-on-prem/v1/_base_policy.xml, src/core/apim_nodo_3p_services.tf, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
Related to https://github.com/pagopa/org-infra/pull/132
---
=> feat: WebBo prod via `wisp2.pagopa.gov.it`

src/core/env/prod/terraform.tfvars
Add Softlab VPN IPs for assistance tools
Payment Manager migration on cloud
---
=> Add Softlab VPN IPs for assistance tools

src/domains/bizevents-common/02_security.tf, src/domains/bizevents-common/03_cosmosdb_bizevents_datastore.tf, src/domains/bizevents-common/README.md, src/domains/bizevents-common/env/weu-uat/terraform.tfvars
- fix ehub_tx_biz_key from primary connection string to primary key
---
=> fix: Biz-Events event hub publisher key

src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
Update `hot_cache_period` Data Explorer
---
=> feat: Modifica auto scaling DB EXP - PPR-506

src/core/api/mock_payment_gateway_api/v1/_openapi.json.tpl, src/core/api/mock_payment_gateway_mng_api/v1/_openapi.json.tpl
=> feat: update api for mock pgs

src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
Add new biz event topic evh according to [EnrichedEventForPDND](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/578322480/EnrichedEventForPDND)
---
=> feat: Add ehub nodo-dei-pagamenti-biz-evt-pdnd

src/domains/shared-app/03_influxdb.tf, src/domains/shared-app/04_apim_influxdb.tf, src/domains/shared-app/99_variables.tf, src/domains/shared-app/README.md, src/domains/shared-app/api/influxdb/v1/_base_policy.xml, src/domains/shared-app/api/influxdb/v1/_openapi.json.tpl, src/domains/shared-app/api/influxdb/v2/_base_policy.xml, src/domains/shared-app/api/influxdb/v2/_openapi.json.tpl
- added influxdb with helm_release on shared namespace 
to have an instance on AKS
---
=> InfluxDB on AKS

src/domains/load-test/02_iam.tf, src/domains/load-test/README.md
Assign `Grafana Admin` role to `adgroup-developers`
---
=> feat: Grafana Admin Permission to Pagopa Adgroup Developers

src/domains/load-test/01_grafana.tf, src/domains/load-test/README.md, src/domains/load-test/env/weu-dev/terraform.tfvars
Fix wrong cname
Wrong DNS prefix and output from grafana managed module
Depends on: https://github.com/pagopa/terraform-azurerm-v3/pull/4
---
=> Fix: Grafana CNAME

src/core/appgateway.tf
temporary fix waiting for an optimization on admin-panel
---
=> feat: increase timeout app gtw

src/core/node_forwarder.tf
- add kv in node-forwarder
---
=> feat: Added kv to node-forwarder

src/domains/shared-app/.terraform.lock.hcl, src/domains/shared-app/04_apim_influxdb.tf, src/domains/shared-app/README.md, src/domains/shared-app/api_product/_influxdb_policy.xml
=> Policy Influxdb

src/aks-platform/env/weu-prod/terraform.tfvars
=> Upgrade aks prod to 1.23.12

src/domains/shared-common/env/weu-uat/terraform.tfvars
=> Agent Pool Load Test

src/core/README.md, src/core/apim_nodo_services_dev.tf, src/core/node_forwarder.tf
=> fix: Nodo-dev closepayment backend ref

.devops/shared-deploy-pipelines.yml
=> Pipeline depenson fixing

src/core/api/nodopagamenti_api/nodoServices/web-bo-on-prem/v1/_base_policy.xml
=> fix: f5 for webbo

src/core/api/payment_manager_api/payment-transactions-gateway/v1/_openapi.json.tpl
=> feat: add refund in pgs

.gitignore, src/domains/bizevents-common/01_events.tf, src/domains/bizevents-common/02_security.tf, src/domains/bizevents-common/README.md
- added variables for the new enrichment feature 
- call external services
---
=> [PPR-501] enrich biz event: added security variables

src/core/scripts/create_table_config.dexp, src/core/scripts/create_table_nm3_states.dexp, src/core/scripts/create_table_vm3_states.dexp, src/core/scripts/ingestion_grants.dexp
=> feat: Add new table to dataexp

src/core/node_forwarder.tf
- configured autoscaling for node-forwarder microservice
https://pagopa.atlassian.net/wiki/spaces/IQCGJ/pages/587661622/Configurazione+autoscaling
---
=> feat: [PAGOPA-392] Autoscaling node-forwarder

src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml, src/core/apim_nodo_services.tf
=> fix: Add missing fields

src/core/api/nodopagamenti_api/nodoPerPM/v1/_base_policy.xml.tpl, src/core/api/nodopagamenti_api/nodoPerPM/v1/_base_policy_dev.xml.tpl, src/core/api/nodopagamenti_api/nodoPerPM/v1/_closepayment_policy.xml.tpl, src/core/api/nodopagamenti_api/nodoPerPM/v1/_closepayment_policy_dev.xml.tpl, src/core/api/nodopagamenti_api/nodoPerPM/v1/_swagger.json.tpl, src/core/api/nodopagamenti_api/nodoPerPM/v2/_base_policy.xml.tpl, src/core/api/nodopagamenti_api/nodoPerPM/v2/_base_policy_dev.xml.tpl, src/core/apim_nodo_services_dev.tf
=> feat: Add checkPosition NODO_4_PM

src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml, src/core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml
=> fix: Apim 500 activatePaymentNotice and nodoInviaFlussoRendicontazione

src/core/api_logs.tf
=> feat: disable rtd and restapi apim logs

src/core/api/tkm_api/tkm-ms-card-manager/v1/_openapi.json.tpl
- Update `tkm-ms-card-manager` v1 swagger definition
- Add /cards endpoint
---
=> [PM-1250] feat: update swagger definition

src/aks-platform/.terraform.lock.hcl, src/aks-platform/99_main.tf, src/aks-platform/README.md, src/aks-platform/env/weu-dev/terraform.tfvars, src/aks-platform/env/weu-prod/terraform.tfvars, src/aks-platform/env/weu-uat/terraform.tfvars, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/monitor.tf
```sh
./terraform.sh apply weu-dev -target=module.tls_checker
./terraform.sh apply weu-uat -target=module.tls_checker
./terraform.sh apply weu-prod -target=module.tls_checker
./terraform.sh apply dev -target=module.web_test_api -target=azurerm_log_analytics_workspace.log_analytics_workspace
./terraform.sh apply uat -target=module.web_test_api -target=azurerm_log_analytics_workspace.log_analytics_workspace
./terraform.sh apply prod -target=module.web_test_api -target=azurerm_log_analytics_workspace.log_analytics_workspace
```
---
=> Fix TLS healthchecks

src/core/api/nodopagamenti_api/nodeForIO/v1/activateIO_reservation_nm3.xml
=> fix: 500 activateIO_reservation_nm3

src/core/env/prod/terraform.tfvars, src/domains/bizevents-common/03_cosmosdb_bizevents_datastore.tf, src/domains/bizevents-common/env/weu-uat/terraform.tfvars
=> fix : biz prod

src/core/buyerbanks_function.tf, src/core/fdr.tf
=> fix : UAT `core` align

.terraform.lock.hcl, .utils/terraform_run_all.sh, src/domains/gps-app/04_apim_external_payments.tf, src/domains/gps-app/04_apim_internal_payments.tf, src/domains/load-test/.terraform.lock.hcl, src/domains/load-test/01_grafana.tf, src/domains/load-test/README.md, src/domains/selfcare-common/02_security.tf, src/domains/selfcare-common/README.md
- kv: added policy for external team only for dev and uat
Allow the external team to manage the kv in dev and uat
---
=> feat: selfcare common added policy for external team

src/core/env/uat/terraform.tfvars
=> fix: lmi deny path uat

src/domains/gps-common/02_security.tf
Co-authored-by: Angelo Caporaso <AngeloCaporaso@users.noreply.github.com>
Co-authored-by: Andrea De Rinaldis <andrea-deri@users.noreply.github.com>
Adding the necessary subkeys used by the service
This change is required to perform correctly the calls to the services that are involved in the process.
---
=> PAGOPA-599 subkeys generation

src/core/api/payment_manager_api/payment-events/v1/_openapi.json.tpl
=> fix: Refact pm api event

src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
=> feat: Add pn to ehub biz enrich

src/domains/gps-common/02_security.tf, src/domains/gps-common/README.md
- subscription key for payments REST API product added
- subscription key for payments SOAP API product added
- old subscription key definition for payments (only for REST) removed
---
=> PAGOPA-599 payments subscription key split

src/core/README.md, src/core/azure_devops_agent.tf, src/domains/gps-common/00_monitor.tf
- update devops agent version from `v1.0.90` to `v3.5.0`
- Some pipelines need agents with docker-compose. E.g.: [GPD-Payements smoke test stage](https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=65476&view=logs&j=5d8a3be4-6844-551f-a950-ea4245805b20&t=a0001135-552c-55f9-e53b-ae37fcfc8668)
---
=> Update devops Agent

src/domains/nodo-common/03_nodo_postgresql.tf, src/domains/nodo-common/README.md
=> fix : Try Nodo PG 2

src/core/api_product/nodo_pagamenti_api/auth/_base_policy.xml, src/core/apim_nodo_services_auth.tf, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/variables.tf
- added named values
- modified policy for nodo-auth adding `X-Forwarded-For` header field
---
=> feat: Add policy req [PAGOPA-608]

src/core/api_config_fe.tf
=> feat: PAGOPA-209 Added kv [API CFG]

src/core/env/prod/terraform.tfvars
=> feat: Scale up node forwarder to P1v3 SKU

src/core/README.md, src/core/api_config.tf, src/core/apim_nodo_3p_services.tf, src/core/dns_private.tf, src/core/env/prod/terraform.tfvars, src/core/vpn.tf
=> fix : Align prod core phase#1

src/domains/selfcare-app/api/pagopa-selfcare-ms-backoffice/v1/_openapi.json.tpl
updated open api BO Pagopa: add request param to apim "createInstitutionApiKeysUsingPOST"
this parameter identifies the subscription to be created
needs apply in dev
---
=> updated open api selfcare

src/aks-platform/04_rbac.tf, src/domains/nodo-app/03_serviceaccounts_azure_devops.tf, src/domains/nodo-app/README.md, src/domains/nodo-cron/03_serviceaccounts_azure_devops.tf, src/domains/nodo-cron/README.md
=> fix : Add nodo-cron perm aks

src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
=> fix: Verificatore

src/domains/nodo-app/.terraform.lock.hcl, src/domains/nodo-app/02_namespace.tf, src/domains/nodo-app/04_apim_nodo_services_ndp.tf, src/domains/nodo-app/README.md
=> feat: Add apim monitorin nodo ndp + AKS Blueprint upgrade from v1 to v2

src/core/README.md, src/core/apim_nodo_3p_services.tf
The purpose of this PR is to use a for wfesp service according to [documentation](https://pagopa.atlassian.net/wiki/spaces/PPA/pages/563642704/Configurazione+servizi+satelliti+nodo+onCloud+su+APIM+pagoPA)
- WFESP http://wfesp.test.pagopa.gov.it/redirect/wpl02
- WEB-BO  https://uat.wisp2.pagopa.gov.it/bo-nodo/login accessible via [VPN](https://github.com/pagopa/pagopa-infra/blob/1d9aedbbb58b2759d68076e35de0cb6215a88ac3/src/core/env/uat/terraform.tfvars#L121)
---
=> fix: Apim wfesp web-bo uat

src/domains/ecommerce-common/env/weu-dev/terraform.tfvars, src/domains/ecommerce-common/env/weu-uat/terraform.tfvars
=> fix: BoundedStaleness for ecommerce cosmosdb

src/core/README.md, src/core/env/prod/terraform.tfvars, src/core/network.tf, src/core/variables.tf, src/domains/nodo-secret/02_security.tf, src/domains/nodo-secret/99_main.tf
=> feat: Enable DDoS protection

src/core/env/prod/terraform.tfvars
=> feat: Tuning autoscaling apim and app gateway

.devops/ecommerce-deploy-pipelines.yml
=> fix: delete aks refs in  ecommerce-common pipelines

src/domains/nodo-app/04_apim_wfesp.tf, src/domains/nodo-app/api/wfesp-service/v1/_WFESP.openapi.json.tpl, src/domains/nodo-app/api/wfesp-service/v1/_base_policy.xml, src/domains/nodo-app/api_product/wfesp-service/_base_policy.xml
=> feat: Add wfesp apim

src/domains/nodo-app/04_apim_mock_ec.tf, src/domains/nodo-app/04_apim_mock_psp.tf, src/domains/nodo-app/04_apim_prometheus.tf, src/domains/nodo-app/04_apim_webbo.tf, src/domains/nodo-app/README.md, src/domains/nodo-app/api/mock-ec-service/v1/_base_policy.xml, src/domains/nodo-app/api/mock-ec-service/v1/_mock-ec.openapi.json.tpl, src/domains/nodo-app/api/mock-psp-service/v1/_base_policy.xml, src/domains/nodo-app/api/mock-psp-service/v1/_mock-psp.openapi.json.tpl, src/domains/nodo-app/api_product/mock-ec-service/_base_policy.xml, src/domains/nodo-app/api_product/mock-psp-service/_base_policy.xml
ingresses for mock-ec and mock-psp
---
=> feat: NOD-56-migrazione-mocks-pa-psp

src/aks-platform/05_monitoring.tf, src/aks-platform/99_variables.tf, src/aks-platform/env/weu-dev/kube-prometheus-stack-helm/prometheus-basic-auth, src/aks-platform/env/weu-dev/kube-prometheus-stack-helm/values.yaml, src/aks-platform/env/weu-dev/terraform.tfvars
=> feat: Add prometheus basic auth

src/aks-platform/env/weu-dev/kube-prometheus-stack-helm/values.yaml
=> feat: Fix nginx ingress for prometheus

src/aks-platform/05_monitoring.tf, src/aks-platform/99_variables.tf, src/aks-platform/README.md, src/aks-platform/env/weu-dev/terraform.tfvars
=> feat: format

src/domains/nodo-app/04_apim_nodo_services_ndp.tf
=> feat: Fix module.apim_nodo_per_pm

src/core/dns_private.tf, src/domains/nodo-common/01_network.tf, src/domains/nodo-common/07_sftp.tf, src/domains/nodo-common/99_locals.tf, src/domains/nodo-common/99_variables.tf, src/domains/nodo-common/README.md, src/domains/nodo-common/env/weu-dev/terraform.tfvars, src/domains/nodo-common/env/weu-uat/terraform.tfvars
=> feat: Add sftp nodo

src/domains/nodo-app/04_apim_mock_ec_secondary.tf, src/domains/nodo-app/04_apim_mock_psp_secondary.tf, src/domains/nodo-app/api/mock-ec-secondary-service/v1/_base_policy.xml, src/domains/nodo-app/api/mock-ec-secondary-service/v1/_mock-ec-secondary.openapi.json.tpl, src/domains/nodo-app/api/mock-psp-secondary-service/v1/_base_policy.xml, src/domains/nodo-app/api/mock-psp-secondary-service/v1/_mock-psp-secondary.openapi.json.tpl, src/domains/nodo-app/api_product/mock-ec-secondary-service/_base_policy.xml, src/domains/nodo-app/api_product/mock-psp-secondary-service/_base_policy.xml
=> feat: Add secondary instance

src/core/README.md, src/core/dns_private.tf, src/core/env/dev/terraform.tfvars, src/domains/nodo-app/04_apim_nodo_pg.tf, src/domains/nodo-common/env/weu-uat/terraform.tfvars
=> feat: Align uat nodo ndp

src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl, src/core/api/nodopagamenti_api/nodoPerPa/v1/auth/NodoPerPa.wsdl
=> fix: Align wsdl auth to SANP 3.3.0

src/domains/afm-app/04_apim_afm_marketplace.tf, src/domains/afm-app/README.md, src/domains/afm-app/api/marketplace-service/utils/_base_policy.xml, src/domains/afm-app/api/marketplace-service/utils/_openapi.json.tpl
added new openapi file for AFM Utils
---
=> AFM-Util Openapi

src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf, src/domains/ecommerce-app/99_variables.tf, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_auth_request.xml.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_base_policy.xml.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_recaptcha_check.xml.tpl, src/domains/ecommerce-app/env/weu-dev/terraform.tfvars, src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
- add ecommerce checkout API in ecommerce domain
The goal of this PR is to create a new product & API in ecommerce domain dedicated to checkout pagoPA.
In a dedicated PR [these API](https://github.com/pagopa/pagopa-infra/blob/a01315942e2483bc86c04c65d9f4e3ffc20224b6/src/core/apim_checkout.tf#L282) will be removed.
---
=> feat:  CHK-995 ecommerce checkout API in ecommerce domain

src/aks-platform/05_monitoring.tf, src/aks-platform/env/weu-uat/kube-prometheus-stack-helm/prometheus-basic-auth, src/aks-platform/env/weu-uat/kube-prometheus-stack-helm/values.yaml, src/aks-platform/env/weu-uat/terraform.tfvars
Depend on https://github.com/pagopa/pagopa-infra/tree/add-elk-on-aks
---
=> feat: Change prometheus namespace

src/domains/nodo-app/04_apim_nodo_services_ndp.tf
=> fix ndp product

src/domains/selfcare-app/04_apim_api_config.tf, src/domains/selfcare-app/README.md, src/domains/selfcare-app/api/pagopa-api-config/v1/_base_policy.xml, src/domains/selfcare-app/api/pagopa-api-config/v1/_openapi.json.tpl
Created new apim resource for backoffice pagopoa
Created new apim resource for backoffice pagopoa for be API
Exposes the API to allow the frontend to reach the backend
---
=> create new resource apim for api apiConfig for auth

src/core/api/nodopagamenti_api/nodoServices/wfesp/v1/_base_policy.xml
=> fix: wfesp backend-service with redirect

src/core/env/uat/terraform.tfvars, src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
=> fix: Add evh uat and ai conn str NDP

src/domains/nodo-common/03_postgresql.tf, src/domains/nodo-common/99_variables.tf, src/domains/nodo-common/env/weu-dev/terraform.tfvars, src/domains/nodo-common/env/weu-uat/terraform.tfvars
=> feat: Duplicate db

src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
=> add: Ndp apikey

src/core/security.tf, src/domains/afm-common/02_security.tf, src/domains/bizevents-common/02_security.tf, src/domains/ecommerce-common/02_security.tf, src/domains/gps-common/02_security.tf, src/domains/nodo-secret/02_security.tf, src/domains/shared-common/02_keyvault.tf
=> feat: Add perms kv uat dev grp

.gitignore, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/psql/nodo/liquibase/dump.sh
=> add: Deny path only vpn ndp product

src/domains/bizevents-app/04_apim_bizevents.tf, src/domains/nodo-secret/02_security.tf, src/domains/nodo-secret/README.md
-  added ```subscription_required = true``` for bizevent API
---
=> feat: [BizEvent] fix subkey required

src/domains/ecommerce-app/04_apim_ecommerce.tf, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_base_policy.xml.tpl, src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
=> feat: rename methods-service API

src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_carts_redirect.xml.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_checkout_redirect.xml.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
- API to redirect` Cart -> checkout` with `http-equiv`
---
=> feat: CHK-1010 add get to redirect checkout

src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl, src/core/api/nodopagamenti_api/nodoPerPa/v1/auth/NodoPerPa.wsdl, src/core/api/nodopagamenti_api/nodoPerPsp/v1/auth/nodoPerPsp.wsdl, src/core/api_product/nodo_pagamenti_api/auth/_base_policy.xml, src/core/apim_api_config.tf, src/core/apim_nodo_3p_services.tf
=> bug: PAGOPA-634 Added all api to nodo-auth, fix policy

src/core/README.md, src/core/api/nodopagamenti_api/nodoServices/web-bo-history-on-prem/v1/_NodoDeiPagamenti.openapi.json.tpl, src/core/api/nodopagamenti_api/nodoServices/web-bo-history-on-prem/v1/_base_policy.xml, src/core/apim_nodo_3p_services.tf
=> fix: Webbo history endpoint ( onprem and oncloud )

src/psql/nodo/liquibase/changelog/cfg/0/common/db.changelog-configs.xml
=> feat: Fix liquibase config key lisPay

src/aks-platform/04_rbac.tf
=> feat: Add jobs to cluster role

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_base_policy.xml.tpl
=> feat: add Authorization for ecommerce for checkout

src/domains/nodo-app/env/weu-dev/terraform.tfvars, src/domains/nodo-app/env/weu-prod/terraform.tfvars, src/domains/nodo-app/env/weu-uat/terraform.tfvars, src/domains/nodo-cron/env/weu-dev/terraform.tfvars, src/domains/nodo-cron/env/weu-prod/terraform.tfvars, src/domains/nodo-cron/env/weu-uat/terraform.tfvars
=> fix: Node pool

src/core/api/payment_transactions_gateway_api/external/v1/_openapi.json.tpl
=> feat: CHK-1121 add enum for status pgs

CODEOWNERS
=> feat: Add Andrea as Codeowner of selfcare domain

src/core/.terraform.lock.hcl, src/core/apim_donations.tf, src/core/apim_donazione_ucraina.tf
=> feat: Disable dona ucraina

src/core/README.md, src/core/appgateway.tf, src/core/gpd.tf, src/core/security.tf
Adding gpd subscription key to keyvault
This was required by the performance test pipeline
---
=> feat: Adding gpd subscription key PAGOPA-705

src/core/api/payment_transactions_gateway_api/internal/v1/_openapi.json.tpl
=> fix: field name pgs

src/elk-monitoring/05_elastic_stack.tf
=> feat: Fix elastic namespace

src/core/README.md, src/core/api/nodopagamenti_api/nodeForPa/v1/NodeForPa.wsdl, src/core/api/nodopagamenti_api/nodeForPa/v1/_base_policy.xml.tpl, src/core/api/nodopagamenti_api/nodeForPa/v1/auth/NodeForPa.wsdl, src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl, src/core/apim_nodo_services_auth.tf
- added primitive to node for psp
- added node for pa
---
=> feat: [PAGOPA-725] WSDL nuova connettività

src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl
- fix WSDL node-for-psp
- 
---
=> feat: Fix node-auth wsdl

src/core/api/nodopagamenti_api/nodeForPsp/v1/auth/nodeForPsp.wsdl
- fix about nodoInviaFlussoRendicontazione in nodo-auth/node-for-psp
---
=> fix: PAGOPA-757 WSDL nodo-auth nodoInviaFlussoRendicontazione

src/core/gpd.tf
Editing scale thresholds for gpd microservice
This was realized to improve performance and do not perform a scale up of the machines if it was not needed. 
---
=> feat: editing gpd scaling thresholds

src/elk-monitoring/05_elastic_stack.tf
=> feat: Fix elk

src/core/README.md, src/core/env/dev/terraform.tfvars, src/core/node_forwarder.tf, src/core/variables.tf
updated autoscale settings for Node Forwader
---
=> [PAGOPA-760] Autoscale Node Forwarder

src/domains/ecommerce-common/03_storage.tf, src/domains/ecommerce-common/README.md, src/elk-monitoring/README.md
Refactoring of all ecommerce queues to change from an `queue for event` approach to `queue for behaviour`approach.
Those modifications are needed in order to clarify the scope of each queue
---
=> Chk 1193 ecommerce queues refactoring

src/core/apim_donations.tf, src/core/apim_donazione_ucraina.tf
=> feat: Enable dona tmp

src/core/README.md, src/core/api/mockec_api/forwarder/_base_policy.xml, src/core/api/mockec_api/forwarder/_swagger.json.tpl, src/core/apim_mock_ec.tf, src/core/node_forwarder.tf
- added mock ec for node forwarder
- new properties for node forwarder
---
=> node forwarder

src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
added lightbend-key secret for nodo
---
=> feat: Nod 143 licenza lightbend

src/core/api_config.tf
=> feat: [PAGOPA-601] Add vars to API Config

src/core/.terraform.lock.hcl, src/core/api/gpd_api/reporting_analysis/v1/_openapi.json.tpl
This pull request contains the update of `_openapi.json.tpl` file made in order to add a new query parameter in `organizations/{organizationId}/reportings` API for the search by flow date.
- Updated OpenAPI file for GPD reporting analysis service
The changes are needed in order to add the query parameter to the defined API.
=> [PAGOPA-735] Added query parameter on report search

src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml
- update responses about mock test cases
---
=> feat: [PAGOPA-765] Fix AFM Calculator mock

src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
=> feat: Lightbend-key prod

src/elk-monitoring/.terraform.lock.hcl, src/elk-monitoring/01_aks.tf, src/elk-monitoring/05_elastic_stack.tf, src/elk-monitoring/README.md, src/elk-monitoring/env/weu-prod/terraform.tfvars, src/elk-monitoring/env/weu-uat/terraform.tfvars
=> feat: Fix es config

src/core/apim_node_forwarder.tf
=> feat: PAGOPA-773 added subscription-required to forwarder

src/elk-monitoring/05_elastic_stack.tf
=> feat: Fix logstash

src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json, src/psql/nodo/liquibase/changelog/cfg/3.14.0/db.changelog-20230314090150_target_columns.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.14.0.xml, src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.14.0.xml, src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.14.0.xml, src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.14.0.xml, src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.14.0.xml, src/psql/nodo/liquibase/run.sh
Added secret for node forwarder
Added nodo liquibase script
---
=> feat: Nod 146 target columns

src/elk-monitoring/99_locals.tf, src/elk-monitoring/README.md
=> fix : Weuprod-kibana-internal-platform-pagopa

src/core/api/nodopagamenti_api/nodoServices/wfesp/v1/_base_policy.xml, src/core/apim_nodo_3p_services.tf, src/core/env/prod/terraform.tfvars
```
sh terraform.sh plan prod \
-target=azurerm_dns_a_record.dns_a_kibana \
-target=azurerm_private_dns_zone_virtual_network_link.privatelink_blob_azure_com_vnet_integration \
-target=module.apim_nodo_wfesp_api \
-target=module.apim_nodo_wfesp_product \
-target=module.app_gw
```
---
=> feat: Add wfesp onprem prod

src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
=> feat: NOD-113 added nodo secret api-config-cache-subscription-key-string

src/domains/apiconfig-app/README.md, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transaction-auth-requests-service/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl, src/domains/fdr-app/99_locals.tf, src/domains/fdr-common/99_locals.tf, src/elk-monitoring/README.md
Align ecommerce transactions-service statuses
Align ecommerce transactions-service statuses
---
=> Chk 1277 align specifications

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Added 409 error code for **DELETE** transaction API.
Added handling of error 409 alreadyProcessed for DELETE transaction api.
---
=> Added 409 error code for delete transaction

src/core/README.md, src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf, src/domains/ecommerce-app/README.md
Added JWT policy for **DELETE** transaction for  **ecommerce-checkout** api
Added resource for execute JWT  check when call DELETE transaction api
---
=> feat: added policy jwt for delete transaction

src/core/README.md, src/domains/ecommerce-common/03_storage.tf, src/domains/ecommerce-common/README.md
Add ecommerce notification-retry-queue where will be enqueued events to trigger user receipt notification retry
Add new queue that will be consumed by ecommerce event dispatcher for retry notification 
---
=> Chk 1293 add notify retry queue

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_base_policy.xml.tpl
Added DELETE method into allowed-methods for CORS check.
Modified base policy to perform transaction DELETE without CORS error
---
=> fix_base_policy_checkout_cors

src/domains/selfcare-common/02_security.tf, src/domains/selfcare-common/03_cosmosdb_bopagopa_datastore.tf, src/domains/selfcare-common/99_variables.tf, src/domains/selfcare-common/README.md, src/domains/selfcare-common/env/weu-dev/terraform.tfvars, src/domains/selfcare-common/env/weu-prod/terraform.tfvars, src/domains/selfcare-common/env/weu-uat/terraform.tfvars
cosmo db resource  created
---
=> feat: Create cosmo db SELFCARE

src/domains/shared-app/04_apim_statuspage.tf
- add `reporting-orgs-enrollment` among services in status page apim
- the purpose is to expose the health check of` reporting orgs enrollment` on the status page
---
=> feat: Add service in status page apim [gpd]

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
Ecommerce payment methods api specification review
Those modifications are needed in order to let payment-method be compliant with API specification guidelines
---
=> fix: ecommerce payment methods api

src/core/network.tf
=> feat: Add database nodo on cloud routing

src/domains/apiconfig-app/05_tls_checker.tf, src/domains/apiconfig-app/99_main.tf, src/domains/apiconfig-app/README.md
depends on https://github.com/pagopa/terraform-azurerm-v3/pull/96
- fix tls checker in apiconfig domain 
- 
---
=> fix: API-Config TLS checker

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transaction-auth-requests-service/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
* feat(ecommerce): add `NOTIFICATION_ERROR` to transaction status enumeration in APIs
---
=> feat(ecommerce): add `NOTIFICATION_ERROR` to transaction status enumeration in APIs

src/core/api/checkout/checkout_ecommerce/v1/_auth_request.xml.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_auth_request.xml.tpl
- Update `/auth-requests` policy to handle unmatched PSP - gateway with a 400 - Bad Request error
- Handle config error
---
=> [CHK-1335] fix: update auth-requests apim policy

src/core/api/checkout/checkout_ecommerce/v1/_auth_request.xml.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_auth_request.xml.tpl
- Add body for 400 invalid idPsp error
---
=> [CHK-1335] fix: eCommerce for checkout auth request policy

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Update PaymentInfoDto
Update PaymentInfo Dto adding transfer list field
the list is made of Transfer object with fields coming from activateV2 nodo 
Change ecommerce acrivate nodo interaction using activatev2 call
---
=> [CHK-1131] update payment info

src/domains/ecommerce-common/03_storage.tf, src/domains/ecommerce-common/README.md, src/domains/gps-common/README.md
Add `transactions_notifications_queue` used by transactions service for send email to user
Transactions service will send new events on this queue for trigger user notification mail sending mechanism
---
=> feat: add ecommerce notifications queue

src/domains/nodo-common/.terraform.lock.hcl, src/domains/nodo-common/03_postgresql.tf, src/domains/nodo-common/04_datafactory.tf, src/domains/nodo-common/07_sftp.tf, src/domains/nodo-common/99_main.tf, src/domains/nodo-common/README.md
=> feat : Nodo-common from v2 to v3 `azurerm`

src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
=> fix: Update ligthbend key

src/core/apim_nodo_services.tf
=> fix: Nodo monitoring

src/domains/afm-app/api/marketplace-service/utils/_openapi.json.tpl, src/domains/afm-app/api/marketplace-service/v1/_openapi.json.tpl
=> feat: Update AFM Marketplace /Utils openapi

src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
Add PSP with id `60000000001` into XPAY psp list
This modification is needed in order to configure psp for XPAY correctly
---
=> fix: xpay psp list

src/core/api/payment_manager_api/pm-per-nodo/v2/_base_policy.xml.tpl
=> fix: sendpaymentresultV2

src/domains/selfcare-app/04_apim_api_config.tf, src/domains/selfcare-app/api/pagopa-api-config/v1/_base_policy.xml, src/domains/selfcare-app/api/pagopa-api-config/v1/_openapi.json.tpl
add getCreditorInstitutionDetails from apiconfig for auth via backoffice platform
---
=> add getCreditorInstitutionDetails to backoffice-apiconfig

src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
NOD-216: subscription-key UAT e PROD
---
=> feat: NOD-177: Aggiungere a pagoPa la chiave per la sendPaymentResult UAT-PRF

src/core/api/payment_transactions_gateway_api/pgs-fe/v1/_openapi.json.tpl
- Update pgse-fe openapi definitions
- Allow client autogen
---
=> [CHK-1407] fix: update pgs-fe openapi definitions

src/core/api_config.tf, src/domains/apiconfig-common/00_github_runner.tf, src/domains/apiconfig-common/README.md
- added ENV to apiconfig only for PROD environment
a property is missing
---
=> [PAGOPA-868] add ENV to apiconfig

src/core/README.md, src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl, src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml, src/core/apim_nodo_services.tf
=> fix: Error APIM on missing field req

src/core/appgateway.tf
=> fix: Increase timeout APP Gateway for APIM

src/core/api/nodopagamenti_api/nodeForPsp/v1/nodeForPsp.wsdl
Add - transferCategory field inside transfer object
wsdl alignement following the development on Nodo dei pagamenti side
- [] Yes, users may be impacted applying this change
---
=> add - transfer category inside transfer

src/core/api_product/nodo_pagamenti_api/decoupler/base_policy.xml.tpl, src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
=> fix : Apim nodo soap req missing field

src/domains/wallet-app/api/wallet-service/v1/_openapi.json.tpl
Update wallet api
Update wallet api
---
=> [CHK-1423] feat: update wallet api

src/domains/wallet-app/api/wallet-service/v1/_openapi.json.tpl
=> feat: update wallet id

src/domains/selfcare-app/api/pagopa-api-config/v1/_openapi.json.tpl
updated api docs
i need to expose a new api on apim
---
=> exposed new apim api

src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
=> feat: update plan for buyer-banks function

src/elk-monitoring/05_elastic_stack.tf, src/elk-monitoring/05_kibana_log_pagopafdr.tf
=> feat: Add log

src/core/README.md, src/core/apim_nodo_services.tf
=> fix: Plan prod core

src/core/appgateway.tf
=> fix: Kibana fqnd listner

src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
- added evt hub for negative biz event
- added connection-string to nodo-kv
---
=> feat: [NOD-208] Added Negative Biz-Evt

src/core/README.md, src/core/monitor.tf, src/core/node_forwarder.tf, src/core/security.tf
```
sh terraform.sh apply <ENV> \
-target=azurerm_key_vault_secret.newconn_opsgenie_webhook_token \
-target=azurerm_monitor_action_group.new_conn_srv_opsgenie \
-target=azurerm_monitor_scheduled_query_rules_alert.opex_pagopa-node-forwarder-responsetime-upd \
-target=azurerm_monitor_scheduled_query_rules_alert.opex_pagopa-node-forwarder-availability-upd
```
---
=> feat: Opsgenie nuova connettività [IMP-52]

src/core/env/uat/terraform.tfvars, src/domains/fdr-app/05_aks_middleware_tools.tf, src/domains/fdr-app/99_locals.tf
=> feat: Enabled apim_fdr_nodo_pagopa_enable UAT

src/domains/gps-app/04_apim_internal_payments.tf, src/domains/gps-app/terraform.sh
- Update apim_gpd_payments_soap_api to 0
- Add new terraform.sh script
---
=> fix: Set apim_gpd_payments_soap_api to 0

src/domains/bizevents-app/00_alert.tf, src/domains/bizevents-app/README.md
=> feat: Runbook alert biz event

src/domains/ecommerce-app/README.md, src/domains/ecommerce-common/.terraform.lock.hcl, src/domains/ecommerce-common/02_security.tf, src/domains/ecommerce-common/03_cosmosdb.tf, src/domains/ecommerce-common/03_redis.tf, src/domains/ecommerce-common/03_storage.tf, src/domains/ecommerce-common/99_main.tf, src/domains/ecommerce-common/99_variables.tf, src/domains/ecommerce-common/README.md, src/domains/ecommerce-common/env/weu-dev/terraform.tfvars, src/domains/ecommerce-common/env/weu-uat/terraform.tfvars, src/domains/nodo-secret/README.md
=> feat: Ecommerce common migration v3

src/core/api/payment_transactions_gateway_api/internal/v1/_openapi.json.tpl
=> fix: pgs internal spec

.devops/checkout-code-review-pipelines.yml, .devops/checkout-deploy-pipelines.yml
=> feat: [CHK-1447] Add iac pipeline for checkout

src/core/README.md, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/messages.tf, src/core/variables.tf, src/domains/bizevents-common/01_events.tf, src/domains/bizevents-common/02_security.tf, src/domains/bizevents-common/03_cosmosdb_bizevents_datastore.tf, src/domains/bizevents-common/03_cosmosdb_negative_bizevents_datastore.tf, src/domains/bizevents-common/99_variables.tf, src/domains/bizevents-common/README.md, src/domains/bizevents-common/env/weu-dev/terraform.tfvars, src/domains/bizevents-common/env/weu-prod/terraform.tfvars, src/domains/bizevents-common/env/weu-uat/terraform.tfvars
=> feat: Add negative biz-events resources [PAGOPA-783]

src/domains/ecommerce-common/02_security.tf
=> feat: add notifications-sender in kv

src/domains/ecommerce-app/api/ecommerce-transaction-user-receipts-service/v1/_openapi.json.tpl
Edit send payment result request body
remove office name and company name from required fields
---
=> [CHK-1515] SendPaymentResult: define required fields

src/domains/checkout-app/01_monitor.tf, src/domains/checkout-app/02_security.tf, src/domains/checkout-app/05_checkout_function.tf, src/domains/checkout-app/99_locals.tf, src/domains/checkout-app/99_variables.tf, src/domains/checkout-app/README.md, src/domains/checkout-app/env/weu-dev/terraform.tfvars, src/domains/checkout-app/env/weu-prod/terraform.tfvars, src/domains/checkout-app/env/weu-uat/terraform.tfvars, src/domains/checkout-app/import_dev.sh, src/domains/checkout-app/import_prod.sh, src/domains/checkout-app/import_uat.sh, src/domains/checkout-app/imported_resources, src/domains/checkout-common/generate_imports.py
* import Checkout functions into Checkout domain
Part of the migration effort of Checkout into a separate domain
Previous PRs:
- #948
- #956 
Depends on #956 
---
=> [CHK-1449] feat(checkout-domain): import Checkout functions into checkout-app domain

src/domains/shared-app/.terraform.lock.hcl, src/domains/shared-app/02_namespace.tf, src/domains/shared-app/04_apim_authorizer.tf, src/domains/shared-app/04_apim_influxdb.tf, src/domains/shared-app/04_apim_iuvgenerator.tf, src/domains/shared-app/04_apim_reporting_orgs_enrollment.tf, src/domains/shared-app/04_apim_statuspage.tf, src/domains/shared-app/05_authorizer_functions.tf, src/domains/shared-app/10_aks_middleware_tools.tf, src/domains/shared-app/99_main.tf, src/domains/shared-app/99_variables.tf, src/domains/shared-app/README.md, src/domains/shared-app/migrate.md, src/domains/shared-common/.terraform.lock.hcl, src/domains/shared-common/02_security.tf, src/domains/shared-common/03_cosmosdb_authorizer.tf, src/domains/shared-common/03_cosmosdb_iuvgenerator.tf, src/domains/shared-common/03_storage_account.tf, src/domains/shared-common/98_agent.tf, src/domains/shared-common/99_main.tf, src/domains/shared-common/99_variables.tf, src/domains/shared-common/README.md
shared app and common domain to azure rm v3
applied in dev
migration of shared-app for other environments requires manual action, which is described in `migration.md` file
---
=> feat: Migrated shared-app and common to azurerm v3

src/domains/gps-app/.terraform.lock.hcl, src/domains/gps-app/05_gpd_reporting_functions.tf, src/domains/gps-app/env/weu-dev/terraform.tfvars, src/domains/gps-app/env/weu-prod/terraform.tfvars, src/domains/gps-app/env/weu-uat/terraform.tfvars, src/domains/gps-common/.terraform.lock.hcl
=> chore: Upgrade azure function runtime version

.devops/nodo-db-migration-pipelines.yml, src/psql/nodo/liquibase/changelog/cfg/3.10.0/db.changelog-0-colums-to-delete.xml, src/psql/nodo/liquibase/changelog/cfg/3.18.0/db.changelog-20230502104500_aggiunta_flag_psp_cp.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.10.0.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.18.0.xml, src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.18.0.xml, src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.18.0.xml, src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.18.0.xml, src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.18.0.xml, src/psql/nodo/liquibase/run.sh
=> feat: [PAG-2552] Added field flag_psp_cp to canali_nodo

src/domains/shared-app/04_apim_enrolled_ec.tf, src/domains/shared-app/05_authorizer_functions.tf, src/domains/shared-app/99_locals.tf, src/domains/shared-app/README.md, src/domains/shared-app/api/enrolled-orgs/v1/_base_policy.xml, src/domains/shared-app/api/enrolled-orgs/v1/_openapi.json.tpl, src/domains/shared-app/api_product/_base_policy_internet.xml
The purpose of this pr is to add apim to retrive ec enroll according to [doc](https://pagopa.atlassian.net/wiki/spaces/IQCGJ/pages/626491723/Design+Review+Autorizzatore#API---Get-enrolled-EC)
---
=> feat: Add ec enroll api for pn

src/domains/checkout-app/04_apim_checkout.tf, src/domains/checkout-app/04_apim_checkout_ec.tf, src/domains/checkout-app/99_variables.tf, src/domains/checkout-app/README.md, src/domains/checkout-app/env/weu-dev/terraform.tfvars, src/domains/checkout-app/env/weu-prod/terraform.tfvars, src/domains/checkout-app/env/weu-uat/terraform.tfvars, src/domains/checkout-app/import_dev.sh, src/domains/checkout-app/import_prod.sh, src/domains/checkout-app/import_uat.sh, src/domains/checkout-app/imported_resources
* import Checkout CDN into checkout domain
Part of the migration effort of Checkout into a separate domain
Previous PRs:
- #948
- #956
- #959
- #963
Depends on #963 
---
=> [CHK-1449] feat(checkout-domain): import Checkout APIM logging into checkout domain

src/domains/bizevents-common/03_cosmosdb_bizevents_datastore.tf, src/domains/bizevents-common/03_cosmosdb_negative_bizevents_datastore.tf
=> fix: Negative biz prod

src/domains/bizevents-common/01_events.tf, src/domains/bizevents-common/02_security.tf, src/domains/bizevents-common/README.md
Adding two connection strings for the event hubs to the biz evt kv for the integration tests of negative events
This change was needed for the correct behavior of the integration tests of the negative events
---
=> Pagopa 911 biz evt test gestione eventi negativi per pdnd

src/domains/selfcare-common/03_cosmosdb_bopagopa_datastore.tf
=> fix: Selfcare mongo access

src/domains/fdr-common/03_storage_account.tf, src/domains/fdr-common/99_variables.tf
=> feat: [NOD-277] Add fdr storage

src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json, src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json, src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
=> feat: Add mongo & otel token fdr

.devops/afm-code-review-pipelines.yml, .devops/afm-deploy-pipelines.yml, .devops/bizevents-code-review-pipelines.yml, .devops/bizevents-deploy-pipelines.yml, .devops/checkout-code-review-pipelines.yml, .devops/checkout-deploy-pipelines.yml, .devops/core-code-review-pipelines.yml, .devops/core-deploy-pipelines.yml, .devops/ecommerce-code-review-pipelines.yml, .devops/ecommerce-deploy-pipelines.yml, .devops/fdr-db-migration-pipelines.yml, .devops/fdr-db-schema-pipelines.yml, .devops/gps-code-review-pipelines.yml, .devops/gps-deploy-pipelines.yml, .devops/nodo-code-review-pipelines.yml, .devops/nodo-db-migration-pipelines.yml, .devops/nodo-db-schema-pipelines.yml, .devops/nodo-deploy-pipelines.yml, .devops/selfcare-code-review-pipelines.yml, .devops/selfcare-deploy-pipelines.yml, .devops/shared-code-review-pipelines.yml, .devops/shared-deploy-pipelines.yml, .devops/wallet-code-review-pipelines.yml, .devops/wallet-deploy-pipelines.yml, .devops/web-bo-db-migration-pipelines.yml, .devops/web-bo-db-schema-pipelines.yml, src/core/README.md, src/domains/aca-common/README.md
Changed pipelines agent reference, to allow to use the new agents dedicated
---
=> fix: Pipelines infra now use infra scale set

src/domains/gps-app/api/payments-service/v1/soap/paForNode.wsdl, src/domains/shared-common/00_github_runner.tf
=> new wsdl for GPS payments

src/core/README.md, src/domains/aca-common/01_network.tf, src/domains/aca-common/99_locals.tf, src/domains/aca-common/README.md
Add aks dns record resource for ACA domain
Add aks dns record resource for ACA domain
---
=> fix: add aks dns record

src/domains/aca-common/02_security.tf, src/domains/aca-common/README.md
Add secrets for GDP and API-config services
Those secrets will hold api key to be used for call GDP and API-Config services
---
=> feat: add api key secrets for GDP and API config

src/core/README.md, src/core/apim_mock_ec.tf, src/core/apim_mock_payment_gateway.tf, src/core/dns_plaftorm.tf
=> feat: Add ses aws dns config `platform.pagopa.it`

src/core/appgateway.tf, src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/variables.tf
=> feat: Add appgw rewrite-rule for kibana

src/core/api/nodopagamenti_api/nodoPerPM/v2/_swagger.json.tpl
Added query parameter **clientId** for close payment request.
The change was made to allow the enhancement of the query parameter clientId in the close payment request.
---
=> CHK-1621 feat: added new query paramenter clientId for the close payment request

src/domains/shared-app/api/pdf-engine/v1/_openapi.json.tpl
- Updated openapi specs for pdf-engine in shared, changing service endpoint from pdf-engine to generate-pdf
Fixing wrongly inserted api reference
---
=> [PRDP-34] fix: Update pdf-engine openapi specs

src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
The purpose of this PR is to add some secret useful for az fn pdf receipt
---
=> [PRDP-35] feat: add receipt secrets

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Add NOT_RECEIVED enumeration status for sendPaymentResultOutcome field
Add NOT_RECEIVED enumeration status for sendPaymentResultOutcome field
---
=> Chk 1637 send payment result outcome

src/domains/shared-app/02_keyvault.tf, src/domains/shared-app/05_authorizer_functions.tf, src/domains/shared-app/api/enrolled-orgs/v1/_openapi.json.tpl, src/domains/shared-common/02_security.tf
This pull request contains several changes made on Authorizer project in order to develop an enhancement on enrolled EC's API.
- Added new secrets and parameter to the function app
- Updated OpenAPI including response specification
These changes are required to enhance the API as described before.
---
=> [PAGOPA-996] feat: updated Authorizer enrolled EC's API

src/psql/nodo/liquibase/changelog/cfg/3.20.0/db.changelog-20230609153200_new_iban_tables.xml, src/psql/nodo/liquibase/changelog/cfg/3.21.0/db.changelog-20230616115000_add_column_duedate_to_iban.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.20.0.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/run.sh
- added due_date column to iban table (liquibase script)
- new business request
---
=> [PAGOPA-1013] added due_date column to iban table

src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
GPD open API fix. The "" has been added to the value of the url.server tag.
The change was made to allow code generation on the ACA project.
---
=> fix: Gpd openapi format

src/domains/apiconfig-app/04_apim_api_config.tf, src/domains/apiconfig-app/README.md, src/domains/gps-app/04_apim_gpd_core.tf, src/domains/gps-app/04_apim_gpd_for_pn_aca.tf, src/domains/gps-app/README.md, src/domains/gps-app/api_product/aca-integration/_base_policy.xml
=> feat: PAGOPA-1027 nuovo prodotto aca

src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
=> fix: Receipt domain dev secret

src/domains/receipts-secrets/.terraform.lock.hcl, src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
=> fix: Updated DEV secret refs

src/domains/receipts-secrets/.terraform.lock.hcl, src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
- Updating appinsight connecton string on dev secrets with correct values
- Update required in order to properly log receipt domain logs on appinsight
---
=> Fix receipt domain dev secret

src/domains/gps-app/api/payments-service/v1/rest/external/_openapi.json.tpl, src/domains/gps-common/02_security.tf
Fixing gpd payments app and common, adding cosmos configurations
This was reuiqred for the correct functionality of gpd payments
---
=> Pagopa 960 sviluppo migrazione dati storage to cosmos e applicazione in uat e prod

src/domains/gps-app/00_data.tf, src/domains/gps-app/99_locals.tf
Note: apply only in DEV is sufficient: UAT and PROD resources are not affected.
- `SPRING_DATASOURCE_USERNAME` update
- Fix postgresql server to target correct database server `pagopa-d-gpd-postgresql`
It is necessary to standardize the configuration of dev to that of other environments with regard to `SPRING_DATASOURCE_USERNAME` in order to facilitate management as a secret in Kubernetes.
---
=> chore: Update gpd-core settings [PAGOPA-1038] 

src/domains/apiconfig-common/02_security.tf, src/domains/apiconfig-common/03_storage_account, src/domains/apiconfig-common/03_storage_account.tf, src/domains/apiconfig-common/99_variables.tf, src/domains/apiconfig-common/README.md
Addition of table storage for the ica binary file management, with the connection string in the kv
This addition was needed for the temporary solution of the ica binary file problem
---
=> feat: creazione table storage per api cfg PAGOPA-1009

src/domains/afm-app/04_apim_afm_calculator.tf
=> fix: Afm api product

src/domains/apiconfig-app/00_data.tf, src/domains/apiconfig-app/99_variables.tf, src/domains/apiconfig-app/README.md, src/domains/apiconfig-app/api_config.tf
Adding env variable of table storage to api-cfg app
This change was required due to the addition of the table storage to api-cfg common, now adding new configuration to the app service
---
=> feat: adding env variable to api-cfg PAGOPA-1010

src/core/env/dev/terraform.tfvars, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
According to [PPT-LMI-disabled](https://pagopa.atlassian.net/wiki/spaces/PPA/pages/563642704/Configurazione+servizi+satelliti+nodo+onCloud+su+APIM+pagoPA#1.-PPT-LMI-disabled-return-404-Not-Found) doc , disable LMI on apim pagopa platform.
In order to use in order to use [apiconfig](https://pagopa.atlassian.net/wiki/spaces/ACN/overview?homepageId=546833155) esclusily
---
=> feat: Disable lmi on pagopa apim platform

src/psql/nodo/liquibase/changelog/cfg/3.21.0/db.changelog-20230628150500_upd_iban_master_table.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.21.0.xml, src/psql/nodo/liquibase/run.sh
=> feat: Add `description` iban master table

src/domains/receipts-common/03_cosmosdb.tf
- Updated cosmos definition to include receipts-message-errors in cosmos containers
---
=> [PRDP-56] feat: introducing receipt error container in cosmosdb.tf

src/domains/shared-app/05_authorizer_functions.tf, src/domains/shared-app/README.md
=> feat: Add slot staging autorizzatore

.devops/nodo-db-migration-pipelines.yml, src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json, src/psql/nodo/liquibase/changelog/online/3.10.0/db.changelog-20230607141600000_add_column_companyNameSecondary.xml, src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.10.0.xml, src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.18.0.xml, src/psql/nodo/liquibase/run.sh
added missing liquibase script for node
added apim-subscription-key for node
---
=> feat: Node db scripts and apim-subscription-key

src/domains/fdr-app/04_apim_fdr.tf, src/domains/fdr-app/api/fdr-service-internal/v1/_base_policy.xml.tpl, src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl, src/domains/fdr-app/api/fdr-service/v1/_openapi.json.tpl, src/domains/fdr-app/api_product/fdr-service-internal/_base_policy.xml
=> [FdR] update openapi Fase 3 

.gitignore, src/domains/nodo-app/00_alert.tf, src/domains/nodo-app/00_data.tf, src/domains/nodo-app/00_monitor.tf, src/domains/nodo-app/99_locals.tf, src/domains/nodo-app/README.md, src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
```
sh terraform.sh apply weu-prod \
-target=azurerm_monitor_scheduled_query_rules_alert.nodoapi-general-availability \
-target=azurerm_monitor_scheduled_query_rules_alert.nodoapi-general-responsetime
```
---
=> feat: Add nodo api alert responsetime + availability

src/core/README.md, src/core/security.tf, src/domains/apiconfig-app/00_alert_apiconfig_cache.tf, src/domains/apiconfig-app/00_alert_apiconfig_core.tf, src/domains/apiconfig-app/00_monitor.tf, src/domains/apiconfig-app/02_security.tf, src/domains/apiconfig-app/99_locals.tf, src/domains/apiconfig-app/README.md, src/domains/apiconfig-app/api_config.tf
- added JDBC connection problem to API-Config
- added Out-of-memory problem to API-Config-Cache
- moved DB-Check alarm to 00_alarm.tf
---
=> feat: [NOD-150] API-CFG Alarms

src/psql/nodo/liquibase/changelog/cfg/3.22.0/db.changelog-20230705163700_add_unique_to_id_dominio.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.22.0.xml, src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.22.0.xml, src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.22.0.xml, src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.22.0.xml, src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.22.0.xml
- added unique costraint to id_dominio column (ica_binary_file table)
---
=> [PAGOPA-1010] add unique to id_dominio: created liquibase script

src/domains/mock-app/04_apim_mock_4_receipt_pdf.tf, src/domains/mock-app/README.md, src/domains/mock-app/api/mock_4_receipt_pdf/v1/_base_policy.xml, src/domains/mock-app/api/mock_4_receipt_pdf/v1/_swagger.json.tpl, src/domains/mock-app/api_product/mock_4_receipt_pdf/_base_policy.xml
=> feat: Add mock-io appi 4 pdf-receipt

src/domains/mock-app/api/mock_4_receipt_pdf/v1/_base_policy.xml
- Updated mocks to cover multiple cases
---
=> feat: updated mocks for receipt pdf

src/domains/apiconfig-app/api/apiconfig_api/subkey/v1/_base_policy.xml.tpl, src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
Removed rate-limit check into GPD base policy for aca product.
Added content-type header into API-CONFIG base policy for aca product
The change was made to fix issues with pagopa-aca flow.
---
=> fix(configuration) GPD and API-CONFIG for ACA

src/domains/mock-app/.terraform.lock.hcl, src/domains/receipts-app/00_alert.tf, src/domains/receipts-app/04_apim_receipts.tf, src/domains/receipts-app/README.md, src/domains/receipts-app/api/receipt-service/v1/_base_policy.xml, src/domains/receipts-app/api/receipt-service/v1/_openapi.json.tpl, src/domains/receipts-app/api_product/_base_policy.xml, src/domains/receipts-app/api_product/receipt-service/_base_policy.xml
- Introducing receipt service apim in receipt-app
Required to expose new services in receipt domain
---
=> [PRDP-42] feat: add service apim in receipt-app

src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json, src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
- Updated receipt secrets with io subscription key
---
=> [PRDP-45] feat: Introducing io apim subkey secret

src/core/README.md, src/core/api/nodopagamenti_api/nodoPerPsp/v1/fdr_nodoinvia_flussorendicontazione_flow.xml, src/core/apim_nodo_services.tf, src/core/apim_nodo_services_auth.tf, src/core/apim_nodo_services_dev.tf, src/core/env/dev/terraform.tfvars, src/domains/fdr-app/00_data.tf, src/domains/fdr-app/04_apim_fdr.tf, src/domains/fdr-app/README.md
on `fdr-app`
```
sh terraform.sh apply weu-<ENV> \
-target=azurerm_api_management_api_operation_policy.fdr_policy_auth
```
---
=> fix: Add fdr monitoring on nodo-auth nodo_per_psp

src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
- Updated uat secrets for receipts domain in order to manage filtered fiscal codes env var
---
=> [PRDP-53] feat: Updated notifier secrets

src/domains/shared-app/00_apim_pdf_engine_alert.tf, src/domains/shared-app/README.md
- Introducing pdf-engine alerts
---
=> [PRDP-62] feat: add pdf-engine alerts

src/domains/afm-app/api/calculator-service/node/v1/_openapi.json.tpl, src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
This PR contains changes made on AFM-Marketplace's OpenAPI files in order to add a flag as a query parameter for the `pspsp/:idPsps/fees` API.
- Updated OpenAPI for AFM-Marketplace in standard and node products 
This change is required in order to expose the new optional flag that can be passed in the API
---
=> [PAGOPA-1023] fix: updated OpenAPI for AFM-Calculator

src/domains/selfcare-app/.terraform.lock.hcl, src/domains/selfcare-app/04_apim_token_exchange.tf
PagoPA backoffice on UAT env can read jwt exchange from prod
---
=> fix: Update openid-configuration for UAT env

src/domains/apiconfig-app/00_alert_apiconfig_cache.tf, src/domains/apiconfig-app/99_locals.tf
**TODO: apply in PROD**
- added alert on jdbc connection error
---
=> feat: [APIConfig Cache] Added alert on jdbc connection

src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
- added in kv key `apim-subscription-key`
---
=> feat: [NODO] Added key apim-subscription-key in prod

src/domains/gps-app/04_apim_external_payments.tf, src/domains/gps-app/04_apim_gpd.tf, src/domains/gps-app/04_apim_gpd_core.tf, src/domains/gps-app/04_apim_gpd_reporting.tf, src/domains/gps-app/README.md
- Create a new product `debt-positions-integration` composed of the following 3 APIs:
GPD-core: module.apim_api_debt_positions_api_v1
GPD-Payments: module.apim_api_gpd_payments_rest_external_api_v1
GPD-Reporting-Analysis: module.apim_api_gpd_reporting_analysis_api
- Need to manage a single subscription key for the 3 APIs of the same service Debt Positions.
---
=> feat: create GPD integration product [PAGOPA-1057]

src/domains/receipts-app/api/receipt-service/v1/_base_policy.xml
=> fix: Api backend receipt service

src/domains/nodo-app/env/weu-dev/terraform.tfvars, src/domains/nodo-app/env/weu-prod/terraform.tfvars, src/domains/nodo-app/env/weu-uat/terraform.tfvars
=> feat: Add nexi proxy internet

src/core/node_forwarder.tf, src/domains/apiconfig-app/00_alert_apiconfig_core.tf, src/domains/apiconfig-app/README.md, src/domains/nodo-app/00_alert.tf, src/domains/nodo-app/04_apim_nodo_technical_support.tf, src/domains/nodo-app/README.md
=> fix: Alert config nodo apicfg forwarder

src/domains/ecommerce-common/03_cosmosdb.tf, src/domains/ecommerce-common/03_redis.tf, src/domains/ecommerce-common/03_storage.tf, src/domains/ecommerce-common/README.md
=> feat: update ecommerce alerts

src/core/env/prod/terraform.tfvars
=> feat: enable ecommerce sendpaymentresult

src/core/node_forwarder.tf, src/domains/selfcare-app/api/pagopa-api-config/v1/_openapi.json.tpl
update open api
expose new api
---
=> update open api

src/domains/mock-app/api/mock_4_receipt_pdf/v1/_base_policy.xml, src/domains/receipts-app/api/receipt-service/v1/_base_policy.xml, src/domains/receipts-app/api/receipt-service/v1/_openapi.json.tpl
- Updated receipts APIM and Mock
---
=> Chore: updated receipts APIM

src/domains/receipts-secrets/02_security.tf, src/domains/receipts-secrets/README.md
=> feat: add receipts secrets

src/domains/fdr-app/05_fdr_re_fn.tf
=> feat: [NOD-361] Added autoscaling to FdR-RE

src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
=> fix: [NOD-387] Autoscaling improvements

src/domains/gps-common/03_cosmosdb.tf
Update of the throughput of the gpd payments cosmos table in the three environments
This update was necessary for the correct functionality of gpd-payments under stress condition
---
=> upd: update gpd pmnts cosmos table tp PAGOPA-1083

.devops/wallet-deploy-pipelines.yml, src/domains/wallet-common/03_cosmosdb.tf, src/domains/wallet-common/env/weu-prod/backend.ini, src/domains/wallet-common/env/weu-prod/backend.tfvars, src/domains/wallet-common/env/weu-prod/terraform.tfvars
- add wallet-common prod without cosmosdb
The goal of this PR is to add prod conf for wallet-common in order to create payment-wallet DNS in https://github.com/pagopa/pagopa-infra/pull/1019
---
=> Chk 1744 env prod

src/domains/ecommerce-common/03_redis.tf
=> fix: redis alert threshold

src/domains/nodo-app/04_apim_nodo_technical_support.tf, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/nodo-app/api/technical-support-service/v1/_openapi.json.tpl
=> fix: [NOD-357] Update openapi Nodo TS

src/domains/wallet-app/api/wallet-service/v1/_openapi.json.tpl
=> fix: add missing type in wallet

src/domains/gps-app/04_apim_gpd_core.tf, src/domains/gps-app/04_apim_gpd_for_pn_aca.tf, src/domains/gps-app/99_locals.tf, src/domains/gps-common/02_security.tf, src/domains/gps-common/99_locals.tf, src/domains/gps-common/README.md, src/domains/gps-common/env/weu-dev/terraform.tfvars, src/domains/shared-app/04_apim_statuspage.tf
The following changes add the `datasource url` as secret, this will be stored as an environment secret in the gpd-core [repository](https://github.com/pagopa/pagopa-debt-position) and will be used in the database migration pipelines.
---
=> ci: Add secret for GPD-Core GHA pipeline

src/domains/wallet-app/api/wallet-service/v1/_openapi.json.tpl
=> fix: delete double auth

src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml, src/domains/gps-app/api/payments-service/v1/rest/external/_base_policy.xml, src/domains/shared-app/05_authorizer_functions.tf, src/domains/shared-app/api/authorizer/authorizer-check.xml
This PR contains several changes related to platform Authorizer, made in order to resolve some bugs and activate pending inclusions on GPD APIs.
So, it was added the platform Authorization's use on GPD-core and GPD-Payments service that were in a temporary pending state.
Also, some bug were resolved. In particular, a bug on wildcard defined in document authorization is resolved. This was casued by a wrong escaping of entity separator, needed with the last optimization. Also, a persisting bug on Azure function is finally resolved: this caused a _drop_ of the same function when a Terraform apply was made on the function app.
The updates on `gps-app` folder were applied with the following command:  
```
sh terraform.sh apply ENV \
--target=module.apim_api_debt_positions_api_v1 \ …
```
=> [PAGOPA-1123] Fixes and activations on Authorizer

src/core/monitor.tf
=> feat: Add web availability test forwarder[.env].platform.pagopa.it

src/domains/shared-common/02_security.tf, src/domains/shared-common/README.md
- Introducing secret placeholder for elk secret (to be added manually)
---
=> [PRDP-64] feat_ add elk secret placeholder in shared

src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl, src/domains/fdr-app/api/fdr-service/v1/_openapi.json.tpl
=> feat: Update openapi

src/domains/shared-common/02_security.tf
- Changed secret to use opentelemetry agent
---
=> [PRDP-95] Updated 02_security.tf

src/domains/ecommerce-app/api/ecommerce-payment-requests-service/v1/_openapi.json.tpl
=> fix(openapi-ecommerce): CHK-1788 increase paName maxLength to 140

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
=> fix: increase pa maxLength

src/domains/aca-common/02_security.tf, src/domains/aca-common/README.md
* add OpenTelemetry header secret to ACA KV
This secret is needed to correctly configure OpenTelemetry agents in ACA services (e.g. pagopa/pagopa-aca-service#50)
---
=> feat(aca): add OpenTelemetry header secret to ACA KV

src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl, src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
=> openapi update

src/core/api/nodopagamenti_api/nodoServices/web-bo-history-on-prem/v1/_base_policy.xml, src/core/api/nodopagamenti_api/nodoServices/web-bo-history/v1/_base_policy.xml, src/core/api/nodopagamenti_api/nodoServices/web-bo-history/v1/_base_policy_dev.xml, src/core/api/nodopagamenti_api/nodoServices/web-bo-on-prem/v1/_base_policy.xml, src/core/api/nodopagamenti_api/nodoServices/web-bo/v1/_base_policy.xml, src/core/api/nodopagamenti_api/nodoServices/web-bo/v1/_base_policy_dev.xml, src/core/api/payment_manager_api/admin-panel/_base_policy.xml.tpl, src/core/apim_nodo_3p_services.tf, src/core/apim_nodo_3p_services_dev.tf, src/core/apim_payment_manager.tf
=> feat: Add softlab ip to apim

src/elk-monitoring/env/weu-prod/terraform.tfvars, src/elk-monitoring/env/weu-uat/terraform.tfvars
=> feat: Add 50GB elk PV warm-cold uat-prod

src/domains/ecommerce-common/02_security.tf
=> feat(sec): CHK-1812 add secret pm for helpdesk

src/domains/nodo-app/00_network.tf, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/nodo-app/05_fn_ndp_re_to_tablestorage.tf, src/domains/nodo-app/99_variables.tf, src/domains/nodo-app/env/weu-dev/terraform.tfvars, src/domains/nodo-app/env/weu-prod/terraform.tfvars, src/domains/nodo-app/env/weu-uat/terraform.tfvars
=> feat: [NOD-410] Nodo RE Table Storage Fn

src/domains/ecommerce-common/02_security.tf, src/domains/ecommerce-common/README.md
Added api-key for execute test for DEV and UAT env after deploy pipeline
Added api key for execute tests
---
=> feat(api-key): added new api key for execute test after deploy for dev and uat env

src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/shared-app/00_alert_taxonomy.tf, src/domains/shared-app/00_monitor.tf, src/domains/shared-app/99_locals.tf
=> [NOD-415] Taxonomy alarms

src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json, src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
=> feat: Add secret for prf test ReceiptGeneratorService

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
- add new `get payment-methods/:id/sessions/:idsession` in `ecommerce-checkout` and `payment-methods` API;
The goal of this PR is to add the following new API:
```yml
/payment-methods/{id}/sessions/{id_session}:
get:
tags:
- payment-methods
operationId: getSessionPaymentMethod
summary: Get session payment method by ID
description: API for retrieve payment method information for a given payment method ID
parameters:
- name: id
in: path
description: Payment Method ID
required: true
schema:
type: string
- name: id_session
in: path
description: Session payment method ID related to NPG
required: true
schema:
type: string    
responses:
'200':
description: Session payment method successfully retrieved 
content:
application/json:
schema:
$ref: '#/components/schemas/SessionPaymentMethodResponse' …
```
=> feat: CHK-1821 add new get session payment method

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
Fixed required value into openapi for retrieve card data api
---
=> fix(openapi) fixed required value into openapi

src/core/README.md, src/core/security.tf
=> feat: Add `github-token-read-packages-bot` secret

src/core/README.md, src/core/dns_selfcare_backoffice_plaftorm.tf
depend on https://github.com/pagopa/pagopa-aws-infra/pull/17
---
=> feat: Account SES to sent mail bo platform pagoPA

src/core/dns_selfcare_backoffice_plaftorm.tf
=> fix: Dkim aws ses backoffice-platform-pagopa-it

src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
=> fix: Secret-int-test-receipts

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
Fixed brand openapi from enum to simple string
---
=> fix(openapi) fixed brand

src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json, src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
=> feat: Add webhook receipt secrets

src/domains/ecommerce-common/02_security.tf, src/domains/ecommerce-common/README.md
Add eCommerce secret used to hold psp - api keys association for NPG authorization request 
Add eCommerce secret used to hold psp - api keys association for NPG authorization request
---
=> feat(secret): [CHK-1823] add secrets for NPG cards method keys

src/domains/fdr-app/00_network.tf, src/domains/fdr-app/02_security.tf, src/domains/fdr-app/04_apim_fdr_json_to_xml.tf, src/domains/fdr-app/04_apim_fdr_xml_to_json.tf, src/domains/fdr-app/05_fdr_json_to_xml_fn.tf, src/domains/fdr-app/99_variables.tf, src/domains/fdr-app/api/fdr-json-to-xml/v1/_base_policy.xml.tpl, src/domains/fdr-app/api/fdr-json-to-xml/v1/_openapi.json.tpl, src/domains/fdr-app/api_product/fdr-json-to-xml/_base_policy.xml, src/domains/fdr-app/env/weu-dev/terraform.tfvars, src/domains/fdr-app/env/weu-uat/terraform.tfvars, src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json, src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
=> feat: fn json to xml

src/domains/fdr-app/04_apim_fdr_json_to_xml.tf, src/domains/fdr-app/04_apim_fdr_xml_to_json.tf, src/domains/fdr-app/99_locals.tf
=> feat: Fix apim json to xml

src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl
* add endpoint to payment-methods to update session data
---
=> [CHK-1839] feat(ecommerce): add endpoint to payment-methods to update session data

src/domains/ecommerce-app/api/ecommerce-transaction-auth-requests-service/v1/_openapi.json.tpl
Add update authorization details for eCommerce-NPG integration 
Those details are used to map NPG notification request to eCommerce PATCH request
---
=> feat(ecommerce-npg): [CHK-1840] auth request npg details

src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
👉🏻 Added new resource `get_card_data_information` for execute jwt check for the api:
- GET /payment-methods/{id}/sessions/{sessionId}
👉🏻 Added new header into request **x-transaction-id-from-client** validate jwt
---
=> feat(jwt) added check jwt for api to retrieve card data

src/domains/fdr-common/env/weu-prod/terraform.tfvars, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- fix mongo configuration in prod
---
=> fix: [NOD-422] Mongo FdR

src/domains/shared-app/04_apim_statuspage.tf
=> feat: added Platform's Authorizer config on Status page

src/domains/ecommerce-app/.terraform.lock.hcl, src/domains/ecommerce-app/04_apim_ecommerce_npg_notification.tf, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/npg-notification/_base_policy.xml.tpl, src/domains/ecommerce-app/api/npg-notification/_npg_notifications_policy.xml.tpl, src/domains/ecommerce-app/api/npg-notification/_openapi.json.tpl
Add openapi and policy to handle NPG payment notification requests.
Those POST requests are handled by a specific APIM policy that perform actions in order to map it to eCommerce transaction PATCH requests
Those modifications are needed in order to correctly handle NPG payment notifications requests and map those request to eCommerce transaction PATCH ones
---
=> feat(ecommerce-npg): [CHK-1837] NPG transaction status notification policy

src/domains/bizevents-common/02_security.tf
Added elastic secret on Infra
Secret needed for the correct deployment of biz event service
---
=> feat: add biz missing elastic secret PAGOPA-1196

src/domains/shared-app/04_apim_statuspage.tf
- Add new receipt generator function to status page apim
Show new receipt generator function in status page
---
=> [PRDP-127] feat: Add receipt generator to status page apim

src/domains/ecommerce-app/04_apim_ecommerce_npg_notification.tf
Disable NPG post APIM policy for eCommerce PROD env
Disable NPG post APIM policy for eCommerce PROD env
---
=> Chk 1837 npg notification policy conf

src/core/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml, src/core/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml, src/core/apim_nodo_services.tf, src/core/apim_nodo_services_auth.tf, src/domains/nodo-app/04_apim_nodo_services_ndp.tf, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/nodo-app/05_fn_ndp_re_to_tablestorage.tf, src/domains/nodo-app/README.md, src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml, src/domains/nodo-app/api/nodopagamenti_api/nodeForPsp/v2/activate_nm3.xml
verificatore now calls `AKS cluster` instead of `apiconfig app service`
---
=> HOTFIX🔥 verificatore: new url to apiconfig

src/domains/ecommerce-common/03_redis.tf
Fix Redis alert `scopes` parameter value with redis resource id
Fix Redis alert `scopes` parameter value with redis resource id
---
=> fix(alert): change id on alert resource id

src/domains/ecommerce-common/03_storage.tf
Explicitate metric for queue alert
Explicitate metric for queue alert
---
=> fix(queue-alert): explicitate metric argument

src/domains/bizevents-common/02_security.tf, src/domains/bizevents-common/README.md
=> feat: Add redis secret to biz

src/domains/afm-app/00_alert_afm_calculator.tf, src/domains/afm-app/00_monitor.tf, src/domains/afm-app/99_locals.tf, src/domains/afm-app/README.md
Added Opsgenie Alerts for `AFM-Calculator` for `getFees`
Monitoring
---
=> [PAGOPA-1188] Alert calculator opsgenie

src/domains/apiconfig-app/00_alert_apiconfig_cache.tf, src/domains/apiconfig-app/00_monitor.tf
added alerts for `apiconfig-cache` in `UAT`
---
=> feat: ApiCfg alert in uat

src/core/monitor.tf
=> fix: Remove useless webtest forwarder

src/domains/receipts-secrets/02_security.tf, src/domains/receipts-secrets/README.md
Added receipts storage account primary key to receipts secrets
[Issue PRDP-130](https://pagopa.atlassian.net/jira/software/c/projects/PRDP/boards/440?modal=detail&selectedIssue=PRDP-130)
---
=> [PRDP-130] feat: Add receipts storage account primary key

src/domains/nodo-app/00_alert.tf, src/domains/nodo-app/README.md
Add new nodo alerts targeted for each `primitiva` and sub-service.
---
=> feat: Add new nodo alerts [PAGOPA-1207]

src/domains/shared-app/04_apim_statuspage.tf
=> fix: StatusPage: new Apiconfig path

.devops/qi-code-review-pipelines.yml, .devops/qi-deploy-pipelines.yml, .github/workflows/static_analysis.yml, .utils/terraform_run_all.sh
Depends on https://github.com/pagopa/pagopa-azure-devops/pull/254
Add IAC pipelines for qi commons and app domains
Add IAC pipelines for qi commons and app domains
---
=> chore(iac): add static analysis and iac pipelines

src/domains/receipts-app/00_alert.tf, src/domains/receipts-app/README.md
- registered an alert on BizEventToReceiptProcessor function
[Issue PRDP-129](https://pagopa.atlassian.net/browse/PRDP-129?atlOrigin=eyJpIjoiZmFkYmVjOTFlNWFkNDk4MWI2YjAzZjM4NzRjNWE3ZGUiLCJwIjoiaiJ9)
Throw an alert when the function BizEventToReceiptProcessor receive an event related to a cart and discard it
---
=> [PRDP-129] feat: Add alert on cart events

src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json, src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
The changes were applied using the command:  
```
sh terraform.sh apply weu-dev \
--target=module.nodo_re_to_datastore_function \
--target=module.nodo_re_to_datastore_function_slot_staging
```
---
=> [NOD-472] fix: updated container registry ref

src/domains/gps-app/04_apim_gpd_payments.tf
=> [NOD-450] Restored subscription_required to GPD Payments

src/domains/gps-app/api/payments-service/v1/rest/_base_policy.xml
=> [PAGOPA-1235] fix: Update GPD-Payments external policy

src/psql/nodo/liquibase/changelog/cfg/3.19.0/db.changelog-20230517113500_remove_LMI_columns.xml, src/psql/nodo/liquibase/changelog/cfg/3.20.0/db.changelog-20230609153200_new_iban_tables.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.22.0.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.23.0.xml, src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.23.0.xml, src/psql/nodo/liquibase/changelog/online/3.23.0/db.changelog-20230919000000_paymentNote.xml, src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.23.0.xml, src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.23.0.xml, src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.23.0.xml, src/psql/nodo/liquibase/run.sh
=> Allineamento script nodo

src/domains/mock-app/.terraform.lock.hcl, src/domains/mock-app/02_namespace.tf, src/domains/mock-app/03_serviceaccounts_azure_devops.tf, src/domains/mock-app/04_apim_mock_ec.tf, src/domains/mock-app/04_apim_mock_ec_psp_pm_nexi.tf, src/domains/mock-app/04_apim_mocker.tf, src/domains/mock-app/04_apim_product_mocker.tf, src/domains/mock-app/06_aks_middleware_tools.tf, src/domains/mock-app/README.md, src/domains/mock-app/api/mock_nexi/psp/v1/mock.openapi.json.tpl, src/domains/mock-app/api/mockec_api/v1/_base_policy_rewrite.xml, src/domains/mock-app/api/mockec_api/v1/_swagger.json.tpl
=> fix: mock ec

src/domains/apiconfig-app/00_alert_apiconfig_core.tf
- alert JDBC Connection in UAT
---
=> Alert Apiconfig-Core in UAT

src/domains/selfcare-app/api/pagopa-selfcare-ms-backoffice/jwt/v1/_openapi.json.tpl
=> new swagger

src/core/apim_nodo_services_dev.tf, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
=> fix: Nodo monitoring dev Nexi

src/domains/checkout-app/README.md, src/domains/ecommerce-app/README.md, src/domains/ecommerce-common/02_security.tf, src/domains/ecommerce-common/README.md
=> feat: add new nodo api key dedicated to ecommerce

src/domains/observability/01_observability.tf, src/domains/observability/04_datafactory_dataset.tf, src/domains/observability/04_datafactory_pipeline.tf, src/domains/observability/README.md, src/domains/observability/datafactory/pipelines/KPI_TPNP_Recupero.json
=> feat: PQI-47 creazione pipeline data factory

src/domains/receipts-app/env/weu-prod/backend.ini, src/domains/receipts-app/env/weu-prod/backend.tfvars, src/domains/receipts-app/env/weu-prod/terraform.tfvars, src/domains/receipts-common/env/weu-prod/backend.ini, src/domains/receipts-common/env/weu-prod/backend.tfvars, src/domains/receipts-common/env/weu-prod/terraform.tfvars, src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
=> feat: Apply prod `receipts` namespace and resources

src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/shared-common/env/weu-prod/terraform.tfvars
=> [NOD-455] taxonomy

src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/shared-app/04_apim_technical_support.tf
=> feat: Technical support group

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
Add recaptchaResponse for create session api
Add recaptchaResponse for create session api
---
=> fix(openapi): add create session recaptchaResponse

src/domains/apiconfig-common/02_security.tf, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
=> feat: API config secret

src/domains/shared-app/env/weu-prod/terraform.tfvars
=> fix: Prod PDF engine

src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
Add Nexi and Amex psp for NPG gateway for DEV environment
Add Nexi and Amex psp for NPG gateway
---
=> feat(auth-request-conf): add nexi and amex psp for NPG

src/domains/shared-app/01_app_service_pdf_engine.tf, src/domains/shared-app/02_keyvault.tf, src/domains/shared-app/04_apim_pdf_engine.tf, src/domains/shared-app/05_taxonomy_fn.tf, src/domains/shared-app/99_locals.tf, src/domains/shared-app/README.md, src/domains/shared-app/api/pdf-engine/v1/_base_policy.xml
- Introducing pdf-engine java app service plan on shared domain
```
sh terraform.sh apply weu-<ENV> \
-target=module.shared_pdf_engine_app_service_java \
-target=module.shared_pdf_engine_java_slot_staging \
-target=azurerm_monitor_autoscale_setting.autoscale_app_service_shared_pdf_engine_java_autoscale \
-target=module.apim_pdf_engine_product \
-target=azurerm_api_management_api_version_set.api_pdf_engine_api \
-target=module.apim_api_pdf_engine_api_v1 \
-target=azurerm_api_management_api_version_set.api_pdf_engine_node_api \
-target=module.apim_api_pdf_engine_node_api_v1
```
---
=> [PRDP-158] feat: add App Service plan for java pdf-engine

src/domains/observability/.terraform.lock.hcl, src/domains/observability/04_datafactory_pipeline.tf, src/domains/observability/datafactory/datasets/KPI_TNSPO.json, src/domains/observability/datafactory/datasets/KPI_TPSPO_DASPO.json, src/domains/observability/datafactory/datasets/type_properties/KPI_TNSPO.json, src/domains/observability/datafactory/datasets/type_properties/KPI_TPSPO_DASPO.json, src/domains/observability/datafactory/pipelines/KPI_TNSPO.json, src/domains/observability/datafactory/pipelines/KPI_TPSPO_DASPO.json
=> feat: Add 3 pipeline for QI/KPI

src/domains/shared-app/04_apim_statuspage.tf, src/domains/shared-app/README.md
=> chore: Add pdfengine status page

src/domains/receipts-app/00_alert.tf
=> chore: Format-fancy-alert-receipts

src/domains/gps-app/README.md, src/domains/gps-app/api/gpd_api/debt-position-services/v1/_base_policy.xml
- Policy update to extract segregation codes and send them to the `GPD-Core` micro-service as a query param.
PS: For now doesn't returns 403 if the caller is authorized but has an **empty list** of segregation codes associated with the CI broker. This feature may be included in the near future when consolidation of the solution is completed.
- Manage cases where CIs are intermediated by multiple brokers
---
=> feat: Update policy in GPD-Core API for organization [PAGOPA-1139] 

src/domains/gps-app/04_apim_gpd_for_pn_aca.tf, src/domains/gps-app/api/pn-integration/_base_policy.xml, src/domains/gps-app/api/pn-integration/_openapi.json.tpl
- Updating OpenAPI;
- Updating name and description to be consistent with other GPD products.
- Bug fix: `https://` present twice in the backend service URL
---
=> chore: Update GPD for PN API [PAGOPA-1267]

src/domains/gps-common/env/weu-prod/terraform.tfvars, src/domains/shared-common/env/weu-prod/terraform.tfvars
Added replica region for 2 cosmosdb account
partial fulfillment of DIS-41
---
=> feat: Dis 41

src/domains/observability/04_datafactory_pipeline.tf
- [] Update configuration to existing resources
---
=> fix trigger for TNSPO kpi

src/domains/receipts-common/03_cosmosdb.tf
=> fix: UAT receipt alarm

src/domains/shared-app/99_locals.tf
=> fix: Config PDF generator

src/domains/fdr-common/03_cosmos_mongodb_fdr.tf, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
=> feat: [NOD-537] Add index FdR

src/core/README.md, src/core/apim_nodo_services_auth.tf, src/core/azure_devops_agent.tf, src/core/env/prod/terraform.tfvars, src/core/variables.tf
=> feat: DIS-47 Added zone replication for azdo agents

src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/shared-app/api/taxonomy/v1/_openapi.json.tpl
=> fix: [NOD-554] Taxonomy openapi

src/domains/receipts-app/00_alert.tf, src/domains/receipts-app/README.md
- Added alert for ReceiptGenerator in case of missing property in biz-event
- Added alert for ReceiptGenerator in case of PDF Engine invocation KO
- Added alert for ReceiptGenerator in case of error on saving PDF in Blob Storage
Added alert
---
=> [PRDP-176] feat: Added alert for receipt generator

src/domains/gps-common/02_security.tf
- added subkey for node invocation
- required for GPD to invoke the node's checkPosition API
---
=> feat: [PAGOPA-1272] node subkey

src/domains/shared-app/99_locals.tf, src/psql/nodo/liquibase/changelog/cfg/3.23.0/db.changelog-20230705163700_update_database_object.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.23.0.xml
- modified some fields of the iban_validi_per_pa view
- resolve an error that emerged during integration tests with nexi
---
=> [PAGOPA-1270] update iban view: update fields on iban_validi_per_pa view

src/domains/shared-app/01_app_service_pdf_engine.tf, src/domains/shared-app/99_variables.tf, src/domains/shared-app/README.md, src/domains/shared-app/env/weu-prod/terraform.tfvars, src/domains/shared-app/env/weu-uat/terraform.tfvars
=> fix: PDF engine autoscaling

src/domains/shared-app/01_app_service_pdf_engine.tf
- Introducing scaling rules based on CPU for the pdf-engine app services
---
=> [PRDP-181] feat: add cpu scaling rules on app service pdf engine

src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf
The goal of this PR is to revert the api key on the ecommerce product to true
---
=> fix: api key for product ecommerce-checkout

src/domains/ecommerce-common/99_variables.tf
=> fix: delete duplicate key in mongo ecommerce param

src/domains/wallet-app/api/payment-wallet/v1/_openapi.json.tpl
=> feat: disable patch wallet for io

src/domains/fdr-app/api/fdr-service/org/v1/_base_policy.xml.tpl, src/domains/fdr-app/api/fdr-service/psp/v1/_base_policy.xml.tpl
This PR contains the addition of the integration of FdR-Fase3 APIs with Authorizer system.
- Integrated FdR-Fase3 APIs with Authorizer
---
=> [NOD-551] feat: added integration with Authorizer system

src/domains/fdr-app/api/fdr-service/org/v1/_openapi.json.tpl, src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
=> fix: [NOD-561] FdR3 OpenAPI

src/elk-monitoring/env/weu-prod/terraform.tfvars
=> feat: Increase elk storage

src/domains/ecommerce-app/04_apim_ecommerce_io.tf, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/ecommerce-io/v1/_create_new_session.xml.tpl
Add policy to create session token from wallet token using PM start session call
This policy implements create session token logic using PM start session api call
---
=> feat(create-session): [CHK-2071] add policy to create session `POST /sessions`

src/domains/ecommerce-app/api/ecommerce-io/v1/_openapi.json.tpl
=> feat: CHK-2003 update docs API ecommerce for IO
