pagopa/pagopa-infra

- src/domains/qi-secrets/secret/weu-dev/noedit_secret_enc.json
Modifying dev secret value for JSM
In order to avoid opening real tickets when developing
---
> Changing secret value dev QI

- src/domains/aca-common/02_security.tf
Added count for aca-api-key for exclude prod env 
---
> fix: added count for aca-api-key

- .devops/aca-deploy-pipelines.yml
> fix: delete aks refs for common aca

- src/psql/nodo/liquibase/changelog/cfg/3.23.0/db.changelog-20230705163700_update_database_object.xml
- added Unique Constraint for fk_iban-fk_pa columns in iban_master tables 
- business request
---
> [PAGOPA-1332] unique pa iban relationship

- src/domains/receipts-secrets/.terraform.lock.hcl
- src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
- src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
- src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
- Introducing dev PDV Tokenizer api key
---
> [PRDP-185] feat: introducing dev tokenizer secret

- src/domains/gps-app/04_apim_gpd_for_pn_aca.tf
- src/domains/gps-app/api/pn-integration/_openapi.json.tpl
path update in `GPD PN Integration` API 
PN integration API was updated to exclude it from deny-paths
---
> chore: Update path in GPD PN Integration API [PAGOPA-1338]

- src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
Add unicredit as psp configured for NPG for DEV environment
Add unicredit as psp configured for NPG for DEV environment
---
> chore(conf): add unicredit as NPG psp

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/cfg/0/uat/data/8-changelog-CANALE_TIPO_VERSAMENTO.xml
> fix: liquibase uat nodo

- src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
- src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
> chore: PRDP-194 pdv keys

- src/domains/wallet-app/api/payment-wallet/v1/_post_wallets_policy.xml.tpl
Edit post wallet policy to update sessionToken append to the redirect url
---
> [CHK-2098] fix policy sessionToken url append

- src/domains/afm-app/00_alert_afm_calculator.tf
- src/domains/gps-app/00_alert_gpd_core.tf
- src/domains/gps-app/00_alert_gpd_payments.tf
- src/domains/nodo-app/00_alert.tf
- src/domains/shared-app/00_alert_authorizer.tf
Remove opsgenie action group from response time alert
Remove opsgenie action group from response-time alert for the following domains:
- gps/gps
- nodo
- afm
- shared (authorizer)
```
sh terraform.sh apply weu-prod \
-target=azurerm_monitor_scheduled_query_rules_alert.opex_pagopa-platform-authorizer-responsetime
sh terraform.sh apply weu-prod \
-target=azurerm_monitor_scheduled_query_rules_alert.alert-nodo-responsetime \
-target=azurerm_monitor_scheduled_query_rules_alert.alert-nodo-auth-responsetime
sh terraform.sh apply weu-prod \
-target=azurerm_monitor_scheduled_query_rules_alert.opex_pagopa-gpd-core-internal-responsetime-upd \
-target=azurerm_monitor_scheduled_query_rules_alert.opex_pagopa-gpd-core-external-responsetime-upd
sh terraform.sh apply weu-prod \ …
```
> chore: Disable opsgenie action group from response-time alert [PAGOPA-1339] 

- src/domains/wallet-app/04_apim_payment_wallet.tf
- src/domains/wallet-app/99_variables.tf
- src/domains/wallet-app/README.md
- src/domains/wallet-app/api/webview-payment-wallet/v1/_base_policy.xml.tpl
- src/domains/wallet-app/env/weu-dev/terraform.tfvars
- src/domains/wallet-app/env/weu-uat/terraform.tfvars
> feat: add cors policy

- src/domains/wallet-app/api/payment-wallet/v1/_post_wallets_policy.xml.tpl
- src/domains/wallet-app/api/webview-payment-wallet/v1/_base_policy.xml.tpl
1. Disable jwt token on webview apis
2. Set fiscal code tokenized by pdv as user id header param
---
> Chk 2006 disable jwt token

- src/domains/wallet-app/env/weu-uat/terraform.tfvars
> feat: enable pm for wallet uat

- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/README.md
- src/domains/wallet-common/02_security.tf
- src/domains/wallet-common/README.md
> feat: add wallet token for testing test

- src/domains/wallet-app/api/webview-payment-wallet/v1/_openapi.json.tpl
> fix: modified CARD to CARDS

- src/domains/shared-common/env/weu-prod/terraform.tfvars
> feat: Added region replica for iuv generator

- src/domains/fdr-common/.terraform.lock.hcl
- src/domains/fdr-common/00_data.tf
- src/domains/fdr-common/01_network.tf
- src/domains/fdr-common/03_postgresql.tf
- src/domains/fdr-common/03_postgresql_replica.tf
- src/domains/fdr-common/99_locals.tf
- src/domains/fdr-common/99_main.tf
- src/domains/fdr-common/99_variables.tf
- src/domains/fdr-common/README.md
- src/domains/fdr-common/env/weu-dev/terraform.tfvars
- src/domains/fdr-common/env/weu-prod/terraform.tfvars
- src/domains/fdr-common/env/weu-uat/terraform.tfvars
- src/next-core/00_network.tf
- src/next-core/01_dns_forwarder.tf
- src/next-core/01_network.tf
- src/next-core/99_variables.tf
- src/next-core/README.md
- src/next-core/env/dev/backend.ini
- src/next-core/env/dev/backend.tfvars
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
- new vnet in northeurope
- vnet peering
- db dedicated private dns zone
- dns zone link to core vnet
- postgres replica subnet
- postgres replica instance
- postgres main dns cname record
---
> feat: Added fdr replica - DIS-38

- src/domains/wallet-app/api/payment-wallet/v1/_openapi.json.tpl
> fix: get wallet for codegen

- src/domains/receipts-app/.terraform.lock.hcl
- src/domains/receipts-app/00_alert.tf
- src/domains/receipts-app/README.md
- Introducing error alerts for services in the receipt domain, regarding the errors in the usage of the PDV Tokenizer Client
---
> [PRDP-196] feat: introducing tokenizer client error alerts

- src/domains/receipts-app/04_apim_receipts.tf
- src/domains/receipts-app/README.md
- src/domains/receipts-app/api/receipt-datastore/v1/_base_policy.xml
- src/domains/receipts-app/api/receipt-datastore/v1/_openapi.json.tpl
- src/domains/receipts-app/api_product/receipt-datastore/_base_policy.xml
-Introduced receipt-datastore api config
---
> feat: introducing APIM config for receipts datastore

- src/domains/observability/04_datafactory_linkedservice.tf
- src/domains/observability/README.md
> chore: Linked service df vs cosmos

- src/domains/receipts-common/03_cosmosdb.tf
> chore: Upd receitps cosmos

- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/domains/nodo-app/00_network.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-app/05_fn_ndp_re_to_tablestorage.tf
- src/domains/nodo-app/99_variables.tf
- src/domains/nodo-common/01_network.tf
- src/domains/nodo-common/03_cosmosdb_nodo_re.tf
- src/domains/nodo-common/03_storage_account_nodo_re.tf
- src/domains/nodo-common/99_variables.tf
> chore: [NOD-587] Disable Nodo RE

- src/domains/fdr-common/03_postgresql.tf
- src/domains/fdr-common/99_variables.tf
- src/domains/fdr-common/README.md
- src/domains/fdr-common/env/weu-dev/terraform.tfvars
- src/domains/fdr-common/env/weu-prod/terraform.tfvars
- src/domains/fdr-common/env/weu-uat/terraform.tfvars
- src/next-core/01_network.tf
- src/next-core/99_variables.tf
- src/next-core/README.md
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Added postgres dns registration in uat env

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/cfg-partner/3.24.0/db.changelog-20231115000000.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.24.0.xml
- added schema `cfg` for NDP partner
---
> feat: [NOD-577] Liquibase schema CFG for NDP 

- src/domains/nodo-app/00_alert.tf
- src/domains/nodo-app/00_alert_faultcode.tf
- src/domains/nodo-app/00_monitor.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-app/README.md
- Update the range in which the threshold is 80;
- Update on cases where fault-code almost certainly isn't related to pagoPA fault;
The purpose is to reduce false positives related to this alert.
---
> chore(nodo-alert): Update fault-code alert

- src/next-aks/.terraform.lock.hcl
- src/next-aks/00_aks.tf
- src/next-aks/00_network.tf
- src/next-aks/01_velero.tf
- src/next-aks/99_locals.tf
- src/next-aks/99_main.tf
- src/next-aks/99_variables.tf
- src/next-aks/README.md
- src/next-aks/env/weu-dev/backend.ini
- src/next-aks/env/weu-dev/backend.tfvars
- src/next-aks/env/weu-dev/terraform.tfvars
- src/next-aks/env/weu-prod/backend.ini
- src/next-aks/env/weu-prod/backend.tfvars
- src/next-aks/env/weu-prod/terraform.tfvars
- src/next-aks/env/weu-uat/backend.ini
- src/next-aks/env/weu-uat/backend.tfvars
- src/next-aks/env/weu-uat/terraform.tfvars
- src/next-aks/scripts/k8setup.md
- src/next-aks/scripts/k8setup.sh
- src/next-aks/terraform.sh
> feat: Added velero isntallation and scheduling

- src/domains/ecommerce-app/api/ecommerce-mock/nodoPerPM/v1/_base_policy.xml.tpl
Add close payment response mock
Add close payment response mock
---
> Chk 2120 ecommerce closepayment mock

- src/next-aks/01_velero.tf
- src/next-aks/99_variables.tf
- src/next-aks/env/weu-prod/terraform.tfvars
> feat: Added velero sa backup

- src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_base_policy.xml.tpl
> fix: check user

- src/domains/ecommerce-app/api/ecommerce-io/v1/_calculate_fees_policy.xml.tpl
- src/domains/wallet-app/04_apim_payment_wallet.tf
Update field mapping from `v3/paypal/psps` to `auth-request` (ecommerce for io)
---
> [CHK-2158] fix(policy):update calculate fee

- src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_base_policy.xml.tpl
- src/domains/wallet-app/04_apim_payment_wallet.tf
- Add wallet user-group check policy to pass client header to payment method
---
> [CHK-2124] add wallet user group

- src/domains/wallet-app/api/npg-notifications/v1/_base_policy.xml.tpl
- update wallet policy notifications
The goal of this PR is to add policy to handle wallet notification according to:
- https://developer.nexi.it/it/api/notifica
- https://github.com/pagopa/pagopa-wallet-service/pull/62
---
> feat: CHK-2162 update policy for handle wallet notifications

- src/domains/receipts-app/00_alert.tf
> chore: Upd-alert-threshold-receipts

- src/domains/ecommerce-app/00_alerts.tf
- src/domains/ecommerce-app/README.md
* add alert for auth request KO on eCommerce
---
Depends on #1521
> [CHK-2085] feat: alert for auth request KO

- src/domains/shared-app/04_apim_statuspage.tf
> [PRDP-244] chore: add helpdesk to status page config

- src/domains/ecommerce-app/04_apim_ecommerce_io.tf
- src/domains/ecommerce-app/99_variables.tf
- src/domains/ecommerce-app/README.md
- src/domains/ecommerce-app/api/ecommerce-io/v1/_create_new_session.xml.tpl
- src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
- src/domains/ecommerce-app/env/weu-prod/terraform.tfvars
- src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/README.md
The goal of this PR is to add JWT generation for eCommerce API for IO in create session policy.
---
> feat: CHK-2184 jwt token for post sessions

- src/domains/ecommerce-app/04_apim_ecommerce_io.tf
- src/domains/ecommerce-app/api/ecommerce-io/v1/_base_policy.xml.tpl
The goal of this PR is to add jwt token check for all eCommerce for IO APIs except `POST /sessions`.
---
> feat: CHK-2185 Add check policy eCommerce for IO

- src/domains/ecommerce-app/env/weu-prod/terraform.tfvars
> fix: add disabled url for ecommerce io

- src/domains/bizevents-common/02_security.tf
- src/domains/bizevents-common/README.md
> chore: Add otl secret biz domain

- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
> feat: increase max run for ecommerce

- src/domains/ecommerce-app/README.md
- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/03_storage.tf
- src/domains/ecommerce-common/README.md
Tuning queue alert
Transient queues storage account alert: more than 1000 messages total
Dead letter queues storage account alert: more than 200 messages total
---
> Tuning alert dead letter queues and transient queues

- src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
- Updated biz-event service apim in biz-event domain
Added new APIs ad defined in https://pagopa.atlassian.net/wiki/spaces/PPR/pages/822870269/Analisi+APIs+Monitoring+Recover+helpdesk-receipt#API-di-recupero-BizEvent
---
> [PRDP-233] feat: Update biz-event service apim openapi

- src/domains/receipts-app/api/receipt-helpdesk/v1/_openapi.json.tpl
- Updated receipt Helpdesk apim in receipt domain, to meet new specificatio
Updated apim, given the following specifications: https://pagopa.atlassian.net/wiki/spaces/PPR/pages/822870269/Analisi+APIs+Monitoring+Recover+helpdesk-receipt#API-getErrorsToReview-:wip:
---
> [PRDP-243] feat: updated receipt apim openapi

- src/domains/ecommerce-app/api/ecommerce-helpdesk-api/v1/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-technical-helpdesk-api/v1/_openapi.json.tpl
Update helpdesk openapi to add `authorizationRequestId` and `paymentGateway`
Update helpdesk openapi to add `authorizationRequestId` and `paymentGateway`
---
> Update helpdesk openapi response body

- src/domains/ecommerce-app/env/weu-prod/terraform.tfvars
> feat: delete ecommerce tx scheduler for pdb

- src/domains/ecommerce-app/04_apim_ecommerce.tf
- src/domains/ecommerce-app/README.md
- src/domains/ecommerce-app/api/ecommerce-helpdesk-api/v1/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-helpdesk-api/v1/_pgs_search.xml.tpl
> feat: add get status for pgs helpdesk

- src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Added detail type wallet for request authorization into transaction service openapi 
---
> CHK-2188 feat: added new detailType wallet into transaction service openapi

- src/domains/ecommerce-app/04_apim_ecommerce_io.tf
- src/domains/ecommerce-app/api/ecommerce-io/v1/get_transaction.xml.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v1/post_transactions.xml.tpl
Add switch pm/ecommerce for get and post transaction for ecommerce-for-io api group
---
> [CHK-2217] switch get post transaction

- src/domains/afm-common/03_storage_account_afm.tf
- src/domains/apiconfig-common/03_storage_account.tf
- src/domains/canoneunico/03_storage_account.tf
- src/domains/fdr-common/03_storage_account_fdr.tf
- src/domains/gps-common/03_reporting_storage_account.tf
- src/domains/gps-common/03_storage_account.tf
- src/domains/nodo-common/03_storage_account_nodo_storico.tf
- src/domains/nodo-secret/storageaccount.tf
- src/domains/receipts-common/03_storage.tf
- src/domains/shared-common/03_storage_account_taxonomy.tf
- src/next-aks/01_velero.tf
> feat: Fix sa backup retention configuration

- src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
- src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
- src/domains/wallet-app/env/weu-dev/terraform.tfvars
- src/domains/wallet-app/env/weu-uat/terraform.tfvars
Modified io backend base path
---
> fix: modified io backend base path

- src/domains/receipts-app/00_alert.tf
- src/domains/receipts-common/03_storage.tf
> chore: Tuning alert pdf

- src/domains/ecommerce-common/00_alerts.tf
> fix: set alert ecommerce for 90 availability

- src/domains/shared-app/99_locals.tf
- Added new env CHECK_SIZE_INTERVAL to customize the size check interval
- Added new env MIN_STABLE_SIZE_ITERATIONS to customize the iteration with stable size
---
> [PRDP-287] chore: Add new env to pdf engine app service

- src/domains/wallet-app/04_apim_payment_wallet.tf
- src/domains/wallet-app/README.md
- src/domains/wallet-app/api/webview-payment-wallet/v1/_openapi.json.tpl
- src/domains/wallet-app/api/webview-payment-wallet/v1/get_psps_policy.xml.tpl
* update spec for `createWalletSession` operation
This change is needed to pass the PSP id when creating a PayPal session
---
Depends on #1578
> [CHK-2238] feat(wallet): update spec for `createWalletSession` operation

- src/domains/wallet-app/04_apim_payment_wallet.tf
- src/domains/wallet-app/README.md
- src/domains/wallet-app/api/webview-payment-wallet/v1/_openapi.json.tpl
- src/domains/wallet-app/api/webview-payment-wallet/v1/get_psps_policy.xml.tpl
* add API endpoint to be used in wallet webview to get fees for Alternative Payment Methods (APMs) when onboarding
---
> [CHK-2236] feat(wallet-webview): add API endpoint to compute fees for APMs when onboarding

- src/domains/observability/04_datafactory_dataset.tf
- src/domains/observability/04_datafactory_dataset_cosmos.tf
- src/domains/observability/04_datafactory_pipeline.tf
- src/domains/observability/datafactory/cosmos/BIZEVENTS_OK.json
- src/domains/observability/datafactory/cosmos/type_properties/BIZEVENTS_OK.json
- src/domains/observability/datafactory/datasets/KPI_ESITI_DAILY.json
- src/domains/observability/datafactory/datasets/KPI_RENDICONTAZIONI.json
- src/domains/observability/datafactory/datasets/KPI_RENDICONTAZIONI_DETAILS.json
- src/domains/observability/datafactory/datasets/type_properties/KPI_ESITI_DAILY.json
- src/domains/observability/datafactory/datasets/type_properties/KPI_RENDICONTAZIONI.json
- src/domains/observability/datafactory/datasets/type_properties/KPI_RENDICONTAZIONI_DETAILS.json
- src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI.json
- src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI_DAILY_Manuale.json
- src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI_Manuale.json
- src/domains/observability/datafactory/pipelines/KPI_FDR_RENDICONTAZIONI.json
> add new pipeline for KPI FDR

- .github/workflows/static_analysis_pr.yml
- README.md
- Add static analysis main action
- Add static analysis PR action
- Add badge on ReadMe.md
---
> feat: add static analyis PR & github badge

- .github/workflows/static_analysis.yml
- .github/workflows/static_analysis_pr.yml
Reuse github action to perform static analysis
To avoid code duplication.
---
> feat: Reuse static analysis action

- src/domains/receipts-app/api/receipt-helpdesk/v1/_openapi.json.tpl
- Introducing getReceiptMessage entry on receipts helpdesk openapi
---
> [PRDP-302] feat: updated receipt helpdesk openapi

- src/domains/nodo-app/00_data.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-app/05_fn_ndp_verifyko_to_datastore.tf
- src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
- src/domains/nodo-app/env/weu-prod/terraform.tfvars
> Scaling verifyko fn

- src/domains/receipts-app/api/receipt-helpdesk/v1/_openapi.json.tpl
- added getCart api to receipt helpdesk openapi
---
> [PRDP-307] chore: Updated receipt helpdesk openapi with getCart API

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
- src/domains/nodo-app/99_variables.tf
- src/domains/nodo-app/env/weu-prod/terraform.tfvars
> Fix Verify ko autoscaling

- src/core/env/dev/terraform.tfvars
- Added Event Hub topic to send `PSP` kpi data to `Datalake`
It's necessary to create new topic on Event Hub in order to transfer `PSP` kpi data to `PDND` team.
---
> added topic for qi psp kpi

- src/domains/canoneunico/env/prod/terraform.tfvars
- src/domains/fdr-app/02_function.tf
- src/domains/fdr-app/99_variables.tf
- src/domains/fdr-app/env/weu-dev/terraform.tfvars
- src/domains/fdr-app/env/weu-prod/terraform.tfvars
- src/domains/fdr-app/env/weu-uat/terraform.tfvars
- src/domains/gps-common/03_reporting_storage_account.tf
- src/domains/gps-common/99_variables.tf
- src/domains/gps-common/env/weu-prod/terraform.tfvars
- src/elk-monitoring/env/weu-prod/terraform.tfvars
> feat: Partial DIS-43 - updated SA replication type

- src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
> enable pm for ecommerce-for-io api in uat

- src/domains/receipts-app/api/receipt-helpdesk/v1/_openapi.json.tpl
- Updated openapi for Helpdesk after changes regarding cart management
---
> [PRDP-285] feat: updated openapi.json.tpl

- src/domains/ecommerce-app/api/ecommerce-helpdesk-api/v1/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-technical-helpdesk-api/v1/_openapi.json.tpl
Added a new endpoint on the helpdesk project to search by email or user's fiscal code for the list of active payment methods associated with them.
The change was made to provide a useful api to retrieve a user's active payment methods 
---
> [CHK-1864] feat: added new endpoint for search active payment method for user

- src/core/identity_rg.tf
Allow to have a single RG dedicated to managed identites
---
> feat: Added new resource group for identities

- src/domains/checkout-app/05_checkout_fe.tf
* redirect ecommerce-fe outcome pages to ecommerce-fe index
This change is required to make the payment outcome propagate through ecommerce-fe pages when outcome pages are visited directly and not through React routing.
Without this change, some payment flows (in particular when using NPG) do not work, as the CDN would redirect the missing resources to Checkout's main page (`index.html`), instead of the ones from `ecommerce-fe`.
Note that `ecommerce-fe` internally also uses React routing, that's why the CDN redirects to `ecommerce-fe/index.html`.
**For reviewers:**
- With this configuration we select manually which pages are redirected (here `gdi-check` and `esito`), should we redirect the whole `ecommerce-fe` directory to be more future-proof?
---
> [CHK-2305] feat(cdn): redirect ecommerce-fe outcome pages to ecommerce-fe index

- src/domains/wallet-app/api/payment-wallet-for-ecommerce/v1/_openapi.json.tpl
* update GET `auth-data` policy to add support for APM wallets
See pagopa/pagopa-wallet-service#83
---
> [CHK-2258] feat(wallet): update GET `auth-data` policy to add support for APM wallets

- src/domains/wallet-common/05_wallet_cdn.tf
Add nexigroup.com as exceptions in the wallet CSP
- Add domain nexigroup.com
---
> [CHK-2243] Add nexigroup to exceptions

- src/domains/wallet-app/api/payment-wallet/v1/_get_payment_methods_policy.xml.tpl
> feat: add x-client-id for payment-method for IO

- src/domains/wallet-app/api/payment-wallet/v1/_get_wallets_by_user_with_pm.xml.tpl
- src/domains/wallet-app/api/payment-wallet/v1/_openapi.json.tpl
- add VALIDATED as wallet status
- patch Payment Manager date according to dateTime format, so `2022-04-07 14:03:42` -> `2022-04-07T12:03:42.0000000+00:00`
---
> feat: update wallet api

- src/domains/bizevents-app/00_alert.tf
- src/domains/bizevents-app/00_monitor.tf
- src/domains/bizevents-app/99_locals.tf
- src/domains/bizevents-app/README.md
> chore: PAGOPA-1220-configurazione-alert-su-opsgenie-per-biz-event

- .tfsec/tfsec.yml
> chore: Added tfsec config file

- src/core/99_locals.tf
- src/core/99_variables.tf
- src/domains/aca-common/02_security.tf
- src/domains/afm-common/02_keyvault.tf
- src/domains/apiconfig-common/02_security.tf
- src/domains/bizevents-common/02_security.tf
- src/domains/ecommerce-common/02_security.tf
- src/domains/fdr-secret/02_security.tf
- src/domains/gps-common/02_security.tf
- src/domains/mock-common/02_security.tf
- src/domains/qi-common/02_security.tf
- src/domains/selfcare-common/02_security.tf
- src/domains/shared-common/02_security.tf
- src/domains/wallet-common/02_security.tf
> feat: Increase kv access policy for admin group

- src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
> feat: enable BNLIITRR for ecommerce npg only for DEV

- src/domains/wallet-common/05_wallet_cdn.tf
> fix: CHK-2362 add wisp2.pagopa.gov.it to wallet csp

- src/domains/wallet-common/05_wallet_cdn.tf
> fix: domain for csp wallet

- src/core/99_locals.tf
- src/core/99_variables.tf
> feat: Restored locals

- src/domains/ecommerce-app/api/ecommerce-io/v1/_calculate_fees_policy.xml.tpl
> fix: CHk-2271 add idpsp as string and belowTh as boolean in calculateFee

- src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v1/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Add field to map gateway authorization status into eCommerce  `GET transaction` api call. This field will be used to perform custom error mapping for NPG error codes
Add field to map gateway authorization status into eCommerce  `GET transaction` api call. This field will be used to perform custom error mapping for NPG error codes
---
> feat: add  field gatewayAuthorizationStatus to get transaction

- src/domains/gps-common/env/weu-prod/terraform.tfvars
> feat: Updated gps cosmos zone redundancy

- src/domains/ecommerce-common/03_storage.tf
Change dead letter events alert thresholds
Change dead letter events alert thresholds
---
> chore(alert-conf): change dead letter event thresholds

- src/domains/bizevents-app/api/bizevents-helpdesk/v1/_base_policy.xml
- src/domains/bizevents-app/api/bizevents-helpdesk/v1/_openapi.json.tpl
- src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
- src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
- Updated `biz-event-service` openapi
---
> [PRDP-356] Updated openapi as defined in service repo

- src/domains/wallet-common/02_security.tf
- src/domains/wallet-common/README.md
- add secret to generate token jwt for wallet NPG notifications 
---
> feat: CHK-2407 add jwt key to npg notification

- src/domains/bizevents-common/02_security.tf
- src/domains/bizevents-common/README.md
> chore : Upd biz secrets

- src/core/azure_devops_agent.tf
> feat: Updated sku to Standard_B2ms for iac vmss

- src/core/01_custom_roles.tf
- src/core/README.md
> feat: Added custom role for IaC azdo pipelines

- src/domains/bizevents-app/api/bizevents-helpdesk/v1/_openapi.json.tpl
- src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
- src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
- reviewed `biz-event-service` openapi
---
> reviewed biz-event-service openapi

- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
> feat: Enabled ecommerce cosmos multiaz

- src/domains/fdr-app/env/weu-prod/terraform.tfvars
- src/domains/nodo-app/05_fn_ndp_verifyko_to_datastore.tf
- src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
- src/domains/nodo-app/99_variables.tf
- src/domains/nodo-app/env/weu-dev/terraform.tfvars
- src/domains/nodo-app/env/weu-prod/terraform.tfvars
- src/domains/nodo-app/env/weu-uat/terraform.tfvars
- src/domains/shared-app/env/weu-prod/terraform.tfvars
> feat: Updated storage account replication type

- src/domains/receipts-common/10_github_identity.tf
> chore: GitHub federated identity receitps repp

- src/domains/afm-app/04_apim_afm_calculator.tf
- src/domains/afm-app/api/calculator-service/v2/_base_policy.xml
- src/domains/afm-app/api/calculator-service/v2/_openapi.json.tpl
Adding v2 version afm calculator api for multiEC cart
This addition is needed for the future implementation of the cart in GEC
---
> PAGOPA-1172 adding afm calculator v2 api

- src/domains/ecommerce-common/03_storage.tf
- src/domains/ecommerce-common/README.md
Duplicate eCommerce storage account queues with -b suffix to perform blue instance tests
Duplicate eCommerce storage account queues with -b suffix to perform blue instance tests
---
> Create blue queue ecommerce

- src/domains/shared-app/04_apim_statuspage.tf
Add `gpd-upload` on status API
`sh terraform.sh apply weu-dev --target=module.apim_api_statuspage_api_v1`
---
> chore(GPD): add gpd-upload on status API [PAGOPA-1473] 

- src/domains/ecommerce-app/api/ecommerce-io/v1/_get_wallets_by_user_with_pm.xml.tpl
- src/domains/wallet-app/api/payment-wallet/v1/_get_wallets_by_user_and_walletId_with_pm.xml.tpl
- src/domains/wallet-app/api/payment-wallet/v1/_get_wallets_by_user_with_pm.xml.tpl
clean stars from masked pan card details for appio-wallet and appio-ecommerce vs pm
---
> [CHK-2482] clean stars from masked pan card details for appio

- .devops/canoneunico-code-review-pipelines.yml
- .devops/canoneunico-deploy-pipelines.yml
- src/domains/shared-common/.terraform.lock.hcl
- src/domains/shared-common/01_github_runner.tf
- src/domains/shared-common/01_network.tf
- src/domains/shared-common/02_security.tf
- src/domains/shared-common/03_cosmosdb_authorizer.tf
- src/domains/shared-common/03_cosmosdb_iuvgenerator.tf
- src/domains/shared-common/03_storage_account.tf
- src/domains/shared-common/03_storage_account_taxonomy.tf
- src/domains/shared-common/03_storage_account_test_data.tf
- src/domains/shared-common/10_github_identity.tf
- src/domains/shared-common/99_main.tf
- src/domains/shared-common/README.md
- added new pipelines canoneunico
- shared-common updated modules to v7.60.0
---
> feat: Iac-phase-3

- src/next-core/00_data.tf
- src/next-core/00_network.tf
- src/next-core/05_messages.tf
- src/next-core/99_variables.tf
- src/next-core/README.md
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Added new evh 03 and 04

- src/domains/wallet-app/04_apim_payment_wallet_migrations.tf
- src/domains/wallet-app/99_variables.tf
- src/domains/wallet-app/README.md
- src/domains/wallet-app/api/payment-wallet-migrations/v1/_base_policy.xml.tpl
- src/domains/wallet-app/api/payment-wallet-migrations/v1/_openapi.json.tpl
- src/domains/wallet-app/env/weu-dev/terraform.tfvars
- add API to migrate wallet from Payment Manager
The goal of this PR is to add new api to handle wallet migrations from Payment Manager, with api key and rate limit (to be fine-tuned).
---
> feat: CHK-25-21 Add migrations api for Payment Manager

- src/domains/gps-app/07_apim_v2_donations.tf
- src/domains/gps-app/07_apim_v2_donazione_ucraina.tf
- src/domains/gps-app/README.md
- src/domains/gps-app/api/payments-service/v1/rest/_base_policy.xml
Remove `set-query-parameter` by policy for these query params:
- `pageNum`
- `pageSize`
`sh terraform.sh apply weu-dev --target=module.apim_api_gpd_payments_rest_external_api_v1`
`pageNum` and `pageSize` are set by `GPD-Payments` micro-service.
---
> chore(GPD): remove useless `set-query-parameter` [PAGOPA-1533] 

- src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.25.0.xml
- src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.25.0.xml
- src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.25.0.xml
- src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.25.0.xml
Add new version to all psql schemas
Addition needed to maintain consistency between schemas
---
> align psql schemas

- src/next-core/00_network.tf
- src/next-core/01_network.tf
> feat: Added rt to sia

- src/domains/nodo-app/00_alert_faultcode.tf
- src/domains/nodo-app/00_alert_ndp_verifyko.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- removed sev3 alerts regarding verify-ko from Opsgenie
---
> chore: Remove alert SEV3 from opsgenie

- src/domains/ecommerce-common/03_storage.tf
- src/domains/ecommerce-common/README.md
Rename authorization requested retry event queue to authorization outcome waiting queue
---
> [CHK-2510] authorization outcome waiting queue

- .devops/ecommerce-deploy-pipelines.yml
Add missing checkout E2E tests repo ref
Add missing checkout E2E tests repo ref
---
> fix(IAC-deploy): add missing checkout tests repo ref back

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/cfg-partner/3.24.0/db.changelog-20231129000000_add_column_to_canali_nodo_and_canali_view.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.24.0/db.changelog-20231129000000_add_column_to_stazioni.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.24.0/db.changelog-20231129000000_set_standin-keys.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.24.0.xml
- src/psql/nodo/liquibase/changelog/cfg/3.24.0/db.changelog-20231129000000_add_column_to_canali_nodo_and_canali_view.xml
- src/psql/nodo/liquibase/changelog/cfg/3.24.0/db.changelog-20231129000000_add_column_to_stazioni.xml
- src/psql/nodo/liquibase/changelog/cfg/3.24.0/db.changelog-20231129000000_set_standin-keys.xml
- src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.24.0.xml
- added scripts for 3.24 cfg
---
> fix: [NOD-738] Nodo liquibase script

- src/domains/apiconfig-common/02_security.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
> fix: Secret cfg

- src/domains/nodo-common/10_github_identity.tf
- Added repository references for managed-identity CD 
This fix is needed in order to add managed-identity handling for new repositories
---
> feat: added repositories for managed-identity CD

- src/domains/canoneunico/.terraform.lock.hcl
- src/domains/canoneunico/03_storage_account.tf
- src/domains/canoneunico/99_main.tf
- src/domains/canoneunico/99_outputs.tf
- src/domains/canoneunico/99_variables.tf
- src/domains/canoneunico/README.md
- src/domains/canoneunico/env/dev/terraform.tfvars
This PR create container sftp CUP for corporate according to [CUP Fase 1](https://pagopa.atlassian.net/wiki/spaces/IQCGJ/pages/938082992/Design+Review+CUP+Fase+1)
---
> chore: Create CUP sftp localusers

- src/domains/wallet-common/02_security.tf
- src/domains/wallet-common/README.md
> feat: add wollet token test for migration

- src/domains/bizevents-common/02_security.tf
- src/domains/qi-common/02_security.tf
> chore: Switch prod ns02 ns04

- src/domains/observability/datafactory/pipelines/PDND_KPI_DASPO.json
- src/domains/observability/datafactory/pipelines/PDND_KPI_LFDR.json
- src/domains/observability/datafactory/pipelines/PDND_KPI_LSPO.json
- src/domains/observability/datafactory/pipelines/PDND_KPI_NRFDR.json
- src/domains/observability/datafactory/pipelines/PDND_KPI_TNSPO.json
- src/domains/observability/datafactory/pipelines/PDND_KPI_TPNP.json
- src/domains/observability/datafactory/pipelines/PDND_KPI_WAFDR.json
- src/domains/observability/datafactory/pipelines/PDND_KPI_WPNFDR.json
- Fixed several issue about pipelines query
Fixed several issue about pipelines used to transfer PSP kpi data to Data Lake 
---
> [PQI-66] feat: fix pipelines query

- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/README.md
Add secret that will contain redirect PSP to host url mapping
Add secret that will contain redirect PSP to host url mapping
---
> feat: add checkout redirect url mapping secret

- src/core/api/nodopagamenti_api/nodoPerPM/v2/_openapi.json.tpl
- src/domains/nodo-app/api/nodopagamenti_api/nodoPerPM/v2/_openapi.json.tpl
> [CHK-2448] fix(closepayment): fix redirect fields `additionalPaymentInformations.{fee,totalAmount}` type

- src/domains/gps-app/04_apim_gpd_core.tf
- src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
- src/domains/gps-app/api/gpd_api/debt-position-services/v2/_openapi.json.tpl
- src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
- src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
- src/domains/gps-app/api/pn-integration/_openapi.json.tpl
- updated openapi for the new nav field
- new nav field on the database
---
> feat: [PAGOPA-1569] openapi for nav

- src/domains/afm-app/04_apim_afm_calculator.tf
- src/domains/afm-app/api/calculator-service/node/v2/_base_policy.xml
- src/domains/afm-app/api/calculator-service/node/v2/_openapi.json.tpl
Adding api v2 afm calculator for node
Needed to maintain the documentation up to date
---
> PAGOPA-1495 adding api v2 afm calculator for node

- src/synthetic-monitoring/.terraform.lock.hcl
- src/synthetic-monitoring/00_data.tf
- src/synthetic-monitoring/01_analytics_workspace.tf
- src/synthetic-monitoring/01_monitoring.tf
- src/synthetic-monitoring/02_monitoring.tf
- src/synthetic-monitoring/99_locals.tf
- src/synthetic-monitoring/99_main.tf
- src/synthetic-monitoring/99_variables.tf
- src/synthetic-monitoring/README.md
- src/synthetic-monitoring/env/weu-dev/backend.ini
- src/synthetic-monitoring/env/weu-dev/backend.tfvars
- src/synthetic-monitoring/env/weu-dev/terraform.tfvars
- src/synthetic-monitoring/env/weu-prod/backend.ini
- src/synthetic-monitoring/env/weu-prod/backend.tfvars
- src/synthetic-monitoring/env/weu-prod/terraform.tfvars
- src/synthetic-monitoring/env/weu-uat/backend.ini
- src/synthetic-monitoring/env/weu-uat/backend.tfvars
- src/synthetic-monitoring/env/weu-uat/terraform.tfvars
- src/synthetic-monitoring/monitoring_configuration.json
- src/synthetic-monitoring/monitoring_configuration.json.tpl
- src/synthetic-monitoring/terraform.sh
> feat: Added synthetic monitoring module

- src/synthetic-monitoring/02_monitoring.tf
- src/synthetic-monitoring/99_variables.tf
- src/synthetic-monitoring/env/weu-dev/terraform.tfvars
> feat: Added self alert variable

- src/domains/wallet-app/api/payment-wallet-migrations/v1/_base_policy.xml.tpl
> fix: [wallet-migration] add rate limit for internal ip address

- src/domains/nodo-app/00_apim_v2.tf
- src/domains/nodo-app/07_apim_v2_nodo_services_01_decoupler.tf
- src/next-core/env/uat/terraform.tfvars
> fix:  Apim v2 data

- src/core/01_custom_roles.tf
> fix: Added missing roles

- src/next-core/03_apim.tf
- src/next-core/README.md
- src/next-core/env/uat/terraform.tfvars
> fix: Apim plan

- src/core/apim_nodo_services_auth_02_product.tf
- src/domains/bizevents-app/04_apim_bizevents.tf
- src/domains/fdr-app/04_apim_fdr_fase3.tf
- src/domains/gps-app/04_apim_gpd.tf
- src/domains/gps-app/04_apim_gpd_core.tf
- src/domains/gps-app/04_apim_gpd_payments.tf
- src/domains/gps-app/04_apim_gpd_reporting.tf
- src/domains/nodo-app/07_apim_v2_nodo_services_auth_02_product.tf
after this change, when an EC/PSP creates a key on [BO portal](https://docs.pagopa.it/manuale-back-office-pagopa) it is automatically approved.
```
src/core
sh terraform.sh apply weu-<ENV> \
-target=module.apim_nodo_dei_pagamenti_product_auth
src/domains/bizevents-app
sh terraform.sh apply weu-<ENV> \
-target=module.apim_bizevents_product
src/domains/fdr-app
sh terraform.sh apply weu-<ENV> \
-target=module.apim_fdr_product_psp \
-target=module.apim_fdr_product_org
src/domains/gps-app
sh terraform.sh apply weu-<ENV> \
-target=module.apim_gpd_integration_product \
-target=module.apim_debt_positions_product \
-target=module.apim_gpd_payments_rest_external_product \
-target=module.apim_gpd_reporting_analysis_product
```
Self-approved apim products are : 
**EC**
- Connessione con nodo
- Nodo …
> chore: Remove `approval_required` for pagoPA BO products

- src/core/dns_private.tf
- src/next-core/03_apim.tf
> feat: Apim v2 dns

- src/domains/selfcare-app/00_alert_backoffice.tf
- src/domains/selfcare-app/00_data.tf
- src/domains/selfcare-app/99_locals.tf
- src/domains/selfcare-app/README.md
> [Selfcare Backoffice] Alert Opsgenie

- src/next-core/04_appgw.tf
- src/next-core/env/prod/terraform.tfvars
> fix: Apim v2 sku and ip zones

- src/next-aks/00_aks.tf
- src/next-aks/00_monitor.tf
- src/next-aks/01_velero.tf
- src/next-aks/99_locals.tf
- src/next-aks/README.md
> feat: Velero backup alert

- src/domains/selfcare-common/04_app_configuration_feature.tf
- src/domains/selfcare-common/README.md
> chore: Add role-ass to app-conf selfcare

- src/domains/selfcare-common/04_app_configuration_feature.tf
> role data owner

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
> feat: add secret nodo offline

- src/domains/ecommerce-app/api/ecommerce-io/v1/_openapi.json.tpl
Fix some missing service rename to application
---
> [CHK-2628] fix-services-rename

- src/domains/fdr-common/env/weu-prod/terraform.tfvars
- src/domains/gps-common/env/weu-prod/terraform.tfvars
- src/domains/nodo-common/env/weu-prod/terraform.tfvars
> feat: Updated postgres backup retention period

- src/domains/checkout-app/01_monitor.tf
- src/domains/checkout-app/05_checkout_fe.tf
- src/domains/checkout-app/05_checkout_function.tf
> CHK-2624 prepare csp fix

- src/domains/checkout-app/.terraform.lock.hcl
- src/domains/checkout-app/01_monitor.tf
- src/domains/checkout-app/01_network.tf
- src/domains/checkout-app/04_apim_checkout.tf
- src/domains/checkout-app/04_apim_checkout_ec.tf
- src/domains/checkout-app/05_checkout_fe.tf
- src/domains/checkout-app/05_checkout_function.tf
- src/domains/checkout-app/05_pagopa_proxy.tf
- src/domains/checkout-app/99_locals.tf
- src/domains/checkout-app/99_main.tf
- src/domains/checkout-app/99_variables.tf
- src/domains/checkout-app/env/weu-dev/terraform.tfvars
- src/domains/checkout-app/env/weu-prod/terraform.tfvars
- src/domains/checkout-app/env/weu-uat/terraform.tfvars
> feat: Checkout app v3

- src/domains/selfcare-common/04_app_configuration_feature.tf
- src/domains/selfcare-common/README.md
- Added two new flags to toggle commission bundles by type
[VAS-880](https://pagopa.atlassian.net/browse/VAS-880?atlOrigin=eyJpIjoiNGYwNGM4NDRjYjBjNDU0OTk1NGIwOTc3ODFiMzJkNmQiLCJwIjoiaiJ9)
---
[VAS-880]: https://pagopa.atlassian.net/browse/VAS-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-880] feat: Added two new flags to toggle commission bundles by type

- src/domains/gps-common/.terraform.lock.hcl
- src/domains/gps-common/10_github_identity.tf
- src/domains/gps-common/README.md
:octocat: GH identity for https://github.com/pagopa/pagopa-gpd-payments-pull
---
> [GPD Payments Pull] gh identity

- src/next-core/05_messages.tf
- src/next-core/99_variables.tf
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Updated eventhub networking

- src/domains/checkout-app/01_network.tf
- src/domains/checkout-app/05_pagopa_proxy_ha.tf
- src/domains/checkout-app/99_variables.tf
- src/domains/checkout-app/env/weu-dev/terraform.tfvars
- src/domains/checkout-app/env/weu-prod/terraform.tfvars
- src/domains/checkout-app/env/weu-uat/terraform.tfvars
- src/domains/shared-app/01_app_service_pdf_engine_ha.tf
- src/domains/shared-app/99_variables.tf
- src/domains/shared-app/README.md
- src/domains/shared-app/env/weu-dev/terraform.tfvars
- src/domains/shared-app/env/weu-prod/terraform.tfvars
- src/domains/shared-app/env/weu-uat/terraform.tfvars
- src/next-core/00_acr.tf
- src/next-core/00_apim.tf
- src/next-core/00_key_vault.tf
- src/next-core/00_monitor.tf
- src/next-core/00_network.tf
- src/next-core/03_tools_cae.tf
- src/next-core/06_node_forwarder.tf
- src/next-core/99_variables.tf
- src/next-core/README.md
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: New critical app service zone balanced DIS-45

- src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
- src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
Add Sondrio PSP id to psp list
Add Sondrio PSP id to psp list
---
> fix: add sondrio psp to psps list config

- src/domains/bizevents-app/api/bizevents-helpdesk/v1/_openapi.json.tpl
- src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
- src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
> chore: Upd api biz

- src/domains/canoneunico/03_storage_account.tf
> fix(CUP): Update SFTP homeDirectory

- src/domains/selfcare-common/04_app_configuration_feature.tf
- src/domains/selfcare-common/README.md
- Added new flag to toggle Creditor institution's delegations' pages
[VAS-555](https://pagopa.atlassian.net/browse/VAS-555?atlOrigin=eyJpIjoiYzFmYWQ1MDVkYjY1NDMyMWE0MDhkYWFiNTc5ZjU1NTUiLCJwIjoiaiJ9)
---
[VAS-880]: https://pagopa.atlassian.net/browse/VAS-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VAS-555]: https://pagopa.atlassian.net/browse/VAS-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-555] feat: Add new feature flag for selfcare-backoffice

- src/domains/wallet-app/api/payment-wallet/v1/_update_applications_with_pm.xml.tpl
fix application/content header in pm invocation
---
> fix application/content header in pm invocation

- src/domains/wallet-app/api/payment-wallet/v1/_base_policy.xml.tpl
Add `x-client-id` valued with IO for payment-wallet api group
Add `x-client-id` valued with IO for payment-wallet api group
---
> feat: add x-client-id for payment-wallet policy

- src/domains/wallet-common/03_redis.tf
- src/domains/wallet-common/99_variables.tf
- src/domains/wallet-common/env/weu-dev/terraform.tfvars
- src/domains/wallet-common/env/weu-prod/terraform.tfvars
- src/domains/wallet-common/env/weu-uat/terraform.tfvars
set redis to be multi az in production, with premium plan (multi az only supported by premium plans)
---
> feat: Updated prod wallet redis configuration

- src/domains/afm-common/10_github_identity.tf
```
sh terraform.sh apply weu-<ENV> \
-target=module.identity_cd_01 \
-target=azurerm_key_vault_access_policy.gha_iac_managed_identities \
-target=null_resource.github_runner_app_permissions_to_namespace_cd_01
```
---
> chore: Force apply identity afm

- src/domains/canoneunico/00_alert.tf
- src/domains/canoneunico/00_data.tf
- src/domains/canoneunico/02_function.tf
- src/domains/canoneunico/99_variables.tf
- src/domains/canoneunico/README.md
- src/domains/canoneunico/env/weu-prod/terraform.tfvars
- src/domains/gps-app/99_variables.tf
- Alerts on CUP functions were added
- Cron Batch schedule was updated
---
> feat: add alerts on CUP functions

- src/domains/wallet-app/env/weu-uat/terraform.tfvars
> chore(migration): Enable migration API on UAT

- src/domains/wallet-app/api/npg-notifications/v1/_base_policy.xml.tpl
Fix notification wallet NPG policy to take into account `paymentMethod` instead of `paymentCircuit` field for evaluate CARD payment
Fix notification wallet NPG policy to take into account `paymentMethod` instead of `paymentCircuit` field for evaluate CARD payment
---
> fix: NPG wallet cards policy

- src/domains/bizevents-common/02_security.tf
- src/domains/bizevents-common/README.md
> chore: Fix biz slack secret

- src/domains/ecommerce-common/02_security.tf
> feat: Added redis ecommerce params in secrets

- src/domains/fdr-common/env/weu-dev/terraform.tfvars
- src/domains/gps-common/env/weu-dev/terraform.tfvars
- src/domains/nodo-common/env/weu-dev/terraform.tfvars
- src/next-core/01_network_dns_private.tf
- src/next-core/99_variables.tf
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Postgres private dns dev

- src/domains/wallet-common/00_alerts.tf
- src/domains/wallet-common/01_network.tf
- src/domains/wallet-common/03_storage.tf
- src/domains/wallet-common/99_locals.tf
- src/domains/wallet-common/99_variables.tf
- src/domains/wallet-common/README.md
- src/domains/wallet-common/env/weu-dev/terraform.tfvars
- src/domains/wallet-common/env/weu-prod/terraform.tfvars
- src/domains/wallet-common/env/weu-uat/terraform.tfvars
* add storage account + queues for pagoPA wallet
These resources are needed to implement asynchronous update of wallet usages
---
> [CHK-2650] feat(wallet): add storage account + queues for pagoPA wallet

- src/domains/wallet-common/02_security.tf
- src/domains/wallet-common/README.md
This PR adds the elastic bearer token to Wallet KV to make it available at pod environment level
- add elastic_otel_token as ignored value's resource
Allows Wallet OTEL Agent to forward data to Elastic collector
---
> [CHK-2680] Add OTeL Elastic token to Wallet kv

- src/domains/ecommerce-app/api/npg-notification/_npg_notifications_policy.xml.tpl
Handle null additionalData for APM payments such as Paypal where `additionalData` field is not sent
Handle null additionalData for APM payments such as Paypal where `additionalData` field is not sent
---
> fix(NPG post notification): handle null additionalData

- src/domains/selfcare-common/04_app_configuration_feature.tf
- src/domains/selfcare-common/README.md
- Added feature flag to selfcare-common to toggle Payments receipts section in back-office
[VAS-686](https://pagopa.atlassian.net/browse/VAS-686?atlOrigin=eyJpIjoiNzMzNGJhYjY5YmU4NGYwYWI4ZWJiOTIwNmUxNzliZjEiLCJwIjoiaiJ9)
---
[VAS-686]: https://pagopa.atlassian.net/browse/VAS-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [VAS-686] feat: Added feature flag to selfcare-common

- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/99_variables.tf
- src/domains/ecommerce-common/env/weu-dev/terraform.tfvars
- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
- src/domains/ecommerce-common/env/weu-uat/terraform.tfvars
> feat: Decoupled redis ha creation from usage

- src/domains/apiconfig-common/02_security.tf
- src/domains/bizevents-common/02_security.tf
- src/domains/nodo-common/02_security.tf
- src/domains/shared-common/02_security.tf
> feat: Addedd redis hostname secrets

- src/domains/wallet-common/02_security.tf
- src/domains/wallet-common/README.md
> [CHK-2731] Add missing wallet storage account key for consumer side

- src/domains/canoneunico/env/weu-prod/terraform.tfvars
- Add `mynet` in PROD config `corporate_cup_users`
---
> chore(CUP): Add new corporate [PAGOPA-1679] 

- src/domains/fdr-app/00_data.tf
- src/domains/fdr-app/04_apim_fdr_fase1_auth.tf
- src/domains/fdr-app/README.md
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
> fix: Endpoint FdR auth

- src/domains/wallet-app/api/payment-wallet/v1/_update_applications.xml.tpl
Fix a variable name in policy
---
> [CHK-2738] fix(update-applications): variable name error in policy

- src/domains/nodo-app/00_data.tf
- src/domains/nodo-app/05_fn_ndp_verifyko_to_datastore.tf
- src/domains/nodo-app/05_fn_ndp_verifyko_to_tablestorage.tf
- src/domains/nodo-app/README.md
> fix: EH ns01 migration

- src/core-itn/.terraform.lock.hcl
- src/core-itn/00_azuread.tf
- src/core-itn/00_data.tf
- src/core-itn/00_key_vault.tf
- src/core-itn/00_monitor.tf
- src/core-itn/00_network.tf
- src/core-itn/01_network.tf
- src/core-itn/05_messages.tf
- src/core-itn/99_locals.tf
- src/core-itn/99_main.tf
- src/core-itn/99_variables.tf
- src/core-itn/README.md
- src/core-itn/env/dev/backend.ini
- src/core-itn/env/dev/backend.tfvars
- src/core-itn/env/dev/terraform.tfvars
- src/core-itn/env/prod/backend.ini
- src/core-itn/env/prod/backend.tfvars
- src/core-itn/env/prod/terraform.tfvars
- src/core-itn/env/uat/backend.ini
- src/core-itn/env/uat/backend.tfvars
- src/core-itn/env/uat/terraform.tfvars
- src/core-itn/terraform.sh
- src/next-core/01_network.tf
- src/next-core/README.md
- **init core-itn**
- **next-core: removed network resource linked to itn region**
- **added network resources for itn**
- **pre-commit fixs**
Allow to have a space where to create resource dedicated to the region italynorth
---
> breaking: Core-itn init with network

- src/next-aks/.terraform.lock.hcl
- src/next-aks/00_aks.tf
- src/next-aks/01_velero.tf
- src/next-aks/99_main.tf
- src/next-aks/99_variables.tf
- src/next-aks/README.md
> feat: Velero backup for each namespace

- src/domains/ecommerce-app/api/ecommerce-io/v1/_openapi.json.tpl
Related to https://github.com/pagopa/pagopa-infra/pull/1898, but isolated for integration test with IO
---
> feat: update ecommerce-io for node error

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/cfg-partner/3.28.0/db.changelog-20240410000000_metadata_ibanappoggio.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.27.0.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.28.0.xml
- src/psql/nodo/liquibase/changelog/cfg/3.28.0/db.changelog-20240410000000_metadata_ibanappoggio.xml
- src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.27.0.xml
- src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.28.0.xml
- src/psql/nodo/liquibase/changelog/offline/3.27.0/db.changelog-20240417000000_v_position_payment_status_snapshot.xml
- src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.27.0.xml
- src/psql/nodo/liquibase/changelog/offline/db.changelog-master-3.28.0.xml
- src/psql/nodo/liquibase/changelog/online/3.27.0/db.changelog-2024032911150000_add_index.xml
- src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.27.0.xml
- src/psql/nodo/liquibase/changelog/online/db.changelog-master-3.28.0.xml
- src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.27.0.xml
- src/psql/nodo/liquibase/changelog/re/db.changelog-master-3.28.0.xml
- src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.27.0.xml
- src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.28.0.xml
Added liquibase regarding releases 3.27 and 3.28 of Nodo
---
> feat: [NOD-809] Liquibase Oracle to Postgres rel 3.27-3.28

- src/domains/ecommerce-common/00_alerts.tf
- src/domains/ecommerce-common/README.md
Add alert for KO detected on POST notifications NPG callback api call
This alert monitor NPG authorization outcome endpoint in order to discover KO's
---
> feat(monitoring NPG): alert for KO on POST notification

- src/domains/selfcare-common/04_app_configuration_feature.tf
- introducing station testing feature flag
---
> [VAS-772] feat: introducing station testing feature flag

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/cfg-partner/3.28.0/db.changelog-20240410000000_metadata_ibanappoggio.xml
- src/psql/nodo/liquibase/changelog/cfg/3.28.0/db.changelog-20240410000000_metadata_ibanappoggio.xml
- changed liquibase property in CFG schema
---
> fix: [NOD-850] Fix Liquibase property

- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/03_redis.tf
- src/domains/ecommerce-common/99_variables.tf
- src/domains/ecommerce-common/README.md
- src/domains/ecommerce-common/env/weu-dev/terraform.tfvars
- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
- src/domains/ecommerce-common/env/weu-uat/terraform.tfvars
> feat: Cleanup redis configuration

- src/domains/printit-app/05_aks_middleware_tools.tf
- src/domains/printit-app/README.md
- src/domains/printit-secrets/00_generic.tf
- src/domains/printit-secrets/01_keyvault.tf
- src/domains/printit-secrets/README.md
- **secret: added app insight**
- **enabled aks middleware**
- **pre-commit fixs**
- 
---
> feat: Printit Enable aks middleware

- src/next-core/04_appgw.tf
> feat: Fix integration app gw listeners

- .devops/disaster-recovery.yml
> feat: Postgres failover approve stage

- src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl
- src/domains/fdr-app/api/fdr-service/org/v1/_openapi.json.tpl
- src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
> feat: NOD-863 allign openapi with idtransfer

- src/domains/fdr-app/04_apim_fdr_fase3.tf
- src/domains/fdr-app/05_fdr_xml_to_json_fn.tf
- src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
> feat: NOD-861 fix path conversione service

- src/next-core/01_network.tf
> feat: Added rt association to app gw integration snet

- src/domains/afm-app/04_apim_afm_calculator.tf
- src/domains/afm-app/README.md
- src/domains/afm-app/api/calculator-service/node/v1/_openapi.json.tpl
- src/domains/afm-app/api/calculator-service/node/v2/_openapi.json.tpl
- src/domains/afm-app/api/calculator-service/v1/_openapi.json.tpl
- src/domains/afm-app/api/calculator-service/v2/_openapi.json.tpl
> chore: PAGOPA-1726 updating openapi

- src/core/99_variables.tf
- src/core/README.md
- src/core/cosmos_db_payments.tf
- src/core/dns_private.tf
- src/core/env/prod/terraform.tfvars
> chore: Add `db-nodo-pagamenti-dr` a-record

- src/domains/observability/01_observability.tf
- src/domains/observability/README.md
> chore: Add dataexp data-conn

- src/domains/fdr-app/api/fdr-service-internal/v1/_openapi.json.tpl
- src/domains/fdr-app/api/fdr-service/org/v1/_openapi.json.tpl
- src/domains/fdr-app/api/fdr-service/psp/v1/_openapi.json.tpl
> feat: NOD-879 add STAND_IN_NO_RPT

- src/core-itn/00_monitor.tf
- src/core-itn/01_network.tf
- src/core-itn/90_tools_cae.tf
- src/core-itn/99_locals.tf
- src/core-itn/99_variables.tf
- src/core-itn/README.md
- src/core-itn/env/dev/terraform.tfvars
- src/core-itn/env/prod/terraform.tfvars
- src/core-itn/env/uat/terraform.tfvars
- src/next-core/README.md
- created container app env and subnet
- enable data for monitoring
- fix variables
Allow to use container app in Italy
---
> feat: Italy container app env

- src/domains/nodo-switcher/01_nodo_switcher.tf
> fix: Variable name

- src/core-itn/01_network.tf
- src/core-itn/03_monitoring.tf
- src/core-itn/99_variables.tf
- src/core-itn/README.md
- src/core-itn/env/dev/terraform.tfvars
- src/domains/nodo-common/README.md
- added app insigths and law into italy
- removed subnets not more used
Have monitoring in italy
---
> feat: Monitoring in Italy

- src/domains/afm-app/api/marketplace-service/v1/_openapi.json.tpl
> chore: Upd open-api market-place BE

- src/domains/ecommerce-app/04_apim_ecommerce_mock.tf
> fix(ecommerce): Enabled subscription key for gec and node forwarder mock

- src/domains/bizevents-app/api/bizevents-helpdesk/v1/_openapi.json.tpl
- src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
- src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
Update all biz openapi
Needed to refresh biz openapi
---
> chore: PAGOPA-1681 updating biz openapi

- src/domains/gps-app/api/gpd-upload-service/v1/_base_policy.xml
- src/elk-monitoring/05_elastic_stack.tf
Add `pagopa-gpd-upload` in `elastic_stack.dedicated_log_instance_name`
Update gpd-upload API rate-limt 
Dedicated log on ELK for `pagopa-gpd-upload` chart
---
> feat(gpd-upload): Add instance to ELK [PAGOPA-1595]

- src/domains/aca-app/api/aca/v1/_base_policy.xml.tpl
- src/domains/aca-app/api_product/_base_policy.xml
> chore: Remove base include from ACA

- src/domains/pay-wallet-app/00_monitor.tf
- src/domains/pay-wallet-app/99_locals.tf
- src/domains/pay-wallet-app/99_variables.tf
- src/domains/pay-wallet-app/README.md
- src/domains/pay-wallet-app/env/itn-dev/terraform.tfvars
- src/domains/pay-wallet-common/00_monitor.tf
- src/domains/pay-wallet-common/02_azdo.tf
- src/domains/pay-wallet-common/03_storage.tf
- src/domains/pay-wallet-common/99_locals.tf
- src/domains/pay-wallet-common/99_variables.tf
- src/domains/pay-wallet-common/README.md
- src/domains/pay-wallet-common/env/itn-dev/terraform.tfvars
- changes all monitors to use the app-insight in italy
Use the App Insigth in Italy for monitoring
---
> fix(pay-wallet): App insight now is in Italy

- src/core/01_custom_roles.tf
> fix: Iac plan role permissions

- src/domains/bizevents-common/02_security.tf
- src/domains/bizevents-common/env/weu-prod/terraform.tfvars
- src/domains/fdr-app/env/weu-prod/terraform.tfvars
- src/domains/nodo-app/env/weu-prod/terraform.tfvars
- src/domains/nodo-common/env/weu-prod/terraform.tfvars
- src/domains/nodo-switcher/env/weu-prod/terraform.tfvars
> chore: Switch Hhub PROD from NS01 to NS03

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
- added secret pp-nodo-offiline-password
---
> chore: [NOD-857] Nodo added secret

- src/domains/nodo-app/00_alert_node_cfg_sync.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- added alert for SYNC dumping
---
> chore: [NOD-884] Alert node cfg sync

- src/next-core/07_azure_devops_agent.tf
- src/next-core/99_locals.tf
- src/next-core/99_variables.tf
- src/next-core/README.md
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Devops agent update. moved to next-core

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/cfg-partner/3.28.0/db.changelog-20240517000000_elenco_servizi_view.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.28.0/db.changelog-20240517010000_cdi_preferences_view.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.28.0.xml
- src/psql/nodo/liquibase/changelog/cfg/3.28.0/db.changelog-20240517000000_elenco_servizi_view.xml
- src/psql/nodo/liquibase/changelog/cfg/3.28.0/db.changelog-20240517010000_cdi_preferences_view.xml
- src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.28.0.xml
- renamed `ELENCO_SERVIZI_VIEW` to `ELENCO_SERVIZI_VIEW_MASTER`
- created `ELENCO_SERVIZI_VIEW` like `ELENCO_SERVIZI`
- renamed `CDI_PREFERENCES_VIEW to CDI_PREFERENCES_VIEW_MASTER`
- created `CDI_PREFERENCES_VIEW` like `CDI_PREFERENCES`
- needed for migration CFG schema from ORACLE to POSTGRESQL PagoPA
---
> chore: [NOD-901] Liquibase nodo - viste

- src/core/README.md
- src/domains/ecommerce-app/04_apim_ecommerce_npg_notification.tf
- src/domains/nodo-app/README.md
> feat: enable npg notification for prod

- src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
- src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
```
sh terraform.sh apply weu-dev --target=module.apim_api_gpd_api --target=module.apim_api_debt_positions_api_v1
```
---
> [PAGOPA-1744] chore(GPD): Update APIs

- src/domains/observability/05_app_forwarder.tf
- src/domains/observability/datafactory/datasets/KPI_TNSPO.json
- src/domains/observability/datafactory/pipelines/KPI_TNSPO.json
- src/domains/observability/datafactory/pipelines/KPI_TPSPO_DASPO.json
Update following tables/columns : 
```
.rename column KPI_TNSPO.OUTCOME to OUTCOME_SPO_REQ;
.alter-merge table KPI_TNSPO (OUTCOME_SPO_RESP:string);
.alter-merge table KPI_TNSPO (FAULT_CODE_SPO:string);
.alter-merge table KPI_TNSPO (FAULT_CODE_PSP:string);
```
---
> chore: PQI-72 fix

- src/core-itn/00_dns_private.tf
- src/core-itn/01_keyvault.tf
- src/core-itn/01_network.tf
- src/core-itn/02_dns_private_link.tf
- src/core-itn/10_evenhubs.tf
- src/core-itn/99_variables.tf
- src/core-itn/README.md
- src/core-itn/env/uat/terraform.tfvars
> feat: Core itn uat prod

- src/domains/bizevents-app/api/transaction-service/v1/_openapi-jwt.json.tpl
- src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
- updated transaction service openapi
- business request
---
> [PAGOPA-1763] transaction openapi

- src/domains/fdr-common/00_data.tf
- src/domains/fdr-common/02_security.tf
- src/domains/fdr-common/05_subscription_key.tf
- src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
> [NOD-905] feat: add secrets for integration tests and OpEx dashboards

- src/domains/selfcare-common/.terraform.lock.hcl
- src/domains/selfcare-common/02_security.tf
- src/domains/selfcare-common/04_app_configuration_feature.tf
> fix: Feature flags

- src/domains/printit-app/00_data.tf
- src/domains/printit-app/06_keyvault.tf
- src/domains/printit-common/03_eventhub.tf
…s and related secrets
- Introduced topics for event hub related to complete and error topics for notices
---
> feat: Introducing complete and errors notice eventhub topic [VAS-835] 

- src/domains/printit-app/06_keyvault.tf
- src/domains/printit-app/README.md
- src/domains/printit-common/03_storage_account_notices.tf
- src/domains/printit-common/10_github_identity.tf
- src/domains/printit-common/README.md
> feat: Subkey printit

- src/domains/bizevents-common/02_security.tf
- src/domains/bizevents-common/README.md
> chore: Add LstTrx KV secrets

- .devops/packer-deploy-pipelines.yml
- src/next-core/07_azure_devops_agent.tf
- src/next-core/99_variables.tf
- src/next-core/README.md
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
- src/packer/01_azure_devops_agent.tf
- src/packer/01_dns_forwarder_image.tf
- src/packer/99_variables.tf
- src/packer/README.md
- src/packer/env/dev/terraform.tfvars
- src/packer/env/prod/terraform.tfvars
- src/packer/env/uat/terraform.tfvars
> feat: Update azdo image

- src/domains/nodo-common/05_nodo_switcher.tf
- src/domains/nodo-common/README.md
- src/domains/nodo-switcher/01_nodo_switcher.tf
- src/domains/nodo-switcher/README.md
> feat: Moved nodo switcher resource group

- src/core/appgateway.tf
- src/next-core/03_apim.tf
- src/next-core/04_appgw_integration.tf
- src/next-core/99_variables.tf
- src/next-core/README.md
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Apim migration

- src/core/dns_private.tf
> fix: Updated private dns configuration for apim

- src/domains/apiconfig-common/env/weu-prod/terraform.tfvars
- src/domains/bizevents-common/env/weu-prod/terraform.tfvars
- src/domains/nodo-common/env/weu-prod/terraform.tfvars
- src/domains/shared-common/env/weu-prod/terraform.tfvars
> feat: Migrated prod redis to ha version

- src/core/99_variables.tf
- src/core/apim_nodo_services_auth_02_product.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> fix: Updated named value old apim

- src/domains/gps-app/api/gpd-upload-service/v1/_base_policy.xml
- Update `authorization_entity` variable in `apim_gpd_upload_api_v1` policy
```
sh terraform.sh apply weu-uat --target=module.apim_gpd_upload_api_v1`
```
- Authorization by `authorization_entity` 
---
> fix(gpd-upload): [PAGOPA-1789] Update authorization_entity variable

- src/core/apim_nodo_monitoring_services.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
> fix: [NOD-936] Add nodo api monitoring to apim_x_node product

- src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v1/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
Add 422 error response code to POST auth request
Add 422 error response code to POST auth request
---
> feat(ecommerce-auth-reqeust): add 422 http error code

- src/domains/checkout-app/04_apim_checkout.tf
- src/domains/checkout-app/README.md
> feat: add new product for checkout auth

- src/domains/apiconfig-app/api/apiconfig_api/v1/_openapi.json.tpl
Update openapi api config
Change needed to maintain the openapi of api-config up to date
---
> feat: update apiconfig openapi

- src/core/apim_nodo_services_auth_02_product.tf
- src/core/appgateway.tf
- src/core/dns_private.tf
- src/core/env/dev/terraform.tfvars
- src/next-core/03_apim.tf
- src/next-core/api/base_policy.tpl
- src/next-core/env/dev/terraform.tfvars
> feat: Dev end apim migration

- .devops/disaster-recovery.yml
> feat: Fix pipeline

- src/next-core/00_network.tf
- src/next-core/01_network.tf
- src/next-core/01_network_dns_private.tf
> feat: Fixed replica vnet peering and postgres routing

- src/core/env/uat/terraform.tfvars
See https://github.com/pagopa/pagopa-infra/pull/1785
---
> chore: Switch-UAT-API-Config-Cache-Oracle-To-Postgres

- src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
- Add a complete API in GPD v2 internal API
`sh terraform.sh apply weu-dev --target=module.apim_api_gpd_api_v2`
- Autogen client e.g. Dismissione Wisp Client
---
> feat: Update GPD internal API

- src/domains/ecommerce-app/api/ecommerce-checkout/v1/_methods_testing_policy.xml.tpl
> fix: testing check

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/cfg-partner/3.28.0/db.changelog-20240605000000_update_float4.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.28.0.xml
- src/psql/nodo/liquibase/changelog/cfg/3.28.0/db.changelog-20240605000000_update_float4.xml
- src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.28.0.xml
> fix: [NOD-948] fix float fields postgres

- src/domains/fdr-common/03_postgresql_replica.tf
- src/domains/gps-common/03_postgresql_replica.tf
- src/domains/nodo-common/03_postgresql_replica.tf
> feat: Fix postgres ve delete command

- src/aks-leonardo/03_aks_0.tf
- src/aks-leonardo/03_aks_storage.tf
- src/core-itn/env/prod/terraform.tfvars
- updated aks module to support oms agent flags correctly
- core-itn: added ddos protection for vnet
- minor fix
Setup AKS Leonardo to be used in Italy PROD
---
> feat: AKS-Leonardo on Prod in Italy

- src/core/env/uat/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Switched to new apim

- src/domains/pay-wallet-common/.terraform.lock.hcl
- src/domains/pay-wallet-common/00_monitor.tf
- src/domains/pay-wallet-common/01_network.tf
- src/domains/pay-wallet-common/02_security.tf
- src/domains/pay-wallet-common/03_cosmosdb.tf
- src/domains/pay-wallet-common/03_redis.tf
- src/domains/pay-wallet-common/03_storage.tf
- src/domains/pay-wallet-common/80_monitoring.tf
- src/domains/pay-wallet-common/99_main.tf
- src/domains/pay-wallet-common/env/itn-prod/terraform.tfvars
- src/domains/pay-wallet-common/env/itn-uat/terraform.tfvars
- upgrated azurerm to v3.106.1
- fix private link 
- disable monitoring module
fix private link for storage account
---
> fix: Pay-wallet storage private link 

- src/next-core/04_appgw_integration.tf
> feat: Added prf listener uat

- src/domains/selfcare-common/04_app_configuration_feature.tf
- src/domains/selfcare-common/10_github_identity.tf
- src/domains/selfcare-common/README.md
🎏 new `payment notice` flag
---
> feat: Flag payment notices

- src/core/dns_private.tf
> feat: Fix prf dns

- src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI.json
- src/domains/observability/datafactory/pipelines/KPI_FDR_IMPORT_ESITI_Manuale.json
> fix IUR on modType=1

- src/aks-leonardo/00_key_vault.tf
- src/aks-leonardo/03_aks_0.tf
- src/aks-leonardo/80_vm_debug.tf
- src/aks-leonardo/99_locals.tf
- src/aks-leonardo/99_variables.tf
- src/aks-leonardo/README.md
- src/aks-leonardo/env/itn-dev/terraform.tfvars
- src/aks-leonardo/env/itn-prod/terraform.tfvars
- src/aks-leonardo/env/itn-uat/terraform.tfvars
- **created vm debug in italy**
- **pre-commit fixs**
Allow to use a Debug vm to understand problems with network
---
> feat: Italy vm for debug purpose

- src/core/env/uat/terraform.tfvars
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Migrated uat apim

- src/core/env/uat/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Switched to old apim v2 uat

- src/domains/pay-wallet-app/env/itn-prod/backend.tfvars
- src/domains/pay-wallet-app/env/itn-prod/terraform.tfvars
- src/domains/pay-wallet-common/03_storage.tf
- src/domains/pay-wallet-common/env/itn-prod/terraform.tfvars
- src/domains/pay-wallet-common/env/itn-uat/terraform.tfvars
The goal of this PR is to add pay-wallet configuration for PROD
---
> feat(pay-wallet-prod): CHK-2941 create resources for prod env

- src/domains/wallet-app/api/npg-notifications/v1/_base_policy.xml.tpl
Add check against required fields performing wallet `POST notifications`
This modification is needed in order to make wallet b.e. process notification successfully also in case of missing required fields from NPG and put wallet in `ERROR` state instead of leaving in in `VALIDATION_REQUESTED` ones.
When `details` is not valued wallet is put in `ERROR` status by wallet-be performing transition to final status.
Look [here](https://github.com/pagopa/pagopa-wallet-service/blob/cb10eaf72e9b7e4c8e61fbd0cd9e0a37d4335e2f/src/main/kotlin/it/pagopa/wallet/services/WalletService.kt#L833-L842) for CARDS onboarding and [here](https://github.com/pagopa/pagopa-wallet-service/blob/cb10eaf72e9b7e4c8e61fbd0cd9e0a37d4335e2f/src/main/kotlin/it/pagopa/wallet/services/WalletService.kt#L854-L864) for Paypal ones …
> fix(NPG-POST-notification): no details for missing required info

- src/domains/pay-wallet-app/.terraform.lock.hcl
- src/domains/pay-wallet-app/04_apim_io_payment_wallet.tf
- src/domains/pay-wallet-app/api_product/_base_policy.xml
> fix: minor fixes for pay wallet app

- src/core/node_forwarder.tf
Increase Node Forwarder `CONN_TIMEOUT` variable for UAT env
Node forwarder is used for Redirect integration that have slow response times due to the usage of PSP vpn's that make api call slower than 8 seconds
---
> chore(node-forwarder): increase uat timeout

- src/domains/bizevents-app/api/transaction-service/v1/_openapi-jwt.json.tpl
- src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
- src/domains/shared-app/api/session-wallet/v1/_fragment_policiy_chk_jwt.tpl.xml
> chore: Upd lst trx IO

- src/core/natgateway.tf
> chore: Change threshold SNATConnectionCount alert

- src/domains/pay-wallet-app/99_locals.tf
> fix: pay-wallet hostname internal

- src/domains/pay-wallet-app/api/payment-wallet/v1/_get_wallets_by_user_and_walletId_with_pm.xml.tpl
- src/domains/wallet-app/api/payment-wallet/v1/_get_wallets_by_user_and_walletId_with_pm.xml.tpl
- add businessName for wallet by id (with Payment Manager)
---
> feat: add business name wallet with PM

- src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
- src/domains/gps-app/api/gpd_api/v1/_openapi.json.tpl
- src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
- Update OpenAPI to `0.11.36` version of GPD-Core
target apply
```
sh terraform.sh apply weu-uat --target=module.apim_api_debt_positions_api_v1 --target=module.apim_api_debt_positions_api_v2 --target=module.apim_api_gpd_api_v1 --target=module.apim_api_gpd_api_v2
```
related to https://github.com/pagopa/pagopa-debt-position/pull/244
---
> chore(GPD): Update OpenAPI

- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> chore: Switch PROD API-Config-Cache Oracle-To-Postgres

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
> chore: add secrets for wisp

- src/domains/pay-wallet-app/04_apim_io_payment_wallet.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet_for_ecommerce.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet_migrations.tf
- src/domains/pay-wallet-app/99_locals.tf
- src/domains/pay-wallet-app/env/itn-dev/terraform.tfvars
- src/domains/pay-wallet-app/env/itn-uat/terraform.tfvars
- src/domains/wallet-app/04_apim_payment_wallet.tf
- src/domains/wallet-app/04_apim_payment_wallet_for_ecommerce.tf
- src/domains/wallet-app/04_apim_payment_wallet_migrations.tf
- src/domains/wallet-app/README.md
Move old wallet api to new domain, using again the old service.
Switch to itn is planned for future steps
---
> feat(wallet):  CHK-2936 move old wallet api to new domain (old service)

- src/domains/pay-wallet-common/00_dns_public.tf
- src/domains/pay-wallet-common/05_wallet_cdn.tf
- src/domains/pay-wallet-common/99_variables.tf
- src/domains/pay-wallet-common/README.md
- src/domains/pay-wallet-common/env/itn-dev/terraform.tfvars
- src/domains/pay-wallet-common/env/itn-prod/terraform.tfvars
- src/domains/pay-wallet-common/env/itn-uat/terraform.tfvars
- src/domains/wallet-common/05_wallet_cdn.tf
- src/domains/wallet-common/README.md
> feat(pay-wallet): CHK-2947 import payment-wallet dns and CDN in pay-wallet domain

- src/domains/gps-common/10_github_identity.tf
> chore: Add identity federations to pagopa-gpd-payments

- src/domains/shared-app/04_apim_io_wallet_session.tf
- src/domains/shared-app/README.md
- src/domains/shared-app/api/session-wallet/v1/_base_policy.xml.tpl
- src/domains/shared-app/api/session-wallet/v1/_fragment_policiy_chk_jwt.tpl.xml
- src/domains/shared-common/.terraform.lock.hcl
- src/domains/shared-common/02_security.tf
- src/domains/shared-common/README.md
> chore: Generate JWT_SIGNATURE_KEY for session shared

- src/domains/shared-app/04_apim_io_wallet_session.tf
> fix: Session wallet

- src/domains/bizevents-app/api/transaction-service/v1/_base_policy-jwt.xml
> chore: Add fix policy listTrx jwt IO

- src/domains/pay-wallet-app/04_apim_io_payment_wallet.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet_for_ecommerce.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet_migrations.tf
Switch wallet b.e. to the itn ones
Switch wallet b.e. to the itn ones
---
> chore(wallet): use itn backend

- src/domains/pay-wallet-app/env/itn-prod/terraform.tfvars
> feat: enable migration for pay-wallet prod

- src/domains/wallet-app/api/npg-notifications/v1/_base_policy.xml.tpl
trigger infra release through PR
trigger infra release through PR
---
> feat(io-api-release): trigger release

- src/domains/bizevents-app/api/transaction-service/v1/_base_policy-jwt.xml
- src/domains/pay-wallet-app/api/io-payment-wallet/v1/_get_payment_methods.xml.tpl
- src/domains/shared-app/04_apim_io_wallet_session.tf
- src/domains/shared-app/README.md
- src/domains/shared-app/api/session-wallet/v1/_fragment_policiy_chk_token.tpl.xml
Add fragment to check pm token when api work as pm proxy
- Update transaction list to check pm when ecommerce vs pm is enabled
- Update get all payment methods for app IO including fragment
---
> feat(shared-session) CHK-2963: check session for pm token in biz events transactions list

- src/core/env/prod/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
> feat: Upgrade apim prod

- src/next-core/03_apim.tf
> feat: Updated apim module to fix autoscale

- .github/workflows/static_analysis_pr.yml
> feat: Fix pr static analysis

- src/core/99_locals.tf
- src/core/99_variables.tf
- src/core/README.md
- src/core/api/nodopagamenti_api/nodoServices/web-bo-history-on-prem/v1/_base_policy.xml
- src/core/api/nodopagamenti_api/nodoServices/web-bo-history/v1/_base_policy.xml
- src/core/api/nodopagamenti_api/nodoServices/web-bo-history/v1/_base_policy_dev.xml
- src/core/api/nodopagamenti_api/nodoServices/web-bo-on-prem/v1/_base_policy.xml
- src/core/api/nodopagamenti_api/nodoServices/web-bo/v1/_base_policy.xml
- src/core/api/nodopagamenti_api/nodoServices/web-bo/v1/_base_policy_dev.xml
- src/core/api/payment_manager_api/admin-panel/_base_policy.xml.tpl
- src/core/apim_nodo_3p_services.tf
- src/core/apim_nodo_3p_services_dev.tf
- src/core/apim_payment_manager.tf
- src/core/appgateway.tf
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
> feat: Added temp address for web-bo api

- src/domains/printit-common/03_storage_account_institutions.tf
- Introducing logo container
- Updated institutions container privacy access
---
> feat: add logo container

- src/domains/gps-app/04_apim_gpd_payments.tf
- src/domains/gps-app/99_variables.tf
- src/domains/gps-app/api/payments-service/v1/soap/wisp-paSendRTV2.xml
- src/domains/gps-app/env/weu-dev/terraform.tfvars
- src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-receipt-ko.xml
> chore: [PAGOPA-1878] paSendRTV2 outbound policy for WISP dismantling

- src/domains/ecommerce-app/04_apim_ecommerce_redirect_outcome.tf
Enable redirect outcome url
Enable redirect outcome url
---
> feat: enable redirect outcome

- src/aks-leonardo/env/itn-uat/terraform.tfvars
> feat: Upgrade aks itn 1.29

- src/domains/shared-app/01_app_service_pdf_engine.tf
- src/domains/shared-app/04_apim_pdf_engine.tf
> feat: Pdf engine non-ha dismission prod

- src/core/apim_node_forwarder.tf
- src/core/env/dev/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/core/node_forwarder.tf
> feat: Cleaned node forwarder non-ha prod

- src/core/appgateway.tf
- src/core/env/prod/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
> feat: Migrated to upgraded apim, upload listener

- src/aks-leonardo/env/itn-prod/terraform.tfvars
- src/aks-leonardo/env/itn-uat/terraform.tfvars
- PROD AKS 1.29 + Keda 1.24.0
- UAT sku to Standard
Allow to have the last version of aks to be under support, and UAT now have a sku Standard
---
> feat(aks leonardo): Upgrated PROD to v1.29 + UAT sku standard

- src/next-core/03_apim.tf
- src/next-core/README.md
> feat: Upgraded apim module

- src/core/README.md
- src/core/redis_cache.tf
> feat: Cleanup apim ext cache

- src/domains/pay-wallet-app/api/npg-notifications/v1/_base_policy.xml.tpl
Depends on https://github.com/pagopa/pagopa-wallet-service/pull/168
Add JWT token validation for wallet onboarding
Add JWT token validation for wallet onboarding
---
> Chk 2980 wallet npg post notification jwt validation

- src/domains/ecommerce-app/04_apim_ecommerce_io_v2.tf
- src/domains/ecommerce-app/api/ecommerce-io/v2/_get_wallets_by_user_with_pm.xml.tpl
> fix(get wallets): CHK-2989 enabling applications ecommerce api vs pm

- src/core-itn/20_container_registry.tf
- src/domains/printit-app/01_app_service_pdf_engine.tf
- used itn container registry
- enabled `admin_enabled`
---
> feat: Italian container registry

- .devops/nodo-db-schema-pipelines.yml
- src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
> feat: Create cfg usr read

- src/domains/ecommerce-app/04_apim_ecommerce_webview.tf
> chore: enable ecommerce webiview in prod

- src/domains/bizevents-app/04_apim_bizevents.tf
- src/domains/bizevents-app/99_locals.tf
- src/domains/bizevents-app/README.md
- src/domains/bizevents-app/api/transaction-service/v1/_openapi-jwt.json.tpl
- src/domains/bizevents-app/api/transaction-service/v1/_openapi.json.tpl
- Added optional filters for isPayer and isDebtor
- Added sorting for transactionDate ASC and DESC
- new business request
---
> feat: [PagoPa-1799] - new filter api

- src/domains/nodo-app/04_apim_mock_ec.tf
- Update count to APIM module and resources
```
sh terraform.sh apply weu-uat --target=module.apim_api_mock_ec_api_v1 --target=azurerm_api_management_api_version_set.api_receipt_for_ndp_api
```
- Enable Mock-EC in UAT environment
---
> feat(nodo): Enable mock-ec API [PAGOPA-1897]

- src/domains/bizevents-app/env/weu-prod/terraform.tfvars
> fix: Cfg biz-jwt-pdv

- CODEOWNERS
> feat: Defined next-core codeowners

- src/core/api/nodopagamenti_api/nodoPerPM/v2/wisp-closepayment.xml
- src/core/api/payment_manager_api/pm-per-nodo/v2/wisp-sendpaymentresult.xml
- src/domains/nodo-app/api/nodopagamenti_api/nodoPerPM/v2/wisp-closepayment.xml
- src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-disable-payment-token-timer.xml
- src/domains/nodo-app/api/nodopagamenti_api/wisp/wisp-sendpaymentresult.xml
> fix: [PAGOPA-1906] Fix closePayment and sendPaymentResult

- src/core/README.md
- src/core/postgresql.tf
> feat: Removed unused resources

- src/domains/bizevents-common/10_github_identity.tf
- src/next-core/08_natgateway.tf
> chore: Add-fed-indentity-biz + change-natgw-alert

- src/domains/pay-wallet-app/api/payment-wallet-migrations-for-cstar/v1/_base_policy.xml.tpl
> feat: increase rate limit interval

- src/core/README.md
- src/core/apim.tf
- src/core/apim_donations.tf
- src/core/apim_node_forwarder.tf
- src/core/apim_nodo_3p_services.tf
- src/core/apim_nodo_3p_services_dev.tf
- src/core/apim_nodo_monitoring_services.tf
- src/core/apim_nodo_services_09_nodo_per_pm.tf
- src/core/apim_nodo_services_dev.tf
- src/core/apim_payment_manager.tf
- src/core/apim_payment_transactions_gateway.tf
- src/core/apim_tkm.tf
- src/next-core/03_apim.tf
- src/next-core/README.md
> feat: Apim custom domain migration

- src/core/README.md
- src/core/apim.tf
- src/next-core/03_apim_monitor.tf
- src/next-core/README.md
> feat: Apim monitor migration

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-common/env/weu-prod/terraform.tfvars
> chore: [PAGOPA-1908] Nodo common for WISP

- src/domains/pay-wallet-app/04_apim_io_payment_wallet.tf
- src/domains/pay-wallet-app/README.md
> chore: Add terraform_data for apim policy

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-common/env/weu-prod/terraform.tfvars
- change cosmos configuration in prod
---
> fix: [PAGOPA-1908] Nodo common fix WISP cosmos

- src/domains/nodo-app/env/weu-prod/terraform.tfvars
> feat: Add dr oracle subnet

- src/core/data.tf
- src/core/env/prod/terraform.tfvars
> feat: Aligned backup storage configuration

- src/core/payment_manager_monitor.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
> chore: Core fix availability pm restapi cd

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
> chore: [PAGOPA-1908] Nodo secret iuv for WISP

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/wfesp/db.changelog-master-3.26.0.xml
> chore: [PAGOPA-1960] Fix WFESP liquibase

- src/domains/pay-wallet-common/03_cosmosdb.tf
- src/domains/pay-wallet-common/env/itn-dev/terraform.tfvars
- src/domains/pay-wallet-common/env/itn-uat/terraform.tfvars
Add `updateDate` to pay wallet cosmos indexes
---
> update index pay wallet. Add update date.

- src/domains/shared-app/env/weu-prod/terraform.tfvars
- src/domains/shared-app/env/weu-uat/terraform.tfvars
> today is a good day: enable payment-wallet with NPG

- .devops/pay-wallet-deploy-pipelines.yml
- src/domains/pay-wallet-common/env/itn-dev/terraform.tfvars
- src/domains/pay-wallet-common/env/itn-uat/terraform.tfvars
> fix: CHK-2996 pipeline deploy name for pay-wallet

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-app/env/weu-uat/terraform.tfvars
> chore: Update WISP whitelist in uat

- src/core/README.md
- src/core/buyerbanks_function.tf
- src/core/monitor.tf
- src/core/node_forwarder.tf
- src/core/outputs.tf
- src/core/payment_manager_monitor.tf
- src/next-core/00_key_vault.tf
- src/next-core/00_monitor.tf
- src/next-core/02_monitor.tf
- src/next-core/03_apim.tf
- src/next-core/03_tools_cae.tf
- src/next-core/04_appgw.tf
- src/next-core/04_appgw_integration.tf
- src/next-core/05_messages.tf
- src/next-core/06_node_forwarder.tf
- src/next-core/08_natgateway.tf
- src/next-core/09_assets_cdn_platform.tf
- src/next-core/99_variables.tf
- src/next-core/README.md
- src/next-core/env/dev/terraform.tfvars
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Monitor migration

- src/next-core/02_monitor.tf
> feat: Disabled asset cdn tests

- src/domains/printit-app/04_apim_notice_service.tf
product apim `Stampa Avvisi external` published 
---
> fix(printit): Product Apim Published

- src/domains/nodo-app/01_aks.tf
> feat: Restored node pool configuration

- src/domains/nodo-app/00_alert_wisp_dismantling.tf
- src/next-core/02_monitor.tf
> [PAGOPA-1913] fix(nodo-app): Update WISP dismantling alerts

- src/domains/nodo-app/00_alert_wisp_dismantling.tf
> [PAGOPA-1913] fix(nodo-app): Update WISP dismantling alerts

- src/next-core/02_monitor.tf
- src/next-core/99_variables.tf
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: Cleaned web tests

- src/domains/ecommerce-app/api/ecommerce-webview/v1/_openapi.json.tpl
> fix: REDIRECT as ecommerce-fe gateway

- src/domains/nodo-app/env/weu-uat/terraform.tfvars
- Added `Comune di Albairate` EC for WISP dismantling
These changes are required in order to add the new EC on WISP dismantling
---
> [PAGOPA-1075] feat: add Comune di Albairate in WISP dismantling

- src/domains/bizevents-app/04_apim_bizevents.tf
- src/domains/bizevents-app/README.md
- src/domains/bizevents-common/02_security.tf
- src/domains/bizevents-common/README.md
- src/domains/bizevents-secrets/secret/weu-dev/noedit_secret_enc.json
- src/domains/bizevents-secrets/secret/weu-uat/noedit_secret_enc.json
> feat: Add params 4 perftest biz

- src/core/99_variables.tf
- src/core/README.md
- src/core/env/dev/terraform.tfvars
- src/core/env/prod/terraform.tfvars
- src/core/env/uat/terraform.tfvars
- src/core/outputs.tf
- src/next-core/07_container_registry.tf
- src/next-core/README.md
> feat: Migrated container registry

- src/next-core/06_node_forwarder.tf
- Update node-forwarder-availability alert 
- When the request traffic is low there are many false positive
---
> [PAGOPA] feat: Update node-forwarder-availability alert

- src/domains/selfcare-common/02_security.tf
> chore: Add perms-seflfcare-kv-dev-uat

- src/domains/afm-app/04_apim_afm_calculator.tf
- src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml
The involved resources are
- `/Users/andreaferracci/projects/pagopa-infra/src/domains/afm-app/api/calculator-service/node/v1/_base_policy.xml` (mock conditions modified, added one bundle to a specific scenario)
- `/Users/andreaferracci/projects/pagopa-infra/src/domains/afm-app/04_apim_afm_calculator.tf` (named value added)
In order to allow the NDP integration test execution, some modification has been made to the apim base policy.
---
> feat: [PQ-89] - ndp integration test enhancement

- src/domains/nodo-app/env/weu-prod/terraform.tfvars
Add : 
- 02002380224-02695640421_01 Trentino Riscossioni/e-SED Società Cooperativa https://config.platform.pagopa.it/creditor-institutions/02002380224
- 03122360153-08543640158_01 Comune di Corbetta/APKAPPA S.R.L. https://config.platform.pagopa.it/creditor-institutions/03122360153
- 12621570154-00053810149_01 Universita' degli Studi di Milano - Bicocca/Banca Popolare di Sondrio https://config.platform.pagopa.it/creditor-institutions/12621570154
---
> feat: Add new EC/station to DismissioneWISP

- src/domains/nodo-app/env/weu-prod/terraform.tfvars
> feat: Remove wispdism step3

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
> chore: secrets regarding ecommerce for WISP

- src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-activate-outbound.xml
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- `application/xml` is not a valid content-type. set `text/xml` instead
---
> fix: WFESP content-type

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-app/env/weu-uat/terraform.tfvars
> chore: Enable WISP for all [UAT]

- src/next-core/03_apim_management_groups.tf
- src/next-core/03_apim_management_tech_usr.tf
- src/next-core/README.md
> chore: Add apim usr grp tech pagopa-core

- src/domains/ecommerce-app/api/ecommerce-checkout/v1/_methods_testing_policy.xml.tpl
The goal of this PR is to enable Satispay for checkout / eCommerce
---
> feat: enable Satispay for checkout

- src/domains/ecommerce-common/00_alerts.tf
- src/domains/ecommerce-common/03_storage.tf
- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
Due to WISP redirection eCommerce need more database resources.
- increase eCommerce max throughput to 15k RUs
- increase transient queue alert threshold to 10_000 messages
- increase latency threshold for io availability alert
---
> feat(ecommerce): increase ecommerce max throughput to 15k

- src/domains/bizevents-app/api/bizevents-service/v1/_base_policy.xml
- src/domains/bizevents-app/api/bizevents-service/v1/_openapi.json.tpl
> chore: Fix ec biz service

- src/domains/nodo-common/00_monitor.tf
- src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
- src/domains/nodo-common/99_locals.tf
- src/domains/nodo-common/README.md
> chore: Add alert cosmos_wisp_normalized_ru_exceeded

- src/domains/bizevents-app/04_apim_lap.tf
> chore: Fix test api biz lap

- src/domains/receipts-app/04_apim_receipts.tf
Added `apim_api_receipts_helpdesk_api_v1` to `technical_support_api` 
This change is necessary in order to centralize all the help-desk apis under a unique product
---
> feat: add receipt pdf technical support api to assistenza product

- src/domains/bizevents-app/04_apim_bizevents.tf
- Added BizEvent help desk api to product Assistenza 
This change allows Assistenza team to access the biz help desk api 
---
> feat: add biz event service helpdesk api to assistenza product

- .devops/base-code-review-pipelines.yml
- .devops/base-deploy-pipelines.yml
- .devops/next-core-secrets-code-review-pipelines.yml
- .devops/next-core-secrets-deploy-pipelines copy.yml
- .devops/next-core-secrets-deploy-pipelines.yml
- src/next-core/07_azure_devops_agent.tf
Signed-off-by: Fabio Felici <fabio.felici@pagopa.it>
This change was made to add next-core-secrets in the azure DevOps process, the deployment method was defined as a new installation performed on the repositories of recent projects that make the maintenance more stable and effective, it will follow as we refactor the existing pipelines in this section to fit the new method.
- Add next-core-secrets on code review process
- Install new pipeline definition method
Refer PR: pagopa/pagopa-azure-devops#361
---
> feat: [PAYMCLOUD-83] New pipeline code review next core secrets with refactor

- src/domains/checkout-app/04_apim_checkout.tf
- src/domains/checkout-app/README.md
Disable verbose apim loggin for API dedicated to IO and SEND flow (APIs that will soon be replaced by eCommerce)
---
> chore: Disable verbose logging checkout API

- src/domains/checkout-app/05_checkout_function.tf
> chore: refactor alert pagopa-proxy to use apim data

- src/next-core/03_apim_backup.tf
> fix: Enabled public access for backup SA

- src/domains/checkout-app/05_checkout_fe.tf
> feat: add x-frame-options waiting csp enabled for checkout

- src/domains/afm-common/10_github_identity.tf
> chore: Add gh identity pagopa-afm-fee-reporting-service

- src/next-core/99_main.tf
- src/next-core/env/prod/terraform.tfvars
- src/next-core/env/uat/terraform.tfvars
> feat: remove softlab and add SMI to whitelist IP

- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240517000000_elenco_servizi_view.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240517010000_cdi_preferences_view.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240527000000_update_elenco_servizi_view_master.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240605000000_update_float4.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240711000000_add_field_aca.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240711000001_add_field_standin.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240718000000_new_manutenzione_stazioni_table.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240910000000_add_is_payment_options_enabled_field.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/3.31.0/db.changelog-20240910000001_add_rest_endpoint_field.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.31.0.xml
- src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.31.0.xml
> fix: 3.31.0 updated for cfg-partner with missing fields

- src/domains/selfcare-common/.terraform.lock.hcl
- src/domains/selfcare-common/02_azdo.tf
- src/domains/selfcare-common/04_app_configuration_feature.tf
- src/domains/selfcare-common/README.md
Added selfcare backoffice feature flags:
- Flag to hide/show the REST endpoint section in Station's detail/add/edit pages
- Flag to hide/show the Payment Options service section in Station's detail/add/edit pages
---
> feat: Add new feature flags for backoffice's Stations

- src/domains/paymentoptions-app/05_subkey.tf
- src/domains/paymentoptions-app/06_keyvault.tf
- src/domains/paymentoptions-app/README.md
> feat: Add opt key 4test

- src/domains/paymentoptions-app/00_data.tf
- fixed key vault api config cache subkey value
---
> fix: api-config-cache subkey

- src/domains/gps-app/02_security.tf
- src/domains/gps-app/04_apim_gpd_core.tf
- src/domains/gps-app/04_apim_payments_pull.tf
- src/domains/gps-app/README.md
> add: Cfg perf test ppull

- src/domains/gps-app/04_apim_gpd_core.tf
- src/domains/gps-app/04_apim_payments_pull.tf
> add: Fix perf-test-env-paymentopt

- src/domains/aca-app/api/aca/v1/_openapi.json.tpl
Updating openapi for aca service
Needed in order to make the openapi compliant with the SANP
---
> PAGOPA-2127 removing company name from input

- src/domains/gps-app/02_security.tf
- src/domains/gps-app/04_apim_gpd_core.tf
- src/domains/gps-app/04_apim_payments_pull.tf
- src/domains/gps-app/README.md
> feat: Add cfg pert test ppull for prod

- .devops/aca-code-review-pipelines.yml
- .devops/apiconfig-code-review-pipelines.yml
- .devops/canoneunico-code-review-pipelines.yml
- .devops/mock-code-review-pipelines.yml
- .devops/observability-code-review-pipelines.yml
- .devops/qi-code-review-pipelines.yml
- .devops/qi-deploy-pipelines.yml
- .devops/receipts-code-review-pipelines.yml
- .devops/receipts-deploy-pipelines.yml
> fix: Pipeline template reference

- src/next-core/01_custom_roles.tf
> feat: Added apim secret reader permission

- src/domains/observability/.terraform.lock.hcl
- src/domains/observability/03_eventhub_msg.tf
> chore: Fix evh observability to italy name

- src/domains/observability/env/dev/terraform.tfvars
- src/domains/observability/env/prod/terraform.tfvars
- src/domains/observability/env/uat/terraform.tfvars
Added an event hub for payment wallet's events
---
> feat: [CHK-3292] add payment wallet eventhub

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.30.0.xml
- src/psql/nodo/liquibase/changelog/cfg-partner/db.changelog-master-3.31.0.xml
- added version to XML of 3.31 main file of cfg-partner
---
> fix: [PAGOPA-2304] Fix liquibase cfg-partner

- src/domains/gps-app/README.md
- src/domains/gps-app/api/gpd_api/debt-position-services/v1/_openapi.json.tpl
- src/domains/gps-common/terraform.sh
`sh terraform.sh apply weu-<env> -target=module.apim_api_debt_positions_api_v1`
---
> chore(gpd): remove pull flag from swagger

- .devops/nodo-db-schema-pipelines.yml
> feat: Modify user partitions

- .devops/nodo-db-schema-pipelines.yml
> feat: Paymcloud 118 partition scheduler fix

- src/core/api/nodopagamenti_api/monitoring/v1/_base_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodeForIO/v1/_base_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodeForPa/v1/_base_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodeForPsp/v1/_base_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodoPerPM/v1/_add_v1_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodoPerPM/v1/_base_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodoPerPM/v2/_base_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodoPerPa/v1/_base_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodoPerPsp/v1/_base_policy.xml.tpl
- src/core/api/nodopagamenti_api/nodoPerPspRichiestaAvvisi/v1/_base_policy.xml.tpl
- src/domains/apiconfig-common/02_security.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/next-core/03_apim_named_values.tf
- src/next-core/api/nodopagamenti_api/monitoring/v1/_base_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodeForIO/v1/_base_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodeForPa/v1/_base_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodeForPsp/v1/_base_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodeForPsp/v1/_base_policy_api_test.xml.tpl
- src/next-core/api/nodopagamenti_api/nodoPerPM/v1/_add_v1_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodoPerPM/v1/_base_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodoPerPM/v2/_base_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodoPerPa/v1/_base_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodoPerPsp/v1/_base_policy.xml.tpl
- src/next-core/api/nodopagamenti_api/nodoPerPspRichiestaAvvisi/v1/_base_policy.xml.tpl
```
CORE
sh terraform.sh apply <env> \
-target=module.apim_nodo_monitoring_api \
-target=azurerm_api_management_api_policy.apim_node_for_io_policy_ndp \
-target=azurerm_api_management_api_policy.apim_node_for_io_policy_auth \
-target=azurerm_api_management_api_policy.apim_node_for_pa_policy_auth \
-target=azurerm_api_management_api_policy.apim_node_for_psp_policy \
-target=azurerm_api_management_api_policy.apim_node_for_psp_policy_auth \
-target=azurerm_api_management_api_operation_policy.close_payment_api_v1 \
-target=azurerm_api_management_api_operation_policy.parked_list_api_v1 \
-target=module.apim_nodo_per_pm_api_v1 \
-target=module.apim_nodo_per_pm_api_v1_dev \
-target=module.apim_nodo_per_pm_api_v2 \
-target=azurerm_api_management_api_policy.apim_nodo_per_pa_policy \ …
```
> chore: [PAGOPA-2264] Fix cache and prf policies

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-common/01_network.tf
- src/domains/nodo-common/03_cosmosdb_wisp_converter.tf
- src/domains/nodo-common/99_variables.tf
- src/domains/nodo-common/env/weu-dev/terraform.tfvars
- src/domains/nodo-common/env/weu-prod/terraform.tfvars
- src/domains/nodo-common/env/weu-uat/terraform.tfvars
- src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
> feat: [PAGOPA-2212] introduced report generation for D-WISP

- src/domains/bizevents-app/04_apim_bizevents.tf
- src/domains/bizevents-app/04_apim_lap.tf
> feat : Add published 2 `bizevent-lap` and `bizevent-transactions` apim product

- src/domains/printit-app/.terraform.lock.hcl
- src/domains/printit-app/01_app_service_pdf_engine.tf
- src/domains/printit-app/99_variables.tf
- src/domains/printit-app/README.md
- src/domains/printit-app/env/itn-dev/terraform.tfvars
- src/domains/printit-app/env/itn-prod/terraform.tfvars
- src/domains/printit-app/env/itn-uat/terraform.tfvars
> feat: PAYMCLOUD-129 disabled ha app service in uat

- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/README.md
> chore: PPABV-51 new secret for ecommerce testing

- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
> fix: revert increase ru ecommerce

- src/domains/ecommerce-app/api/ecommerce-checkout/v1/_methods_testing_policy.xml.tpl
Add RICO to enabled payment methods
Add RICO to enabled payment methods
---
> feat: add RICO to enabled payment method codes

- src/next-aks/01_velero.tf
- src/next-aks/README.md
> chore: Updated velero module

- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
- increase `max_throughput` for eCommerce pagoPA CosmosDB
The goal of this PR is to increase `max_throughput` for eCommerce pagoPA CosmosDB according traffic from "dismissione wisp"
---
> chore: increase ecommerce RU

- src/next-core-secrets/secret/dev/noedit_secret_enc.json
- src/next-core-secrets/secret/prod/noedit_secret_enc.json
- src/next-core-secrets/secret/uat/noedit_secret_enc.json
> feat: Added github runner job pat

- src/domains/bizevents-common/02_security.tf
> feat: Add grant 2 dev kv-biz

- src/aks-platform/99_locals.tf
Description:
- Revised the alert descriptions to be more consistent with module names
- Adjusted alert severity, window durations, and evaluation frequencies for improved monitoring accuracy and responsiveness
This change is necessary to enhance the monitoring system by ensuring alert descriptions align with module names and adjusting alert settings for better accuracy.
---
> chore: [PAYMCLOUD-174] Update alert descriptions and configurations

- src/domains/apiconfig-app/.terraform.lock.hcl
- src/domains/apiconfig-app/02_namespace.tf
- src/domains/apiconfig-app/04_apim_api_apiconfig-cache-node-nexi.tf
- src/domains/apiconfig-app/04_apim_api_apiconfig-cache-node.tf
- src/domains/apiconfig-app/04_apim_api_apiconfig-cache-replica-node.tf
- src/domains/apiconfig-app/04_apim_api_config.tf
- src/domains/apiconfig-app/04_apim_product_apiconfig-cache.tf
- src/domains/apiconfig-app/04_apim_product_apiconfig-selfcare-integration.tf
- src/domains/apiconfig-app/05_aks_middleware_tools.tf
- src/domains/apiconfig-app/99_main.tf
- src/domains/apiconfig-app/README.md
- src/domains/apiconfig-app/api_config.tf
- src/domains/apiconfig-app/api_config_fe.tf
- src/domains/apiconfig-app/env/weu-dev/terraform.tfvars
- src/domains/apiconfig-app/env/weu-prod/terraform.tfvars
- src/domains/apiconfig-app/env/weu-uat/terraform.tfvars
> feat: Upgraded apiconfig-app tf provider

- src/domains/bizevents-app/.terraform.lock.hcl
- src/domains/bizevents-app/02_namespace.tf
- src/domains/bizevents-app/04_apim_bizevents.tf
- src/domains/bizevents-app/04_apim_bizevents_pm_ingestion.tf
- src/domains/bizevents-app/04_apim_lap.tf
- src/domains/bizevents-app/05_aks_middleware_tools.tf
- src/domains/bizevents-app/99_main.tf
- src/domains/bizevents-app/README.md
- src/domains/bizevents-app/env/weu-dev/terraform.tfvars
- src/domains/bizevents-app/env/weu-prod/terraform.tfvars
- src/domains/bizevents-app/env/weu-uat/terraform.tfvars
> feat: Upgraded tf provider bizevent app

- src/domains/checkout-app/05_checkout_function.tf
- src/domains/ecommerce-app/.terraform.lock.hcl
- src/domains/ecommerce-app/02_namespace.tf
- src/domains/ecommerce-app/04_apim_ecommerce.tf
- src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf
- src/domains/ecommerce-app/04_apim_ecommerce_helpdesk_commands.tf
- src/domains/ecommerce-app/04_apim_ecommerce_io.tf
- src/domains/ecommerce-app/04_apim_ecommerce_redirect_outcome.tf
- src/domains/ecommerce-app/04_apim_ecommerce_webview.tf
- src/domains/ecommerce-app/05_aks_middleware_tools.tf
- src/domains/ecommerce-app/99_main.tf
- src/domains/ecommerce-app/README.md
- src/domains/ecommerce-app/env/weu-dev/terraform.tfvars
- src/domains/ecommerce-app/env/weu-prod/terraform.tfvars
- src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
> feat: Paymcloud 172 ecommerce app

- src/domains/checkout-app/05_checkout_function.tf
- src/domains/checkout-app/05_pagopa_proxy.tf
- src/domains/checkout-app/05_pagopa_proxy_ha.tf
- src/domains/checkout-app/99_variables.tf
- src/domains/checkout-app/README.md
- src/domains/checkout-app/env/weu-dev/terraform.tfvars
- src/domains/checkout-app/env/weu-prod/terraform.tfvars
- src/domains/checkout-app/env/weu-uat/terraform.tfvars
> fix: Functions ip restriction configuration

- src/domains/fdr-app/.terraform.lock.hcl
- src/domains/fdr-app/00_network.tf
- src/domains/fdr-app/02_function.tf
- src/domains/fdr-app/02_namespace.tf
- src/domains/fdr-app/04_apim_fdr_fase1_internal.tf
- src/domains/fdr-app/04_apim_fdr_fase3.tf
- src/domains/fdr-app/04_apim_fdr_json_to_xml.tf
- src/domains/fdr-app/04_apim_fdr_legacy_nodo_nexi.tf
- src/domains/fdr-app/04_apim_fdr_xml_to_json.tf
- src/domains/fdr-app/05_fdr_json_to_xml_fn.tf
- src/domains/fdr-app/05_fdr_re_fn.tf
- src/domains/fdr-app/05_fdr_xml_to_json_fn.tf
- src/domains/fdr-app/10_aks_middleware_tools.tf
- src/domains/fdr-app/99_main.tf
- src/domains/fdr-app/99_variables.tf
- src/domains/fdr-app/README.md
- src/domains/fdr-app/env/weu-dev/terraform.tfvars
- src/domains/fdr-app/env/weu-prod/terraform.tfvars
- src/domains/fdr-app/env/weu-uat/terraform.tfvars
> feat: Paymcloud 172 fdr app

- src/domains/gps-app/.terraform.lock.hcl
- src/domains/gps-app/00_alert_gpd_ingestion.tf
- src/domains/gps-app/00_network.tf
- src/domains/gps-app/02_namespace.tf
- src/domains/gps-app/04_apim_gpd.tf
- src/domains/gps-app/04_apim_gpd_core.tf
- src/domains/gps-app/04_apim_gpd_for_pn_aca.tf
- src/domains/gps-app/04_apim_gpd_payments.tf
- src/domains/gps-app/04_apim_gpd_reporting.tf
- src/domains/gps-app/04_apim_gpd_upload.tf
- src/domains/gps-app/04_apim_gps.tf
- src/domains/gps-app/04_apim_gps_donation.tf
- src/domains/gps-app/04_apim_gps_enrollments.tf
- src/domains/gps-app/04_apim_payments_pull.tf
- src/domains/gps-app/04_apim_reporting_enrollment.tf
- src/domains/gps-app/05_gpd_reporting_functions.tf
- src/domains/gps-app/06_aks_middleware_tools.tf
- src/domains/gps-app/99_main.tf
- src/domains/gps-app/99_variables.tf
- src/domains/gps-app/README.md
- src/domains/gps-app/env/weu-dev/terraform.tfvars
- src/domains/gps-app/env/weu-prod/terraform.tfvars
- src/domains/gps-app/env/weu-uat/terraform.tfvars
> feat: Upgraded gpsapp tf provider

- src/domains/selfcare-app/.terraform.lock.hcl
- src/domains/selfcare-app/00_alert_backoffice.tf
> chore: Pagopa 2400 bo selfcare chk alert opsgenie

- src/domains/selfcare-common/env/weu-prod/terraform.tfvars
> feat: Increase RU BO selfcare mongo

- src/domains/pay-wallet-app/.terraform.lock.hcl
- src/domains/pay-wallet-app/02_namespace.tf
- src/domains/pay-wallet-app/03_serviceaccounts_azure_devops.tf
- src/domains/pay-wallet-app/04_apim_io_payment_wallet.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet_for_ecommerce.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet_migrations.tf
- src/domains/pay-wallet-app/05_aks_middleware_tools.tf
- src/domains/pay-wallet-app/99_main.tf
- src/domains/pay-wallet-app/README.md
> feat: Upgraded pay-wallet-app tf provider

- src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_BUNDLES.json
- src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_CIBUNDLES.json
- src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_PAYMENTTYPES.json
- src/domains/observability/datafactory/pipelines/PDND_CDC_GEC_TOUCHPOINTS.json
Modified the the following pipelines about GEC ingestion:
- `PDND_CDC_GEC_BUNDLES_Pipeline`
- `PDND_CDC_GEC_CIBUNDLES_Pipeline`
- `PDND_CDC_GEC_PAYMENTTYPES_Pipeline`
- `PDND_CDC_GEC_TOUCHPOINTS_Pipeline`
The change is necessary in order to exclude the deletion events no more useful on Data Lake.
---
> feat: [PQ-233] delete event excluded

- src/domains/printit-app/.terraform.lock.hcl
- src/domains/printit-app/01_app_service_pdf_engine.tf
- src/domains/printit-app/02_namespace.tf
- src/domains/printit-app/03_serviceaccounts_azure_devops.tf
- src/domains/printit-app/04_apim_notice_blob.tf
- src/domains/printit-app/04_apim_notice_generator.tf
- src/domains/printit-app/04_apim_notice_service.tf
- src/domains/printit-app/04_apim_pdf_engine.tf
- src/domains/printit-app/05_aks_middleware_tools.tf
- src/domains/printit-app/99_main.tf
- src/domains/printit-app/99_variables.tf
- src/domains/printit-app/README.md
> feat: Paymcloud 72 printit app

- src/domains/paymentoptions-app/.terraform.lock.hcl
- src/domains/paymentoptions-app/02_namespace.tf
- src/domains/paymentoptions-app/03_serviceaccounts_azure_devops.tf
- src/domains/paymentoptions-app/04_apim_payment_options.tf
- src/domains/paymentoptions-app/04_apim_payment_options_mock.tf
- src/domains/paymentoptions-app/05_aks_middleware_tools.tf
- src/domains/paymentoptions-app/99_main.tf
- src/domains/paymentoptions-app/README.md
> feat: Upgraded paymentoptions app tf provider

- src/domains/qi-app/.terraform.lock.hcl
- src/domains/qi-app/04_apim_qi.tf
- src/domains/qi-app/05_aks_middleware_tools.tf
- src/domains/qi-app/99_main.tf
- src/domains/qi-app/README.md
> feat: uUgraded qi app tf provider

- src/aks-leonardo/99_locals.tf
- src/next-core/03_apim.tf
- src/next-core/04_appgw.tf
- src/next-core/04_appgw_integration.tf
- src/next-core/08_natgateway.tf
Description:
- Updated NAT Gateway description with a dynamic product reference
- Prepend module names to alert descriptions for clarity
- Enhanced APIM metric alert descriptions with dynamic naming
- Standardized AKS alert descriptions and adjusted parameters for improved monitoring accuracy
These changes aim to enhance monitoring capabilities by providing clearer alert descriptions and parameters. Dynamic naming and standardized descriptions contribute to better traceability and accuracy in monitoring metrics across different resources associated with the products.
No additional information to add.
> chore: [PAYMCLOUD-178] Update alert descriptions and parameters for better monitoring

- src/domains/receipts-app/.terraform.lock.hcl
- src/domains/receipts-app/02_namespace.tf
- src/domains/receipts-app/04_apim_receipts.tf
- src/domains/receipts-app/05_aks_middleware_tools.tf
- src/domains/receipts-app/99_main.tf
- src/domains/receipts-app/README.md
- src/domains/receipts-app/env/weu-dev/terraform.tfvars
- src/domains/receipts-app/env/weu-prod/terraform.tfvars
- src/domains/receipts-app/env/weu-uat/terraform.tfvars
> feat: Upgraded receipt-app tf provider

- src/domains/selfcare-app/.terraform.lock.hcl
- src/domains/selfcare-app/02_namespace.tf
- src/domains/selfcare-app/04_apim_backoffice.tf
- src/domains/selfcare-app/04_apim_backoffice_external.tf
- src/domains/selfcare-app/06_selfcare-fe.tf
- src/domains/selfcare-app/10_aks_middleware_tools.tf
- src/domains/selfcare-app/99_main.tf
- src/domains/selfcare-app/README.md
- src/domains/selfcare-app/env/weu-dev/terraform.tfvars
- src/domains/selfcare-app/env/weu-prod/terraform.tfvars
- src/domains/selfcare-app/env/weu-uat/terraform.tfvars
> feat: Upgradded selfcare-app tf provider

- src/domains/apiconfig-common/02_security.tf
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
> chore: [PAGOPA-2264] secret apiconfig

- src/domains/shared-app/.terraform.lock.hcl
- src/domains/shared-app/00_network.tf
- src/domains/shared-app/01_app_service_pdf_engine.tf
- src/domains/shared-app/01_app_service_pdf_engine_ha.tf
- src/domains/shared-app/02_namespace.tf
- src/domains/shared-app/04_apim_authorizer.tf
- src/domains/shared-app/04_apim_authorizer_config.tf
- src/domains/shared-app/04_apim_enrolled_ec.tf
- src/domains/shared-app/04_apim_influxdb.tf
- src/domains/shared-app/04_apim_io_wallet_session.tf
- src/domains/shared-app/04_apim_pdf_engine.tf
- src/domains/shared-app/04_apim_reporting_orgs_enrollment.tf
- src/domains/shared-app/04_apim_statuspage.tf
- src/domains/shared-app/04_apim_taxonomy.tf
- src/domains/shared-app/04_apim_technical_support.tf
- src/domains/shared-app/05_taxonomy_fn.tf
- src/domains/shared-app/06_pagopa_shared_toolbox.tf
- src/domains/shared-app/10_aks_middleware_tools.tf
- src/domains/shared-app/99_locals.tf
- src/domains/shared-app/99_main.tf
- src/domains/shared-app/99_variables.tf
- src/domains/shared-app/README.md
> feat: Upgraded shared-app tf provider

- src/domains/wallet-app/.terraform.lock.hcl
- src/domains/wallet-app/02_namespace.tf
- src/domains/wallet-app/04_apim_payment_wallet.tf
- src/domains/wallet-app/04_apim_payment_wallet_for_ecommerce.tf
- src/domains/wallet-app/04_apim_payment_wallet_migrations.tf
- src/domains/wallet-app/05_aks_middleware_tools.tf
- src/domains/wallet-app/99_main.tf
- src/domains/wallet-app/README.md
> feat: Upgraded wallet-app tf provider

- src/domains/ecommerce-app/api/ecommerce-helpdesk-api/v1/_openapi.json.tpl
> feat: PPABV-59 add new api for ecommerce helpdesk

- src/domains/pay-wallet-common/env/itn-dev/terraform.tfvars
Enable public access for payment wallet DEV CosmosDB
Enable public access for payment wallet DEV CosmosDB for development purpose
---
> chore(pay-wallet-common): enable public access to cosmos DB for dev env

- src/domains/afm-app/07_gh_runner.tf
- src/domains/afm-app/99_main.tf
- src/domains/apiconfig-app/07_gh_runner.tf
- src/domains/apiconfig-app/99_main.tf
- src/domains/bizevents-app/07_gh_runner.tf
- src/domains/bizevents-app/99_main.tf
- src/domains/ebollo-app/07_gh_runner.tf
- src/domains/ebollo-app/99_main.tf
- src/domains/fdr-app/07_gh_runner.tf
- src/domains/fdr-app/99_main.tf
- src/domains/gps-app/07_gh_runner.tf
- src/domains/gps-app/99_main.tf
- src/domains/nodo-app/07_gh_runner.tf
- src/domains/nodo-app/99_main.tf
- src/domains/payopt-app/07_gh_runner.tf
- src/domains/payopt-app/99_main.tf
- src/domains/printit-app/07_gh_runner.tf
- src/domains/printit-app/99_main.tf
- src/domains/receipts-app/07_gh_runner.tf
- src/domains/receipts-app/99_main.tf
- src/domains/selfcare-app/07_gh_runner.tf
- src/domains/selfcare-app/99_main.tf
- src/domains/shared-app/07_gh_runner.tf
- src/domains/shared-app/99_main.tf
> feat: Updated gh runner module

- src/domains/gps-app/api/gpd-upload-service/v1/_base_policy.xml
```
sh terraform.sh apply weu-${env} --target=module.apim_gpd_upload_api_v1
```
---
> feat(GPD): Update rate-limit

- .devops/ndp-switcher-deploy-pipelines.yml
> feat: Ndp switcher pipeline

- src/next-core/01_dns_public.tf
- src/next-core/README.md
> feat: PAYMCLOUD-186 - added status page cname record

- src/domains/afm-app/07_gh_runner.tf
- src/domains/apiconfig-app/07_gh_runner.tf
- src/domains/bizevents-app/07_gh_runner.tf
- src/domains/fdr-app/07_gh_runner.tf
- src/domains/gps-app/07_gh_runner.tf
- src/domains/nodo-app/07_gh_runner.tf
- src/domains/receipts-app/07_gh_runner.tf
- src/domains/selfcare-app/07_gh_runner.tf
- src/domains/shared-app/07_gh_runner.tf
- src/next-core/env/prod/terraform.tfvars
> feat: Moved prod gh job to correct cae region

- src/next-core/01_custom_roles.tf
> feat: Added container app job permissions to iac reader role

- src/domains/pay-wallet-common/02_security.tf
- src/domains/pay-wallet-common/03_storage.tf
- src/domains/pay-wallet-common/README.md
Add staging PROD Event hub connection string secret
Increase storage queue alert threshold
Add staging PROD Event hub connection string secret
Increase storage queue alert threshold
---
> chore: add secret for staging evh

- src/domains/observability/04_datafactory_linkedservice.tf
> chore: Fix dl obs

- src/domains/ebollo-app/06_keyvault.tf
- src/domains/ebollo-secrets/secret/itn-dev/noedit_secret_enc.json
- src/domains/ebollo-secrets/secret/itn-prod/noedit_secret_enc.json
- src/domains/ebollo-secrets/secret/itn-uat/noedit_secret_enc.json
> Feat add elastic otel

- src/domains/printit-app/api/notices-blob/v1/_openapi.json.tpl
This get is used to download zip and pdf files
---
> fix(printit): remove .zip in the swagger file for printit proxy to blob

- src/next-core/env/prod/terraform.tfvars
According to https://github.com/pagopa/org-infra/pull/243 
---
> feat: Remove alert status-page

- src/core/apim_nodo_services_09_nodo_per_pm.tf
Added `Nodo per Payment Manager` api to `Assistenza` product
The change is necessary to enable Assistenza team to use the `checkPosition` api
---
> feat: [PQ-247] add nodo per payment manager api to assistenza product

- src/domains/shared-app/01_app_service_pdf_engine.tf
> fix: Pdf engine java autoscaling prod

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/nodo-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/nodo-secret/secret/weu-uat/noedit_secret_enc.json
- added `pagopa-platform-domain-github-bot-cd-pat`
- updated Lightbend Key
---
> chore: Gh Bot CD PAT + Lightbend Key [NODO]

- src/domains/gps-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/gps-secret/secret/weu-uat/noedit_secret_enc.json
- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- added `pagopa-platform-domain-github-bot-cd-pat`
---
> chore: [PAGOPA-2498] GPS secret

- src/domains/gps-app/env/weu-prod/terraform.tfvars
- src/domains/gps-common/env/weu-prod/terraform.tfvars
- src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/observability/03_eventhub_msg_gdp.tf
- src/domains/observability/env/uat/terraform.tfvars
- src/domains/observability/gpd_evh_create__az.sh
> feat: Enabled cdc gpd ingestion PROD

- src/domains/ecommerce-app/04_apim_ecommerce_healthcheck.tf
- src/domains/ecommerce-app/README.md
- src/domains/pay-wallet-app/04_apim_payment_wallet_healthcheck.tf
- src/domains/pay-wallet-common/03_storage.tf
- src/domains/shared-app/04_apim_pagopa_platform_statuspage.tf
- src/domains/shared-app/04_apim_statuspage_ndp.tf
- src/domains/shared-app/README.md
- src/domains/shared-app/api_product/_pagopa_platform_statuspage_policy.xml
- add new product APIM for pagoPA platform healtcheck
The goal of the PR is to create a new product on APIM called `pagoPA Platform Status Page` in order to group all the platform APIs responsible for health checks. Currently, the health check APIs for the `nodo`, `eCommerce` and `payment wallet` are configured.
- [n] No
---
> feat(healthcheck-statuspage): PPABV-60 add new product to support nodo,wallet and eCommerce healtcheck

- src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf
- src/domains/nodo-common/03_storage_account_wisp_converter.tf
- src/domains/nodo-common/env/weu-uat/terraform.tfvars
> chore: [PAGOPA-2505] fix private endpoint storage account WISP

- src/domains/gps-app/env/weu-prod/terraform.tfvars
- src/domains/observability/gpd_evh_create__az.sh
> feat: Enabled debezium-conn gpd prod

- src/domains/qi-app/README.md
- src/domains/qi-common/02_security.tf
- src/domains/qi-common/README.md
The goal of the PR is to add the secrets for service https://github.com/pagopa/pagopa-qi-fdr-kpi-service, then they will be migrated to SOPS in a dedicated PR.
---
> feat: PPABV-106 add secret for fdr-kpi

- src/synthetic-monitoring/02_monitoring.tf
- src/synthetic-monitoring/99_main.tf
- src/synthetic-monitoring/99_variables.tf
- src/synthetic-monitoring/README.md
- src/synthetic-monitoring/env/weu-dev/terraform.tfvars
- src/synthetic-monitoring/env/weu-prod/terraform.tfvars
- src/synthetic-monitoring/env/weu-uat/terraform.tfvars
- src/synthetic-monitoring/monitoring_configuration.json.tpl
> feat: Upgraded synthetic module, disabled fdr and customized nexi tests

- src/domains/pay-wallet-common/00_dns_public.tf
> fix(dns-wallet-dev): CHK-3610 update ns record for dev.payment-wallet.pagopa.it

- src/domains/printit-app/00_alerts.tf
- src/domains/printit-app/README.md
> chore(printit): Alert revision

- src/domains/ebollo-app/05_subkey.tf
- src/domains/ebollo-app/06_keyvault.tf
> feat: Add perf test key MBD

- src/aks-leonardo/03_monitoring.tf
> fix: Agent-elk-itn-leonardo

- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
> chore: increase RU ecommerce-history to support PM migrations

- src/domains/ebollo-secrets/secret/itn-dev/noedit_secret_enc.json
- src/domains/ebollo-secrets/secret/itn-prod/noedit_secret_enc.json
- src/domains/ebollo-secrets/secret/itn-uat/noedit_secret_enc.json
> feat: Add slack-webhook-url ebollo

- src/core-itn/70_monitoring.tf
- src/next-core/02_monitor.tf
- src/synthetic-monitoring/01_analytics_workspace.tf
> feat: Added law ignore sku for use with cluster

- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
> chore: increase ru cosmos ecommerce-history

- src/domains/ecommerce-app/04_apim_ecommerce.tf
- src/domains/ecommerce-app/README.md
- src/domains/ecommerce-app/api/ecommerce-helpdesk-api/v1/_bulk_search.xml.tpl
> chore: remapping request pm search bulk

- src/domains/ebollo-app/00_data.tf
- src/domains/ebollo-app/05_subkey.tf
- src/domains/ebollo-app/06_keyvault.tf
- src/domains/gps-app/04_apim_payments_pull.tf
- fixed gpd product used for MBD service integration tests
[MAIN-29](https://pagopa.atlassian.net/browse/MAIN-29)
---
[MAIN-29]: https://pagopa.atlassian.net/browse/MAIN-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [MAIN-29] fix gpd product for integration tests

- src/synthetic-monitoring/99_main.tf
- src/synthetic-monitoring/README.md
> feat: Updated monitoring module for dynamic criteria

- src/domains/ecommerce-common/env/weu-prod/terraform.tfvars
> fix: set ecommerce ru to 30k

- src/synthetic-monitoring/monitoring_configuration.json.tpl
> feat: Tuned apiconfig aks alert timeout

- src/domains/qi-app/.terraform.lock.hcl
- src/domains/qi-app/02_security.tf
> feat: Add secrets service now QI

- src/elk-monitoring/env/weu-dev/terraform.tfvars
> feat: Upgraded elk ingress nginx version

- src/synthetic-monitoring/monitoring_configuration.json.tpl
> feat:  Updated apiconfig monitoring aks url

- src/domains/fdr-secret/02_security.tf
- src/domains/qi-app/README.md
> fix: static analysis

- src/domains/selfcare-common/00_azuread.tf
> feat: Add spica 2 azuread_application-selfcare

- src/domains/gps-app/00_data.tf
- src/domains/gps-app/02_security.tf
- src/domains/gps-app/05_subkey.tf
- Add apim sub-key for GPD-Core product to be used by QA team for integration testing
QA team needs an api-key in order to invoke GPD-Core api
---
> feat: [PQ-346] gpd-subkey-creation

- src/domains/receipts-common/10_github_identity.tf
- src/domains/receipts-common/env/weu-prod/terraform.tfvars
- added permission on key-vault to GHA identity
Allow execution of smoke tests
---
> fix: [PIDM-167] Added missing permissions for receipt GHA identity

- src/domains/fdr-app/00_monitor.tf
- src/domains/fdr-app/README.md
- src/domains/fdr-app/dashboard/dash-fdr-soap.tpl
- src/elk-monitoring/05_elastic_stack.tf
- src/elk-monitoring/05_kibana_dashboard_pagopafdr.tf
- src/elk-monitoring/05_kibana_log_pagopafdr.tf
- src/elk-monitoring/README.md
- src/elk-monitoring/env/weu-dev/terraform.tfvars
- src/elk-monitoring/pagopa/fdr/component@custom.json
- src/elk-monitoring/pagopa/fdr/data-view.json
- src/elk-monitoring/pagopa/fdr/ilm-policy.json
- src/elk-monitoring/pagopa/fdr/index-template.json
- src/elk-monitoring/pagopa/fdr/ingest-pipeline.json
- src/elk-monitoring/pagopa/fdr/space.json
```
sh terraform.sh apply weu-uat \
--target=azurerm_portal_dashboard.fdr-soap-dashboard \
--target="azurerm_api_management_api_version_set.api_fdr_api_internal" \
--target="azurerm_api_management_api_version_set.api_fdr_api_org" \
--target="azurerm_api_management_api_version_set.api_fdr_api_psp" \
--target="azurerm_api_management_api_version_set.api_fdr_json_to_xml_api" \
--target="azurerm_api_management_api_version_set.api_fdr_xml_to_json_api"
```
```
sh terraform.sh apply weu-uat --target=module.elastic_stack
```
OpEx: SOAP FdR requests dashboard has been added 
---
> chore(fdr): [PAGOPA-2611] Add opex

- src/aks-platform/.terraform.lock.hcl
- src/aks-platform/05_monitoring.tf
- src/aks-platform/README.md
- src/next-core/02_monitor.tf
- src/next-core/README.md
**Description:**
- Added private DNS zone and private endpoint resources for Azure Monitor workspace to enhance network security.
- Updated Prometheus addon configuration.
- Updated module references to align with latest versions.
These changes improve the security of the Azure Monitor infrastructure by introducing private DNS and endpoint configurations. Dependency updates ensure compatibility and reflect the latest improvements.
Ensure that all associated resources are tested, and plans are executed successfully before applying in production.
> feat: [PAYMCLOUD-263] Add private DNS and endpoint to Azure Monitor Workspace

- src/aks-platform/05_monitoring.tf
- src/aks-platform/README.md
- Updated the Prometheus managed addon module source to version v8.83.1.
- Ensures access to the latest fixes and enhancements.
This update keeps the module consistent with the latest repository updates, ensuring compatibility and inclusion of the newest improvements.
No structural or functional changes were made beyond the version bump
> chore: [PAYMCLOUD-220] Upgrade Prometheus module to v8.83.1

- src/domains/checkout-common/00_dns_private.tf
- src/domains/checkout-common/01_network.tf
- src/domains/checkout-common/99_locals.tf
- src/domains/checkout-common/99_variables.tf
- src/domains/checkout-common/env/weu-dev/terraform.tfvars
- src/domains/checkout-common/env/weu-prod/terraform.tfvars
- src/domains/checkout-common/env/weu-uat/terraform.tfvars
This PR wants to add DNS configuration for the checkout domain.
For the DNS zone checkout, it's going to add an a record for `weu*.checkout`
The new checkout auth service service is not reachable due to the lack of a valid certificate
---
> feat: CHK-3696 add dns entry checkout domain auth service

- src/domains/ecommerce-common/00_alerts.tf
- src/domains/ecommerce-common/README.md
Rename payment requests alert adding missing `ecommerce` prefix
Rename payment requests alert adding missing `ecommerce` prefix
---
> chore(ecommerce payment request alert): add ecommerce prefix

- src/domains/checkout-common/00_monitor.tf
- src/domains/checkout-common/02_security.tf
- src/domains/checkout-common/03_redis.tf
- src/domains/checkout-common/99_locals.tf
- src/domains/checkout-common/99_variables.tf
- src/domains/checkout-common/env/weu-dev/terraform.tfvars
- src/domains/checkout-common/env/weu-prod/terraform.tfvars
- src/domains/checkout-common/env/weu-uat/terraform.tfvars
Note for apply:
1. first perform apply with target `azurerm_key_vault_secret.checkout_opsgenie_webhook_token` (create secret for Opsgenie webhook api key
2. update secret with right api key
3. flat apply to create all other Redis resources (Redis cache, subnet and alert)
This PR configure a Redis cache for Checkout domains that will be used by the checkout-auth service.
The following resources have been added:
- checkout opsgenie webhook key secret (used by the opsgenie action group for Redis cache alerts, only for prod env)
- checkout opsgenie action group (used by the opsgenie action group for Redis cache alerts, only for prod env)
- redis checkout resource group
- redis subnet 
- redis cache (version 6)
- redis memory usage alerts (only for prod env)
Redis cache tier is set to Basic …
> feat(checkout-common): [CHK-3695] add Redis Checkout cache instance

- src/domains/checkout-app/api/checkout/checkout_auth_service/v1/_openapi.json.tpl
Perform some refactoring against checkout-auth apis:
1. fix spec for openapi generator to generate `POST auth/token` body correctly
2. add missing state to `POST auth/token` request body
3. add missing descriptions and required fields to all requests/responses
4. review UserInfoResponse to remove the un-useful root field userInfo 
Those modifications are needed in order to fix specs to be generated correctly by the f.e. generator and to perform some refactoring to make specs compliant to best practices 
---
> fix: update auth-request specs

- src/domains/checkout-common/02_security.tf
Add secret to hold one identity client secret
Add secret to hold one identity client secret
---
> feat: add secret to hold one identity client secret

- src/domains/fdr-common/03_storage_account_fdr.tf
> feat: Remove azurerm_storage_management_policy

- src/elk-monitoring/05_elastic_stack.tf
- src/elk-monitoring/env/opentelemetry_operator_helm/otel.yaml
> feat: Added deployment environment to otel collector

- src/elk-monitoring/env/weu-uat/terraform.tfvars
- src/next-core-secrets/secret/uat/noedit_secret_enc.json
> feat: Migrated otel collector to cloud uat

- src/next-core/06_node_forwarder.tf
```
./terraform.sh plan <ENV> \
-target="azurerm_resource_group.node_forwarder_rg" \
-target="module.node_forwarder_snet" \
-target="module.node_forwarder_ha_snet" \
-target="azurerm_subnet_nat_gateway_association.nodefw_ha_snet_nat_association" \
-target="module.node_forwarder_app_service" \
-target="module.node_forwarder_slot_staging" \
-target="azurerm_private_endpoint.forwarder_input_private_endpoint" \
-target="azurerm_private_endpoint.forwarder_staging_input_private_endpoint" \
-target="azurerm_monitor_autoscale_setting.node_forwarder_app_service_autoscale" \
-target="azurerm_monitor_metric_alert.app_service_over_cpu_usage" \
-target="azurerm_monitor_metric_alert.app_service_over_mem_usage" \
-target="azurerm_key_vault_secret.certificate_crt_node_forwarder_s" \ …
```
> feat: Upd new prod env cert-2025 forwarder

- src/aks-platform/02_aks.tf
- src/aks-platform/05_monitoring.tf
- src/next-core/02_monitor.tf
- Removed `count` argument for conditional resource creation.
- Unified configuration for all environments.
- Updated resource references to avoid index-based access.
This change eliminates conditional resource creation for non-production environments, promoting codebase consistency and simplifying maintenance. Unified configurations reduce potential errors and improve understandability.
None.
> feat: [PAYMCLOUD-254] Deploy Prometheus Managed on AKS platform PROD

- src/aks-leonardo/03_aks_0.tf
- src/aks-leonardo/03_monitoring.tf
- src/core-itn/70_monitoring.tf
- Updated Prometheus and Azure Monitor configurations by removing environment-specific conditions.
- Standardized monitoring setup across all environments to reduce complexity.
This change ensures a consistent monitoring configuration across environments by eliminating unnecessary environment-specific conditions. It simplifies maintenance and enhances uniformity in system monitoring.
No additional information needed.
> feat: [PAYMCLOUD-257] Deploy Prometheus managed on AKS leonardo PROD

- src/domains/qi-common/10_github_identity.tf
Add repository `pagopa-qa` to GHA managed identities.
Add repository `pagopa-qa` to GHA managed identities.
---
> feat: add gha identity for pagopa-qa repo

- src/domains/aca-app/.terraform.lock.hcl
- src/domains/aca-app/04_apim_gpd_for_aca.tf
- src/domains/aca-app/README.md
> chore: Fix drift aca app domain

- src/domains/checkout-app/api/checkout/checkout_auth_service/v1/_base_policy.xml.tpl
Add `Authorization` header in cors section for checkout auth service base policy
---
> fix: cors for checkout auth

- src/domains/selfcare-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/selfcare-secret/secret/weu-uat/noedit_secret_enc.json
-  Added quickisght dashboard env in selfcare-secrets for UAT & PROD
---
> feat: Add quickisght dashboard env in selfcare-secrets for UAT & PROD

- src/domains/fdr-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
> chore: Db fdr1 password read

- src/next-core-secrets/secret/prod/noedit_secret_enc.json
> feat: Add grafana secret prod

- .github/workflows/static_analysis.yml
- src/domains/nodo-app/06_aks_middleware_tools.tf
- src/domains/nodo-common/README.md
- src/grafana-monitoring/README.md
- Introduced caching for Terraform plugins to improve workflow efficiency using the `actions/cache` action.
- Modified `TF_PLUGIN_CACHE_DIR` path to use an absolute directory (`/home/runner/...`) for consistency and to resolve potential path issues.
- Added a cleanup step for manual workflow dispatch events.
- Improved step names for better clarity and localization.
These changes aim to enhance the efficiency and reliability of the static analysis workflow by reducing redundant plugin downloads through caching. Additionally, the updates to path configurations and step names provide better clarity and maintainability.
None
> fix: Update Terraform plugin caching mechanism in workflows

- src/domains/checkout-app/env/weu-prod/terraform.tfvars
Enable ingress for prod
Enable ingress for prod
---
> chore: enable checkout auth service ingress

- .devops/gh-runner-cleanup.yml
- .devops/templates/clean-runner-job.yml
> feat: Fix gh runner cleanup script

- src/domains/fdr-app/00_alert.tf
- src/domains/fdr-app/00_alert_fdr_fase1.tf
```
sh terraform.sh apply weu-<ENV> -target=azurerm_monitor_scheduled_query_rules_alert.alert-fdr-nodo-error
```
---
> chore: Refact fdr1 alert `PPT_SYSTEM_ERROR`

- src/domains/checkout-app/02_namespace.tf
- src/domains/checkout-app/05_aks_middleware_tools.tf
- Delete unused POD identity for checkout domain
- update cert mounter helm release to use latest available module and set it to use workload identities instead of deprecated pod identity
Delete unused POD identity for checkout domain
Cert mounter have been tested in dev and uat env perform forced ingress certs renewal and checking for new cert to have been picked up and exposed correctly by ingress.
After deleting pod identities all deployments in the namespace have been restarted to ensure that no pods have a left pod identity usage
---
> chore(checkout): remove unused POD identity

- src/domains/ecommerce-app/02_namespace.tf
- src/domains/ecommerce-app/README.md
Remove unused POD identity
Remove unused POD identity
After deleting pod identities all deployments in the namespace have been restarted to ensure that no pods have a left pod identity usage
---
> chore(ecommerce): remove unused pod identity

- src/elk-monitoring/env/weu-prod/terraform.tfvars
- src/next-core-secrets/secret/prod/noedit_secret_enc.json
> feat: Elasticcloud prod migration

- src/aks-leonardo/env/itn-prod/terraform.tfvars
> feat: Removed prod elastic agent itn

- src/elk-monitoring/05_elastic_stack.tf
- src/elk-monitoring/README.md
- src/elk-monitoring/env/opentelemetry_operator_helm/otel.yaml
> feat: Removed prod otel collector, moved to elasticloud infra

- src/grafana-monitoring/93_auto_dashboard.tf
- src/grafana-monitoring/README.md
> feat: Add auto dashboard version

- src/domains/bizevents-app/04_apim_bizevents.tf
- src/domains/bizevents-app/README.md
- src/domains/bizevents-app/api_product/nodo-sync/_base_policy.xml
This PR contains the definition of the product for some new APIs on `pagopa-biz-events-sync-nodo` application.
- Defined product for `pagopa-biz-events-sync-nodo` application's APIs
---
> feat: [PIDM-265] Defining new product for `pagopa-biz-events-sync-nodo` application

- src/next-core/env/prod/terraform.tfvars
> fix: Fix route table

- src/domains/observability/01_observability.tf
- src/domains/observability/env/prod/terraform.tfvars
> feat: Configured pm db retention

- src/domains/fdr-app/00_alert_fdr_fase3.tf
- src/domains/fdr-app/99_variables.tf
- src/domains/fdr-app/README.md
- src/domains/fdr-app/env/weu-dev/terraform.tfvars
- src/domains/fdr-app/env/weu-prod/terraform.tfvars
- src/domains/fdr-app/env/weu-uat/terraform.tfvars
- src/domains/fdr-common/env/weu-prod/terraform.tfvars
> chore: Fdr3 fix prod

- src/domains/gps-app/api/gpd_api/segregation_codes_fragment.xml
```
sh terraform.sh apply weu-uat --target=azapi_resource.segregation_codes_fragment --target=terraform_data.sha256_segregation_codes_fragment --target=data.azurerm_api_management_user.apim_qa_user
```
---
> fix(GPD): [PIDM-404] Update authorizer policy

- src/aks-platform/env/weu-dev/terraform.tfvars
> feat: Keda 2.14

- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/README.md
Create secrets for invoking Nodo api key protected api version (auth)
Create secrets for invoking Nodo api key protected api version (auth)
---
> feat: create secret for nodo api key

- src/domains/ecommerce-common/02_security.tf
- src/domains/ecommerce-common/README.md
Create secret to hold NPG google pay api keys
Create secret to hold NPG google pay api keys
---
> feat: add secret to hold NPG google pay api keys

- src/domains/nodo-app/env/weu-prod/terraform.tfvars
To avoid problems related to massive requests, we choose to increare the minimum number of node to 4
---
> feat(nodo-app): AKS Nodo01 prod -> minimum nodes to 4

- src/domains/qi-app/07_gh_runner.tf
Creare GH action container app job for qi repos
Creare GH action container app job for qi repos
---
> feat: add gha conteiner app job for qi repos

- src/grafana-monitoring/env/weu-prod/dashboard/Infra/nsgflowlogs.json
> feat: Add nsg dashboard

- src/domains/bizevents-common/02_security.tf
- src/domains/bizevents-common/README.md
> feat: including connection string for EventHub TX on NS03

- src/grafana-monitoring/env/weu-dev/dashboard/Infra/endpointmointoring.json
- src/grafana-monitoring/env/weu-dev/dashboard/Infra/nsgflowlogs.json
- src/grafana-monitoring/env/weu-dev/dashboard/Infra/resourceoverview.json
- src/grafana-monitoring/env/weu-prod/dashboard/Infra/endpointmointoring.json
- src/grafana-monitoring/env/weu-uat/dashboard/Infra/endpointmointoring.json
- src/grafana-monitoring/env/weu-uat/dashboard/Infra/nsgflowlogs.json
- src/grafana-monitoring/env/weu-uat/dashboard/Infra/resourceoverview.json
> feat: Add dev uat synthetics

- src/grafana-monitoring/env/weu-dev/dashboard/Infra/podoverviewphase.json
- src/grafana-monitoring/env/weu-prod/dashboard/Infra/podoverviewphase.json
- src/grafana-monitoring/env/weu-uat/dashboard/Infra/podoverviewphase.json
> feat: Pod by phase dashboard

- src/domains/canoneunico/00_alert.tf
- src/domains/printit-app/02_namespace.tf
- src/domains/printit-app/README.md
> chore: Remove pod-identity printit

- src/domains/cruscotto-common/00_monitor.tf
- src/domains/cruscotto-common/00_network.tf
- src/domains/cruscotto-common/03_postgresql.tf
- src/domains/cruscotto-common/99_locals.tf
- src/domains/cruscotto-common/99_variables.tf
- src/domains/cruscotto-common/env/itn-dev/terraform.tfvars
- src/domains/cruscotto-secrets/secret/itn-dev/noedit_secret_enc.json
> feat: Add dev pgflex 4 cruscotto

- src/domains/gps-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/gps-secret/secret/weu-uat/noedit_secret_enc.json
> [PIDM-450] secret(GPD): Add SEND client api-key

- src/domains/ecommerce-app/04_apim_ecommerce_io.tf
- src/domains/ecommerce-app/README.md
- src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v2/_base_policy.xml.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v2/_openapi.json.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v2/_outcome_info.xml.tpl
- src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl
- Split total amount and fees for outcome info api for transactions-service and checkout
- Remove total amount and fees for io outcome info api
---
> Chk 4107 add outcome api split fee total amount

- .devops/performance-test-setup.yml
> feat: Paymcloud-383

- src/domains/cruscotto-app/04_apim.tf
> chore: Remove-subkey-from-cruscotto-prod

- src/next-core/06_node_forwarder.tf
- Added the `auto_mitigation_enabled` flag to response time and availability alert configurations. This ensures automatic mitigation actions are triggered when thresholds are breached.
- This change enhances system reliability by enabling automatic actions to address potential issues promptly.
- None
--- 
- None
> feat: Enable auto mitigation for forwarder alerts

- src/next-core-secrets/secret/prod/noedit_secret_enc.json
- src/next-core/env/dev/terraform.tfvars
- src/synthetic-monitoring/00_data.tf
- src/synthetic-monitoring/01_analytics_workspace.tf
- src/synthetic-monitoring/README.md
- The Application Gateway and APIM certificates in the DEV environment point to the ones with the (prefix)-stable naming convention.
- Added required secrets for the CERT-DIFF pipeline in Azure DevOps.
---
> chore: Swap appgw certificate@dev

- src/domains/fdr-secret/secret/weu-prod/noedit_secret_enc.json
> chore: Add db-fdr3-password-read secret

- src/domains/fdr-secret/secret/weu-uat/noedit_secret_enc.json
> chore: Add db-fdr3-password-read secret uat

- src/domains/cruscotto-app/06_cruscotto-fe.tf
- src/domains/receipts-common/env/weu-prod/terraform.tfvars
> chore: Upd ru receipts and crusc8 cdn default index

- src/synthetic-monitoring/monitoring_configuration.json.tpl
> chore: Fix synthetic-monitoring 4 debeziumConnectorPostgres

- src/next-core-secrets/secret/dev/noedit_secret_enc.json
- src/next-core-secrets/secret/prod/noedit_secret_enc.json
- src/next-core-secrets/secret/uat/noedit_secret_enc.json
- src/next-core/00_key_vault.tf
- src/next-core/02_monitor.tf
- src/next-core/README.md
- src/synthetic-monitoring/01_analytics_workspace.tf
- src/synthetic-monitoring/README.md
> feat: Add action group cert diff

- src/domains/ecommerce-app/api/ecommerce-payment-requests-service/v1/_openapi.json.tpl
> fix(ecommerce-openapi): Delete paymentContextCode for payment-request

- src/domains/gps-app/00_alert_gpd_core.tf
> [PAGOPA] fix: Patch alert to avoid FP

- src/domains/qi-common/00_azuread.tf
- src/domains/qi-common/02_security.tf
- src/domains/qi-common/README.md
> chore: Add smo grp 2 kv-qi

- src/domains/nodo-app/07_gh_runner.tf
> chore: Fix typo nodo-app

- src/domains/cruscotto-secrets/gen_jwt_key.sh
- src/domains/cruscotto-secrets/secret/itn-uat/noedit_secret_enc.json
> chore: Upd uat crusc8 secrets

- src/aks-leonardo/env/itn-dev/terraform.tfvars
> feat: [PAYMCLOUD-441] Update AKS Kubernetes version and KEDA Helm chart version

- src/domains/shared-common/01_github_runner_itn.tf
- src/domains/shared-common/02_security.tf
- src/domains/shared-common/03_cosmosdb_authorizer.tf
- src/domains/shared-common/99_locals.tf
- src/domains/shared-common/README.md
- Added anonymizer sub key to shared keyvault for perf test
[PAGOPA-3105](https://pagopa.atlassian.net/browse/PAGOPA-3105)
---
[PAGOPA-3105]: https://pagopa.atlassian.net/browse/PAGOPA-3105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: [PAGOPA-3105] [SHARED] Add anonymizer sub key to shared keyvault

- src/aks-leonardo/05_ingress.tf
- src/aks-leonardo/05_keda.tf
- src/aks-leonardo/env/itn-uat/terraform.tfvars
- Upgraded aks to 1.31.8
- Upgraded keda to 2.17.1
- Upgraded nginx ingress controller to 4.12.1
---
> feat: [PAYMCLOUD-442] Update AKS and Helm versions; remove redundant dependencies

- src/domains/nodo-app/.terraform.lock.hcl
- src/domains/nodo-app/00_monitor.tf
- src/domains/nodo-app/02_security.tf
- src/domains/nodo-app/99_variables.tf
- src/domains/nodo-app/README.md
> feat: [PAYMCLOUD-119] Add Logic App-based workflow for monitoring NODO cron job alerts and integrate with AKS metric alerts

- .devops/nodo-cron-alert-suspend-jobs-pipelines.yml
> chore: [PAYMCLOUD-119] Update pipeline trigger to include specific branch patterns

- .devops/nodo-cron-alert-suspend-jobs-pipelines.yml
> fix: [PAYMCLOUD-119] remove duplicate trigger

- .devops/nodo-cron-alert-suspend-jobs-pipelines.yml
> chore: [PAYMCLOUD-119] Remove unused task to delete the current branch in nodo-cron pipeline

- .devops/nodo-cron-alert-suspend-jobs-pipelines.yml
- src/domains/nodo-app/00_monitor.tf
- src/next-core/01_custom_roles.tf
> feat: PAYMCLOUD-119 Update pipeline VM pool and monitoring config to support dynamic environments

- .devops/nodo-cron-alert-suspend-jobs-pipelines.yml
> feat: Add manual env and more logic on nodo cron suspend

- .devops/nodo-cron-alert-suspend-jobs-pipelines.yml
> fix: Set default `env` parameter to 'unset' and adjusted `finalEnv` coalesce

- src/domains/cruscotto-secrets/secret/itn-dev/noedit_secret_enc.json
- src/domains/cruscotto-secrets/secret/itn-prod/noedit_secret_enc.json
- src/domains/cruscotto-secrets/secret/itn-uat/noedit_secret_enc.json
> feat: Add aws ses cfg cruscotto

- scripts/terraform.sh
- src/core-itn/03_peering.tf
- src/core-itn/99_locals.tf
- src/core-itn/README.md
> feat: Rtp peering weu

- scripts/terraform.sh
> feat: Epdated terraform.sh

- src/domains/ecommerce-app/04_apim_ecommerce_io.tf
- src/domains/ecommerce-app/api/ecommerce-io/v2/_auth_request.xml.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v2/_base_policy.xml.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v2/_calculate_fees_policy.xml.tpl
- src/domains/ecommerce-app/api/ecommerce-io/v2/_wallet_transactions.xml.tpl
- src/domains/pay-wallet-app/00_security.tf
- src/domains/pay-wallet-app/04_apim_payment_wallet.tf
- src/domains/pay-wallet-app/99_variables.tf
- src/domains/pay-wallet-app/README.md
- src/domains/pay-wallet-app/api/io-payment-wallet/v1/_base_policy.xml.tpl
- src/domains/pay-wallet-app/api/npg-notifications/v1/_base_policy.xml.tpl
- src/domains/pay-wallet-app/api/payment-wallet-for-ecommerce/v1/_base_policy.xml.tpl
- src/domains/pay-wallet-app/api/webview-payment-wallet/v1/_base_policy.xml.tpl
- src/domains/pay-wallet-app/api/webview-payment-wallet/v1/get_psps_policy.xml.tpl
Reverts pagopa/pagopa-infra#3178
> Revert "feat(api-key): [CHK-4276] inject payment-wallet-service api key"

- src/domains/pay-wallet-common/02_security.tf
- src/domains/pay-wallet-common/README.md
Created secret for primary and secondary key for payment wallet event dispatcher service
Created secret for primary and secondary key for payment wallet event dispatcher service
```code
sh terraform.sh apply itn-dev \
--target=azurerm_key_vault_secret.pay_wallet_event_dispatcher_service_primary_api_key \
--target=azurerm_key_vault_secret.pay_wallet_event_dispatcher_service_secondary_api_key
```
---
> feat: add secret for payment wallet api key

- .devops/performance-test-setup.yml
> feat: Fix apim sku performance pipeline

- src/domains/nodo-app/00_monitor.tf
- src/next-core-secrets/secret/dev/noedit_secret_enc.json
- src/next-core-secrets/secret/prod/noedit_secret_enc.json
- src/next-core-secrets/secret/uat/noedit_secret_enc.json
> feat: Add payments cloud github token secrets and updated cron grom workflow

- .devops/performance-test-setup.yml
- .devops/performance-test-weekly-teardown.yml
> feat: Added performance test teardown scheduled pipeline

- src/domains/bizevents-app/api/lap-service/v1/_base_policy-jwt.xml
- src/domains/bizevents-app/api/lap-service/v1/_base_policy.xml
> feat : PIDM-833 biz-service-identifier- `NDP004PROD` MITIGATION 😏

- src/domains/checkout-app/api/fragments/_fragment_feature_flag_filter.tpl.xml
> chore: disable isScheduledMaintenanceBannerEnabled

- src/domains/nodo-common/01_tags.tf
- src/domains/nodo-common/03_postgresql.tf
- src/domains/nodo-common/03_postgresql_replica.tf
- src/domains/nodo-common/99_main.tf
- src/domains/nodo-common/README.md
- src/domains/nodo-common/env/weu-prod/terraform.tfvars
> feat: Updated pg configuration

- src/domains/printit-app/.terraform.lock.hcl
- src/domains/printit-app/07_gh_runner.tf
- src/domains/printit-app/99_main.tf
- src/domains/printit-app/README.md
> chore: [PAGOPPA-32-16] GH Printit

- src/domains/payopt-app/api/payment-options-mock/_get_payment_options_dev_policy.xml
- src/domains/payopt-app/api/payment-options-mock/_get_payment_options_uat_policy.xml
- src/domains/payopt-app/api/payment-options-mock/_openapi.json.tpl
```
-target=module.apim_payment_options_mock_product -target=module.apim_api_pay_opt_mock_api
```
-update exixting payopts mock swagger 
[PIDM-890] (https://pagopa.atlassian.net/jira/software/c/projects/PIDM/boards/2036?selectedIssue=PIDM-890)
---
[PIDM-890]: https://pagopa.atlassian.net/browse/PIDM-890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [PIDM-890] update payopts mock

- src/domains/qi-app/.terraform.lock.hcl
- src/domains/qi-app/07_gh_runner.tf
- src/domains/qi-app/99_main.tf
- src/domains/qi-app/README.md
> chore: [PAGOPA-3216] GH Qi

- src/domains/observability/01_observability.tf
- src/domains/observability/README.md
> feat: Upd drift grant `adgroup_dataexp_reader`

- src/domains/bizevents-app/README.md
- src/domains/ebollo-app/07_gh_runner.tf
- src/domains/ebollo-app/99_main.tf
- src/domains/ebollo-secrets/secret/itn-dev/noedit_secret_enc.json
- src/domains/ebollo-secrets/secret/itn-prod/noedit_secret_enc.json
- src/domains/ebollo-secrets/secret/itn-uat/noedit_secret_enc.json
> chore: [PAGOPA-3216] GH ebollo

- src/domains/gps-secret/secret/weu-dev/noedit_secret_enc.json
- src/domains/gps-secret/secret/weu-prod/noedit_secret_enc.json
- src/domains/gps-secret/secret/weu-uat/noedit_secret_enc.json
- src/domains/payopt-secrets/secret/itn-dev/noedit_secret_enc.json
- src/domains/payopt-secrets/secret/itn-prod/noedit_secret_enc.json
- src/domains/payopt-secrets/secret/itn-uat/noedit_secret_enc.json
- src/domains/printit-secrets/secret/itn-dev/noedit_secret_enc.json
- src/domains/printit-secrets/secret/itn-prod/noedit_secret_enc.json
- src/domains/printit-secrets/secret/itn-uat/noedit_secret_enc.json
- src/domains/qi-secrets/secret/weu-dev/noedit_secret_enc.json
- src/domains/qi-secrets/secret/weu-prod/noedit_secret_enc.json
- src/domains/qi-secrets/secret/weu-uat/noedit_secret_enc.json
- src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json
- src/domains/receipts-secrets/secret/weu-prod/noedit_secret_enc.json
- src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
- src/domains/shared-secrets/secret/weu-dev/noedit_secret_enc.json
- src/domains/shared-secrets/secret/weu-prod/noedit_secret_enc.json
- src/domains/shared-secrets/secret/weu-uat/noedit_secret_enc.json
> chore: [PAGOPA-3216] Added slack secrets

- src/domains/payopt-app/07_gh_runner.tf
- src/domains/payopt-secrets/secret/itn-dev/noedit_secret_enc.json
- src/domains/payopt-secrets/secret/itn-prod/noedit_secret_enc.json
- src/domains/payopt-secrets/secret/itn-uat/noedit_secret_enc.json
> chore: [PAGOPA-3216] GH payopt

- src/next-core/env/prod/terraform.tfvars
> feat: Increased appgw max capacity

- src/next-core-secrets/secret/dev/noedit_secret_enc.json
- src/next-core-secrets/secret/prod/noedit_secret_enc.json
- src/next-core-secrets/secret/uat/noedit_secret_enc.json
> feat: Added db vdi secret
