pagopa/pagopa-infra

src/README.md, src/api_config_fe.tf, src/apim_nodo_services.tf, src/env/dev/terraform.tfvars, src/security.tf
- remove tls cert kv access policy managed in https://github.com/pagopa/gitops/pull/193
- lint
- tfsec ignore
This PR no need to be applied
https://github.com/pagopa/gitops/pull/193
---
=> removed tlscert kv access policy

src/env/dev/terraform.tfvars, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
The purpose of this PR si to [scale up ](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-scalability#throughput-units) ehub configuration in prod env to avoid [throttlings](https://docs.microsoft.com/it-it/azure/event-hubs/event-hubs-messaging-exceptions#error-code-50002) and add new consumer group for `nodo-dei-pagamenti-re` 
- updated
- enabled   `ehns_auto_inflate_enabled` and set to 5 throughput units 
- added
- a new one consumer group `nodo-dei-pagamenti-rx2` for `nodo-dei-pagamenti-re` ( for operational support )
---
=> [PPR-82] update ehub configuration

src/buyerbanks_function.tf
- always on in all envs for buyerbanks
The API exposed by `fn-buyerbanks` are invoked by a Payment Manager batch once a day, so to avoid finding the function "off" the only time it is invoked, set always on in all envs for buyerbanks
---
=> [PM] always_on true in all envs for buyer-banks

src/buyerbanks_function.tf, src/checkout_function.tf, src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars, src/gpd_reporting.tf, src/reporting_function.tf
The purpose of this PR is to set `always_on` to `true` for `reporting_fdr_fn` in UAT and PROD env and add `os_type` to `linux` for all fn app.
Udpated : 
- all module `function_app` to `2.2.0` rev
- add `os_type` to `linux` for all fn ( as suggested by @pasqualedevita )
- set `always_on` to `true` for reporting fdr function in UAT and PROD
---
=> fdr enable always_on + fix `os_type` to `linux` for fn

src/api/nodopagamenti_api/nodoPerPa/v1/NodoPerPa.wsdl
The purpose of this PR is to update `NodoPerPa` soap service according to [apim nodo roadmap](https://docs.google.com/spreadsheets/d/1n34d5Cpo2mvZ7xdhvvC-xZQvgY7bVosGVE5u0YIRz_k/edit#gid=72242577)
Update `NodoPerPa.wsdl` with : 
1. `nodoChiediInformativaPSP`
2. `nodoChiediElencoQuadraturePA`
3. `nodoPAChiediInformativaPA`
4. `nodoChiediStatoRPT`
5. `nodoChiediListaPendentiRPT`
6. `nodoChiediCopiaRT`
7. `nodoInviaRPT`
8. `nodoInviaCarrelloRPT`
---
=> update NodoPerPa soap service

src/api/checkout/checkout_payment_activations/v1/_swagger.json.tpl, src/apim_checkout.tf
* Add recaptcha check on payment activation endpoint for unauthorized API
* Update swagger associated to this API group to include recaptcha response query parameter
This PR aims to add a captcha check to the `activatePayment` operation on the Checkout payment activations API, as is currently done for the `getPaymentInfo` operation. This check is added as the former, being a delicate and stateful operation, is more in need of protections against malevolent actors (e.g. users spamming requests to the endpoint and blocking payments for other users).
---
=> Add recaptcha check on payment activation endpoint for unauthorized API

src/api_config_fe.tf
The purpose of this PR is to add `Content-Security-Policy` to api-config FE in [Report-Only](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only)
---
=> [PCFG-155] add CSP to apiconfig FE

src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
- Add cdInfoWisp in `app_gateway_deny_paths`;
The goal of this PR is deny  CdInfoWisp Web Service in App Gtw for uat and prod.
---
=> Add cdInfoWisp in app_gateway_deny_paths

src/gpd_reporting.tf
The purpose of this PR is to fix [reporting](https://pagopa.atlassian.net/wiki/spaces/PPD/pages/456525211/Design+Review+-+Rendicontazione) az-fn autoscaling.
Add `azurerm_monitor_autoscale_setting` for az function : 
- `reporting_batch_function`
- `reporting_service_function`
- `reporting_analysis_function`
---
=> [PPD-175] add reporting autoscaling

src/env/prod/terraform.tfvars, src/env/uat/terraform.tfvars
The purpose of this PR is to : 
- downscale in PROD from `D8` to `D4`
:warning: **this change'll lead to a period of temporary unavailability of the postgres DB**
---
=> [PPD-189] resize Postgres Flexible UAT and PROD

src/api/nodopagamenti_api/nodeForPsp/v1/activate_nm3.xml
Change content-type in custom response.
From application/xml to text/xml
Some proxies don't accept the content type application/xml
---
=> [PPR-353] fix content-type verificatore

src/api/nodopagamenti_api/nodeForIO/v1/activateIO_reservation_nm3.xml, src/apim_nodo_services.tf
The purpose of this PR is to enable activateIO reservation policy APIm
Add : 
- apim policy for`nodo/node-for-io/v1` with `SOAPAction: "activateIOPayment"`
---
=> feat: Add activateIO reservation policy

src/appgateway.tf, src/env/dev/terraform.tfvars, src/network.tf
The purpose of this pr is to change ip and port of dns `d.db-nodo-pagamenti.com` for nodo-dei-pagamenti's db from onPrem to onCloud according to [Regole di Rete](https://pagopa.atlassian.net/wiki/spaces/PPA/pages/464650382/Regole+di+Rete)
---
=> Update DNS IP for DB Nodo on Cloud 

src/core/README.md, src/core/fdr.tf
The purpose of this PR is to spawn an alter when FdR flow aren't sent to Az event Hub `pagopa-p-evh-ns01/nodo-dei-pagamenti-fdr`  ( only _PROD_ ) 
Add alert `fdr_parsing_0_flows_alert`
---
=> add FdR Flow Parsing Error with 0 flow

src/core/README.md, src/core/api/mock_nexi/ec/v1/_base_policy.xml, src/core/api/mock_nexi/ec/v1/mock.openapi.json.tpl, src/core/api/mock_nexi/pm/v1/_base_policy.xml, src/core/api/mock_nexi/pm/v1/mock.openapi.json.tpl, src/core/api/mock_nexi/psp/v1/_base_policy.xml, src/core/api/mock_nexi/psp/v1/mock.openapi.json.tpl, src/core/api_product/mock_nexi/_base_policy.xml, src/core/apim_mock_ec_psp_pm_nexi.tf
The purpose of this PR is to add for Nexi EC-PSP-PM api on apim pagoPA UAT/PRF dns
---
=> feat: Add mock EC-PSP-PM Nexi via UAT/PRF 

src/aks-platform/02_aks.tf
- Added externals as admin in aks platform to allow to see the resources
- Added externals as admin in aks platform to allow to see the resources like deploy and pods
---
=> fix: Enabled externals as admin in dev aks platform

README.md
Readme is not updated and the location of the `terraform.sh` script is not correct
This change is necessary in order to facilitate the usage of the `terraform.sh` script
---
=> fix: update readme with new terraform.sh location

src/core/README.md, src/core/cosmos_db_payments.tf, src/domains/afm-common/03_cosmosdb_marketplace.tf, src/domains/afm-common/README.md, src/domains/gps-common/03_cosmosdb.tf, src/domains/gps-common/README.md
Updated modules mongodb collection 
cosmosdb ignore througthput to allow cost advisor
---
=> fix: Cosmosdb ignore througthput to allow cost advisor

src/core/outputs.tf, src/domains/bizevents-common/02_security.tf
- add in Biz-Events key vault primary key of ehub-tx 
---
=> [Biz-Events] feat: add missing config for biz events datastore deploy

src/core/buyerbanks_function.tf, src/core/checkout_function.tf
- `linux_fx_version` for `checkout_function`
-  `linux_fx_version` for `buyerbanks_function`
---
=> fix: add linux_fx_version for checkout & buyerbank

src/core/README.md, src/core/api/nodopagamenti_api/nodoPerPM/v1/_closepayment_policy.xml.tpl, src/core/api/nodopagamenti_api/nodoPerPM/v1/_swagger.json.tpl, src/core/apim_nodo_services.tf, src/core/apim_nodo_services_auth.tf, src/core/apim_nodo_services_dev.tf
- Delete `/v1/ ` in closepaymentV1 swagger in order to expose api according to:
- `https://api.platform.pagopa.it/nodo/nodo-per-pm/v1/closepayment`
---
=> fix: delete v1 in swagger closepayment

src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/domains/gps-app/04_apim_reporting_enrollment.tf, src/domains/gps-app/README.md, src/domains/gps-app/api/gpd-reporting-orgs-enrollment-service/v1/_base_policy.xml, src/domains/gps-app/api/gpd-reporting-orgs-enrollment-service/v1/_openapi.json.tpl, src/domains/gps-app/api_product/gpd-reporting-orgs-enrollment-service/_base_policy.xml, src/domains/gps-common/02_security.tf, src/domains/gps-common/03_storage_account.tf, src/domains/gps-common/README.md
- Add apim for [gpd-reporting-orgs-enrollment](https://github.com/pagopa/pagopa-reporting-orgs-enrollment)
- Add storage connection string in key vault
- Add subscription key in key vault
- Add `/gps/gpd-reporting-orgs-enrollment/.*` among gateway deny-path because the APIs are only for internal use
---
=> feat: Add apim and kv secret for gpd-reporting PAGOPA-719

src/psql/nodo/liquibase/changelog/cfg/3.14.0/db.changelog-20230223101500_update_conf_keys.xml, src/psql/nodo/liquibase/changelog/cfg/db.changelog-master-3.14.0.xml
Aggiunto file liquibase per l'alter di un record per la tabella di configurazione CONFIGURATION_KEYS sul nodo come da hook ricevuto su Slack.
Arrivato un hook di modifica il giorno **22/03/2023** alle **09:58** su canale _Slack_ dedicato _pagopa-nodo4-hook_
---
=> feat: NOD-162: Allineamento liquibase per hook commit 647938

src/core/api/nodopagamenti_api/monitoring/v1/_NodoDeiPagamenti.openapi.json.tpl, src/core/api_config.tf, src/core/apim_nodo_services.tf, src/core/apim_nodo_services_dev.tf, src/core/env/prod/terraform.tfvars
- enable nodo_monitoring_api in `p` environment
- update `app_gateway_allowed_paths_pagopa_onprem_only`
These changes have the purpose of enabling the node monitoring endpoint in production too.
---
=> PAGOPA-814 feat: Enable `p` nodo monitoring apim and update allow path

src/core/.terraform.lock.hcl, src/core/apim_gpd_reporting.tf
During the integration tests performed on GPD-Reporting applications, it was found that the APIs for GPD-Reporting-Analysis services were not protected by a subscription key: they are invocable directly without using any particular key. In particular, for the `getFlow` API, a missing configuration in code mandated the use of a function-key on the Azure Function that allowed any unwanted access to be blocked.
- Added subscription key securization on `getFlow` and `getFlowList` endpoints
This changes are required in order to protect the described APIs
---
=> [PAGOPA-841] fix: set reporting analysis subkey validation

src/core/buyerbanks_function.tf
Related function [PR](https://github.com/pagopa/pagopa-functions-buyerbank/pull/42) 
Update node version to 18 for checkout buyerbanks function
This runtime modification is needed since node 14 has reached end of life
---
=> feat: update buyerbanks function runtime version

src/core/README.md, src/core/api/gpd_api/debt-position-services/v1/_base_policy.xml, src/core/env/uat/terraform.tfvars, src/core/redis_cache.tf, src/core/variables.tf
During the testing phase in UAT environment of the `pagopa-platform-authorizer` service, it was found that APIM is unable to communicate properly with an external Redis cache. This is caused by a misconfiguration of the Redis' private DNS zone that did not allow connection between APIM (present in `vnet-integration` VNET) and Redis itself (present in `vnet` core VNET).
In order to resolve this issue, it was made an update either on APIM and on external cache, adding two new resources:
- one for permitting the connection between Redis' private DNS zone and the `vnet-integration` Virtual network 
- one for permitting the generation of an explicit link between APIM and Redis, due to the fact that the default one does not work correctly on APIM uses.
In future, when a well-known [bug on …
=> [PAGOPA-925] fix: resolved bug on APIM-Redis connectivity

src/domains/apiconfig-app/api/apiconfig-cache/node_fdr/_base_policy.xml, src/domains/apiconfig-app/api/apiconfig-cache/node_fdr/_base_policy_cache_on_apim.xml, src/domains/apiconfig-app/api/apiconfig-cache/node_fdr/generate_cache_fragment.xml
- removed base policy for cache
- updated request timeout in fragment
- added gzip encoding for requests in fragment
- problem with huge amount of data to store on redis through apim
---
=> fix: [NOD-261] Removed cache policy on apim

.github/workflows/static_analysis.yml
Depends on https://github.com/pagopa/pagopa-infra/pull/1011
Add missing aca and wallet domains to github static analysis action.
Add missing aca and wallet domains to github static analysis action.
---
=> fix: add missing domains to static analysis github action

src/domains/shared-app/api/authorizer/authorizer-check.xml, src/domains/shared-app/api/authorizer/v1/_base_policy.xml
With this pull request, a fix on a bug is resolved in order to permits a more wide whitelisting on the subkey related to all entities. Also, a bugfix is made in order to force deletion of pending lock variables. 
- Added a more wide whitelisting strategy for cross-entity subkeys in Authorizer
- Resolved bug on Authorizer's insert lock variables
These changes are required in order to resolve a blocking bug on UAT and PROD environment.
---
=> Fix Authorizer whitelisting

src/domains/apiconfig-app/api/apiconfig-selfcare-integration/v1/_openapi.json.tpl, src/domains/apiconfig-app/env/weu-prod/terraform.tfvars
With this pull request, a new API is added. These APIs permits to execute dedicated queries on segregation codes used by creditor institution for station bindings, needed by SelfCare product according to [doc](https://pagopa.atlassian.net/wiki/spaces/ACN/pages/648413262/Design+Review+SelfCare+Extensions)
To apply this change, execute the command:
`sh terraform.sh apply <ENV> -target=module.apim_apiconfig_selfcare_integration_api_v1`
- Added new API on APIM for `apiconfig-selfcare-integration` product
These changes are required in order to add the new API for the APIConfig integration with SelfCare.
---
=> [PAGOPA-973] feat: added new API for retrieve segregation codes

src/domains/aca-common/README.md, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/ecommerce-payment-methods-service/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-payment-requests-service/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transaction-auth-requests-service/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transaction-user-receipts-service/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-transactions-service/v1/_openapi.json.tpl, src/domains/ecommerce-common/02_security.tf, src/domains/ecommerce-common/README.md
Add `Ocp-Apim-Subscription-Key` auth header for all ecommerce api products
Add `payment_method_api_key` secret to hold payment method api key to be used at runtime by transactions-service
Those modifications are needed to align openapi specifications including the mandatory `Ocp-Apim-Subscription-Key` authorization header for ecommerce products.
---
=> feat(ecommerce): add api key auth header

src/domains/gps-common/.terraform.lock.hcl, src/domains/gps-common/02_security.tf
This PR contains some changes made to KeyVault secrets in order to remove the static assignation to the connection strings used by `reporting orgs enrollment` and `reporting-batch` services and define a dynamic reference to the Storage Account resource.  
The changes were applied executing the following command:  
`sh terraform.sh apply ENV --target=azurerm_key_vault_secret.storage_reporting_connection_string --target=azurerm_key_vault_secret.gpd_reporting_batch_connection_string`
- Updated secret setting on `gpd-kv`
This change is needed in order to permits the correct execution of the API on `reporting orgs enrollment` service
---
=> [PAGOPA-1031] Resolving static setting of GPD reporting's KeyVault secrets

src/domains/receipts-secrets/02_security.tf, src/domains/receipts-secrets/secret/weu-dev/noedit_secret_enc.json, src/domains/receipts-secrets/secret/weu-uat/noedit_secret_enc.json
- Updated sops secrets for uat keyvault in receipts domain
Updating uat keyvault secrets for receipt domain in order to enable deployment of related components on the AKS cluster
---
=> [PRDP-48] feat: introducing receipt uat secrets

src/domains/receipts-common/.terraform.lock.hcl, src/domains/receipts-common/03_cosmosdb.tf, src/domains/receipts-common/03_storage.tf
- Introducing queue-receipt-io-notifier-error definition in receipt-commons
According to [doc](https://pagopa.atlassian.net/wiki/spaces/PPR/pages/723976457/ReceiptNotifierService#Vista-statica-delle-componenti)
Updating receipt domain infrastructure to include elements for the notifier component
---
=> [PRDP-43] feat: update receipt domain with notifier components

src/domains/shared-app/04_apim_statuspage.tf, src/domains/shared-app/api/enrolled-orgs/v1/_openapi.json.tpl
This PR contains changes made in order to include Authorizer as service shown in Status Page.
- Updated API called by Status Page
- Updated `/info` API in platform-authorizer
This update is made in order to add a new state on Status page for Authorizer
---
=> [PAGOPA-1073] feat: Exposing /info API for Status Page

src/domains/canoneunico/02_function.tf, src/domains/canoneunico/99_variables.tf, src/domains/canoneunico/env/dev/terraform.tfvars, src/domains/canoneunico/env/prod/terraform.tfvars, src/domains/canoneunico/env/uat/terraform.tfvars, src/domains/shared-app/04_apim_statuspage.tf
This PR contains changes made in order to include several application as service shown in Status Page.
Also, an update on Canone Unico was made in order to update the health check endpoint access and to update the function runtime version from v3 to v4. 
The updates made on Canone Unico function were not applied on UAT yet.
- Added status indicator for biz-event-datastore services
- Added status indicator for gpd-reporting services
- Added status indicator for canone-unico service
- Update Canone Unico runtime version 
These changes are required in order to add new service status indicators on Status Page.
---
=> [PAGOPA-1075] feat: add enhancement for Status Page

src/core/env/prod/terraform.tfvars
```
sh terraform.sh plan prod \
-target=module.apim \
-target=module.redis
```
⚠️ @andrea-deri @aomegax  verify all `<cache-.*` access refer to `caching-type="internal"` excluded authorizer
---
=> feat: Enable link redis cache on apim prod

src/domains/shared-app/api/authorizer/authorizer-check.xml, src/domains/shared-app/api/authorizer/v1/_base_policy.xml
This PR contains several changes made on APIM policy XMLs in order to resolve a bug on platform Authorizer. This bug, caused by a bad ending of Azure functions functioning during authorization caching, forced the `authorization_DOMAIN_in_progress` variable to remain in a dangling state where it cannot be automatically destroyed by policy. It was deleted only when the TTL comes to 0. This caused the execution to be locked due to the fact that the Authorizer policy fragment reads the dangling `authorization_DOMAIN_in_progress` flag and cannot perform nothing because the lock state impose to stop processing.
Before closing this PR, please merge [this one](https://github.com/pagopa/pagopa-infra/pull/1157) since the updates made here are forked from this pending PR. 
To Apply this changes, it …
=> [PAGOPA-1112] fix: resolved bug on locked internal state

CODEOWNERS, src/psql/nodo/liquibase/changelog/cfg/3.22.0/db.changelog-20230705163700_update_database_object.xml
- added unique constraint on iban column in the iban table
- added fix on pubblication_date foreseen in task [PAGOPA-1107](https://pagopa.atlassian.net/browse/PAGOPA-1107)
- in the iban table, each registered iban must be unique
- the datatype in the IBAN_VALIDI_PER_PA must be TIMESTAMP
---
[PAGOPA-1107]: https://pagopa.atlassian.net/browse/PAGOPA-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bug:[PAGOPA-1125] unique iban

src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_payment_methods_policy.xml.tpl
* add recaptcha to payment-methods' `createSessions` endpoint
This PR adds a reCAPTCHA check on `POST /payment-methods/:id/sessions`. This check is needed because this endpoint is invoked by frontends before creating a transaction (by which the user gets a JWT token).
Without a token, reCAPTCHA protection becomes necessary against abuse.
---
Depends on https://github.com/pagopa/pagopa-infra/pull/1241
=> [CHK-1823] feat(ecommerce): add recaptcha to payment-methods' `createSessions` endpoint

src/domains/gps-app/api/payments-service/v1/rest/_base_policy.xml
- Policy update to extract segregation codes and send them to the `gpd-payments` micro-service as a query param.
- Returns `403` if the caller is authorized but has an empty list of segregation codes associated with the intermediating CI
- Manage cases where CIs are intermediated by multiple brokers
- Related PR: https://github.com/pagopa/pagopa-gpd-payments/pull/55
---
=> feat: Update gpd-payments policy [PAGOPA-1140] 

src/domains/nodo-app/00_alert.tf
- Add the option to customize the response time for each alert that refers to an operation;
- Update the trigger logic, which means that alerts are triggered when the following events occur: 2 thresholds exceeded in a 10-minute time window, calculated over a 5-minute interval.
For some operations having a response time greater than the one defined by default can be considered a normal behavior.
---
=> feat(nodo-app): Add response time alert for each operation [PAGOPA-1207] 

src/domains/nodo-app/00_alert.tf
- According to current behavior, custom `response-time` was updated for the following operation: `nodoInviaFlussoRendicontazione`, `nodoChiediNumeroAvviso`
- Availability query was updated
Improve nodo alerts according to current behavior. Goal:  reduce false positives.
---
=> feat: Update nodo alerts [PAGOPA-1207] 

src/core/README.md, src/core/dns_private.tf
Add dns a record `forwarder` to : 
- `uat.platform.pagopa.it`
- `platform.pagopa.it`
which point to the respective IPs of natgw
---
=> feat: Add dns a-record `forwarder` to natgw ips for `[env].platform.pagopa.it`

src/domains/nodo-app/00_alert_faultcode.tf, src/domains/nodo-app/04_apim_nodo_services_ndp.tf, src/domains/nodo-app/04_apim_nodo_services_ndp_replica.tf, src/domains/nodo-app/05_fn_ndp_re_to_datastore.tf, src/domains/nodo-app/05_fn_ndp_re_to_tablestorage.tf, src/domains/nodo-app/README.md
Two alerts on fault code was added:
- In the first one responses that return OK and those with one of these error codes ["PPT_PAGAMENTO_IN_CORSO","PPT_PAGAMENTO_DUPLICATO", "PPT_STAZIONE_INT_PA_TIMEOUT","PPT_ATTIVAZIONE_IN_CORSO", "PPT_ERRORE_EMESSO_DA_PAA"] are considered positive. The others are considered failure. The alert is triggered based on availability threshold.
- The second monitors PPT_ERRORE_EMESSO_DA_PAA error type only and is based on 2 thresholds: the availability theshold and the number of PSP impacted.
---
=> feat: Add nodo alerts on fault code [PAGOPA-1207]

src/domains/ecommerce-app/api/npg-notification/_npg_notifications_policy.xml.tpl, src/domains/ecommerce-app/api/npg-notification/_openapi.json.tpl
1. Fix operation timestamp parsing for NPG POST notification:
date is passed without timezone information but NPG b.e. set it in Italy timezone.
This pr add date parsing converting input date to UTC set timezone information in request passed to transactions-service.
2. Remove request validation: optional values are serialized as null into received request but request validation task fails for those fields making request validation fail also for valid requests
Those modifications are needed in order to properly parse NPG input date and request body
---
=> fix(npg): [CHK-1997] operation time parsing

src/core/README.md, src/core/apim_nodo_monitoring_services.tf, src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/core/network.tf, src/core/variables.tf, src/domains/apiconfig-common/README.md, src/domains/fdr-app/05_fdr_json_to_xml_fn.tf, src/domains/fdr-app/05_fdr_xml_to_json_fn.tf, src/domains/fdr-app/README.md, src/domains/mock-common/03_mocker_postgresql.tf, src/domains/mock-common/README.md, src/domains/nodo-app/README.md, src/domains/observability/04_datafactory_pipeline.tf, src/domains/observability/README.md, src/domains/shared-app/env/weu-dev/terraform.tfvars, src/domains/shared-common/99_variables.tf, src/domains/shared-common/README.md, src/domains/shared-common/env/weu-prod/terraform.tfvars, src/domains/shared-common/env/weu-uat/terraform.tfvars
Avoid to destroy target peering from core to vnet integration, bacause name changed
---
=> fix: Vnet-peering target name from core to integration

src/domains/ecommerce-app/env/weu-prod/terraform.tfvars
Add amex psp to vpos list in prod
Add `BIC36019` psp id to vpos list in prod configurations
---
=> [CHK-1945] Add amex psp to vpos list in prod

src/core/README.md, src/core/node_forwarder.tf
- add additional autoscaling forwarder based on `HttpResponseTime` avg ( `+2` istances if greater than `3sec` )
- add alert on CPU avg forwarder grater than 80%
- add alert on MEM avg forwarder grater than 80%
```
sh terraform.sh apply <ENV>  \
-target=azurerm_monitor_autoscale_setting.node_forwarder_app_service_autoscale \
-target=azurerm_monitor_metric_alert.app_service_over_cpu_usage \
-target=azurerm_monitor_metric_alert.app_service_over_mem_usage
```
ℹ️  https://learn.microsoft.com/en-us/azure/azure-monitor/autoscale/autoscale-multiprofile?tabs=templates#multiple-contiguous-profiles
---
=> fix: Upd profile scaling to forwarder app service

src/domains/ecommerce-app/api/ecommerce-io/v1/_openapi.json.tpl
Modified eCommerce for IO opeapi:
- Add `POST /sessions` api to generate session token to be used to perform all other calls
- Add Authorization Bearer session token protection for all other api
Modified eCommerce for IO opeapi:
- Add `POST /sessions` api to generate session token to be used to perform all other calls
- Add Authorization Bearer session token protection for all other api
---
=> feat(openapi): add post sessions

src/domains/aca-app/api/aca/v1/_openapi.json.tpl
Fix ACA openapi, modified fields maxSize for entityFiscalCode and AmountEuroCents
---
=> CHK-2072 fix: aca openapi fields max size

src/domains/ecommerce-app/api/ecommerce-io/v1/get_transaction.xml.tpl, src/domains/ecommerce-app/api/ecommerce-io/v1/post_transactions.xml.tpl
1. Save transaction `rptId`and `amount` into internal Redis cache during POST `transaction` policy execution
2. Retrieve `rptId`and `amount` from Redis cache during GET `transaction` used to populate response body
3. Add payment token into payments.payment returned object for taken from proxy `idPagamento` response field
Payment token is used for populate fees call.
Rpt id and amount are required fields and here have been added in order to correctly populate response body
---
=> fix: [CHK-2090] get transaction policy payment token

src/domains/wallet-app/api/webview-payment-wallet/v1/_openapi.json.tpl
Add 401 as possible response codes to:
- `/wallets/{walletId}/sessions/{orderId}/validations`
- `/wallets/{walletId}/sessions`
- `/wallets/{walletId}/outcomes`
The base policy returns 401 if jwt validation fails.
---
=> [CHK-2168] Add 401 to webview api response codes

src/domains/ecommerce-app/04_apim_ecommerce_npg_notification.tf, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/npg-notification/_npg_notifications_policy.xml.tpl, src/domains/ecommerce-app/api/npg-notification/_openapi.json.tpl, src/domains/ecommerce-common/02_security.tf, src/domains/ecommerce-common/README.md
Edit npg notification url spec and policy
- Npg notification url (for all ecommerce transactions) now has `sessionToken` queryParam.
- Added policy jwt validation on sessionToken value.
- Match `orderId` value and get value about `transactionId` and `paymentMethodId`
Secure npg notification url
Make it compliant with logged user payment transaction
---
=> [CHK-2228] feat: redefine npg notification url

src/domains/shared-app/04_apim_statuspage.tf, src/domains/shared-app/README.md, src/domains/shared-app/api/status-page-service/v1/_base_policy.xml
This PR contains the changes applied on pagoPA's Status Page in order to add the info status for SelfCare Backoffice frontend and backend application.
Also, a new procedure for getting the version info for APIConfig frontend application was added and will be integrated as soon as possible from this repository.
- Added version info for Selfcare Backoffice backend
- Added version info for Selfcare Backoffice frontend
- Added version info for APIConfig frontend
---
=> feat: added Selfcare Backoffice (BE and FE) for version info

src/domains/gps-app/04_apim_gpd_core.tf, src/domains/gps-app/api/gpd_api/v2/_base_policy.xml, src/domains/gps-app/api/gpd_api/v2/_openapi.json.tpl
- `apim_api_gpd_api_v2` with related policy and openAPI has been added.
- redirect to new bulk API when calling `POST` `gpd/api/v2/organizations/{organizationFiscalCode}/debtpositions`
---
=> feat: Add v2 for bulk API [GPD]

src/domains/wallet-common/05_wallet_cdn.tf
This PR fix the CSP generated for wallet-fe website.
- Change var def in the CSP from dns_zone_prefix to dns_zone_platform
CSP fails if requested using another domain.
---
=> [CHK-2243] Change var in the CSP'def

src/domains/receipts-common/env/weu-uat/terraform.tfvars
- Changed consistency level account receipt-datastore to STRONG in UAT
[Issue PRDP-328](https://pagopa.atlassian.net/browse/PRDP-328?atlOrigin=eyJpIjoiNTUzYWYwM2EyM2I2NDRhZjk2ZTFkMDY1MWE0YTUxYjUiLCJwIjoiaiJ9)
---
=> [PRDP-328] fix: Changed consistency level account receipt-datastore to STRONG

src/domains/ecommerce-common/02_security.tf, src/domains/ecommerce-common/README.md
* add secret to handle Checkout Redirect PSP API keys
This PR adds a secret that stores PSP keys needed in the first call made to PSPs to get a redirection url for PSPs integrated with eCommerce through Checkout Redirect.
---
=> [CHK-2320] feat(checkout-redirect): add secret to handle Checkout Redirect PSP API keys

src/domains/wallet-app/api/payment-wallet/v1/_onboarding_outcome.xml.tpl, src/domains/wallet-app/api/payment-wallet/v1/_openapi.json.tpl
- update outcome redirect openapi & policy
The goal of this PR is to update outcome redirect for app IO with a dedicate link, the app is listening on:
- `iowallet://*****?outcome=`
so prefix  `iowallet://` instead http protocol.
---
=> feat: 302 for wallet outcome result

src/core/env/prod/terraform.tfvars, src/core/env/uat/terraform.tfvars
- Added Event Hub topic in `uat` and `prod` to send `PSP` kpi data to `Datalake`
It's necessary to create new topic on Event Hub in order to transfer `PSP` kpi data to `PDND` team.
---
=> add: [QI] new topics for qi psp kpi

src/domains/ecommerce-app/env/weu-prod/terraform.tfvars
Set pod disruption budget to 3 to ensure minimum available instances in case of any node goes down
---
=> [CHK-2379] pod disruption budget set to 3 for all ecommerce services

src/core/01_custom_roles.tf, src/core/README.md
Allow to have only a custom role, that permit iac pipelines to do plan without permissions
---
=> fix: Custom roles for IaC

src/domains/ecommerce-common/03_cosmosdb.tf
Add insertionDate as single index for dead-letter-events collection as compound index seems to not be used in aggregation pipelines queries
This index will be used to make dead-letter-events helpdesk api RU consumption low
---
=> fix: add insertionDate index

src/domains/observability/04_datafactory_pipeline.tf, src/domains/observability/datafactory/pipelines/PDND_KPI_DASPO.json, src/domains/observability/datafactory/pipelines/PDND_KPI_LFDR.json, src/domains/observability/datafactory/pipelines/PDND_KPI_LSPO.json, src/domains/observability/datafactory/pipelines/PDND_KPI_NRFDR.json, src/domains/observability/datafactory/pipelines/PDND_KPI_TNSPO.json, src/domains/observability/datafactory/pipelines/PDND_KPI_TPNP.json, src/domains/observability/datafactory/pipelines/PDND_KPI_WAFDR.json, src/domains/observability/datafactory/pipelines/PDND_KPI_WPNFDR.json
Added resource definitions for quality improvement DataFactory pipelines to transfer PSP KPI to Data Lake, below the pipeline resource list:
- PDND_KPI_DASPO
- PDND_KPI_LFDR
- PDND_KPI_LSPO
- PDND_KPI_NRFDR
- PDND_KPI_TNSPO
- PDND_KPI_TPNP
- PDND_KPI_WAFDR
- PDND_KPI_WPNFDR
In the context of Quality Improvement initiative, it's necessary to transfer all computed PSP KPI (performance & FdR) to Data Lake
---
=> [PQI-66] feat: add PDND DataFactory KPI pipeline definitions

src/domains/nodo-secret/secret/weu-dev/noedit_secret_enc.json
New secret _db-nexi-offline-password_ added. This secret is used by **pagopa-node-technical-support-worker** for connecting to Nexi database
---
=> feat: NOD-724: add secret db nodo offline Nexi

src/domains/ecommerce-common/02_security.tf, src/domains/ecommerce-common/README.md
Remove unused secret for redirect refunds endpoints since those endpoints will be retrieved from the single endpoints configuration map
Remove unused secret for redirect refunds endpoints since those endpoints will be retrieved from the single endpoints configuration map
---
=> fix: remove unused secret for redirect payment flow

src/domains/ecommerce-app/api/ecommerce-io/v1/_calculate_fees_policy.xml.tpl
Add missing `asset` field in calculate fees response for app IO with PM
Add missing `asset` field in calculate fees response for app IO with PM
---
=> fix: set missing asset field

src/domains/ecommerce-app/04_apim_ecommerce_checkout.tf, src/domains/ecommerce-app/99_variables.tf, src/domains/ecommerce-app/README.md, src/domains/ecommerce-app/api/ecommerce-checkout/v1/_auth_request.xml.tpl, src/domains/ecommerce-app/env/weu-dev/terraform.tfvars, src/domains/ecommerce-app/env/weu-prod/terraform.tfvars, src/domains/ecommerce-app/env/weu-uat/terraform.tfvars
- Update ecommerce for checkout auth request policy to zero downtime pgs->npg
The goal of this PR is to refactor the policy for selecting the `pgsId` for the `checkout` flow with `eCommerce` to ensure zero downtime during the migration from `eCommerce` with `PGS` to `eCommerce` with `NPG`. So, the selection of the `pgsId` is based on the value of the `detailsType`, where `"card"` indicates a `PGS` flow, while `"cards"` indicates a `NPG` flow.
---
=> refactor: CHK-2645 Update ecommerce for checkout auth request policy to zero downtime pgs->npg

src/core/api/nodopagamenti_api/nodoPerPM/v2/_openapi.json.tpl
Add missing fields for ClosePayment requests:
`transactionDetails.info`:
- bin (valued only for onboarded card payment)
- lastFourDigits (valued only for onboarded card payment)
- maskedEmail (valued only for onboarded paypal payment)
transactionDetails.user:
- add fiscalCode (valued only for user registered transaction)
- add REGISTERED type
Add missing close payment request fields to reflect the last specifications
---
=> feat(closepayment-spec): add missing fields for close payment

src/domains/gps-app/00_alert_gpd_payments.tf, src/domains/gps-common/10_github_identity.tf
- `pagopa-gps-donation-service` federated identity has been added
- `pagopa-gpd-payments` alert on SOAP-API availability has been adjusted
apply with 
`sh terraform.sh apply weu-${env} --target=module.identity_cd_01 --target=azurerm_key_vault_access_policy.gha_iac_managed_identities`
- `pagopa-gps-donation-service` needs to be updated for the deployment pipeline that uses federated-identity
- when the traffic load is low there are false positives for the `pagopa-gpd-payments` alert
---
=> chore(GPD): federated identity and alert tuning [PAGOPA-1668]

src/aks-platform/.terraform.lock.hcl, src/aks-platform/00_data.tf, src/aks-platform/01_network.tf, src/aks-platform/02_aks.tf, src/aks-platform/03_keda.tf, src/aks-platform/05_monitoring.tf, src/aks-platform/05_tls_checker.tf, src/aks-platform/99_locals.tf, src/aks-platform/99_main.tf, src/aks-platform/99_variables.tf, src/aks-platform/README.md, src/aks-platform/env/weu-dev/terraform.tfvars, src/aks-platform/env/weu-uat/terraform.tfvars
Plan: 0 to add, 6 to change, 0 to destroy
Update azurerm provider to v3 in ask-platform
I didn't apply this PR yet
---
=> chore: apply azurerm v3 on aks-platform

src/domains/ecommerce-app/api/ecommerce-io/v1/_auth_request.xml.tpl, src/domains/wallet-app/api/payment-wallet/v1/_base_policy.xml.tpl
Since get wallet by id is protected by userId check, this parameter has to be put in the auth request policy GET wallet by id api invocation
- auth-request policy
---
=> [CHK-2665] fix(auth-request): set user id in get wallet request in post auth request

src/domains/wallet-app/api/payment-wallet-migrations-for-cstar/v1/_openapi.json.tpl
This PR updates openapi spec for migration by adding a new optional header x-contract-hmac provided by CSTAR during migration phase. The header allows to achieve better cross domain observability.
- add x-contract-hmac as optional header for CSTAR apis
---
=> [CHK-2757] Add contract hmac optional header for cstar migration

src/domains/shared-app/04_apim_statuspage.tf, src/domains/shared-app/05_authorizer_functions.tf, src/domains/shared-app/99_locals.tf, src/domains/shared-common/.terraform.lock.hcl, src/domains/shared-common/10_github_identity.tf
- Update cache_generator_hostname
- Remove and destroy function-app related modules
```
sh terraform.sh apply weu-{env} --target=azapi_resource.authorizer_fragment
```
```
sh terraform.sh apply weu-{env} --target=azurerm_key_vault_access_policy.gha_iac_managed_identities --target=module.identity_cd_01
```
```
sh terraform.sh apply weu-{env} --target=module.apim_api_statuspage_api_v1
```
The two functions `CacheNotifier` and `CacheGenerator` have been migrated to AKS
related to https://github.com/pagopa/pagopa-platform-authorizer/pull/33
---
=> chore(shared-app): Authorizer migration to AKS [PAGOPA-1678] 

src/domains/pay-wallet-common/03_cosmosdb.tf, src/domains/pay-wallet-common/env/itn-dev/terraform.tfvars
- upgrade pay-walet cosmos to mongo 6 
The goal of this PR is to exlude the mongo cosmos version for the `payment-wallet` as the terraform resource does not support version 6.
```
╷
│ Error: expected mongo_server_version to be one of ["3.2" "3.6" "4.0" "4.2"], got 6.0
│ 
│   with module.cosmosdb_account_mongodb[0].azurerm_cosmosdb_account.this,
│   on .terraform/modules/cosmosdb_account_mongodb/cosmosdb_account/main.tf line 11, in resource "azurerm_cosmosdb_account" "this":
│   11:   mongo_server_version = var.mongo_server_version
```
The version has been updated from the portal.
---
=> feat(mongo-wallet): CHK-2945 upgrade mongo 6 for wallet

src/domains/pay-wallet-common/03_storage.tf, src/domains/pay-wallet-common/README.md, src/domains/wallet-common/03_storage.tf, src/domains/wallet-common/README.md
Add `pagopa-ENV-wallet-expiration-queue` for both `wallet` and `pay-wallet` domains
This queue will be used by wallet b.e. to trace wallet creation process expiration
---
=> feat(wallet-common & pay-wallet-common): add expiration storage queue

src/core-itn/env/dev/terraform.tfvars, src/core/env/uat/terraform.tfvars, src/domains/pay-wallet-common/env/itn-dev/terraform.tfvars, src/domains/pay-wallet-common/env/itn-prod/terraform.tfvars, src/domains/pay-wallet-common/env/itn-uat/terraform.tfvars, src/next-core/env/dev/terraform.tfvars, src/next-core/env/uat/terraform.tfvars
- changed subnets cird
Now pay-wallet domain use a range cird 10.3.5.0/24, so all the subnets are inside this range, and are /27
---
=> feat(pay-wall): Subnets are now subnets under 10.3.5.0/24 cird

src/core-itn/20_container_registry.tf
Right now ACR in Italy use public network, to allow azdo to push image 
---
=> fix: ACR Italy network now All public

src/domains/printit-app/00_data.tf, src/domains/printit-app/05_subkey.tf, src/domains/printit-app/06_keyvault.tf, src/domains/printit-app/README.md
➕ added new secret: subkey to invoke apiconfig
---
=> fix: introducing api-config subkey to printit

src/core/api/nodopagamenti_api/nodoPerPM/v2/_openapi.json.tpl
Changed `closePayment` OpenAPI to use local datetime format in `additionalPaymentInformation` timestamps (`timestampOperation` field)
This PR fixes a regression on the `closePayment` call, previously the format specified did break the following calls.
---
=> fix: Set `additionalPaymentInformations` timestamps to naive date time format

src/domains/gps-app/api/payments-service/v1/soap/wisp-paSendRTV2.xml
paSendRTV2-request-body is filtered if XElement is used
---
=> fix: Update `paSendRTV2-request-body`

src/core/api_product/nodo_pagamenti_api/decoupler/decoupler-algorithm.xml
- Create `dataToSet` in `belongs_to_wisp` case
- Fix bug `Call Stack: ExpressionValueEvaluationFailure` when access to `dataToSet` that is used in `decoupler-activate-outbound`
---
=>  fix: Update policy decoupler algorithm xml [PAGOPA-1904]

src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
- Add trace short with `A policy error has occurred`
- Add complete trace with `LastError` info
This fragment `src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml` is called in on-error section of decoupler base policy. The goal is improve policy error tracing and build dashboard to count and summarize policy error.
---
=> feat(decoupler-on-error): Add trace in on-error-soap fragment

src/domains/nodo-app/00_alert_faultcode.tf, src/domains/nodo-app/README.md
Alert by Primitiva and fault-code group:
api              = {`sendPaymentOutcome`, `activatePaymentNotice`, `nodoInviaRPT`, `nodoInviaCarrelloRPT`}
fault-code = {`PPT_AUTENTICAZIONE`, `PPT_SYSTEM_ERROR`, `PPT_CANALE_IRRANGIUNGIBILE`, `PPT_ERRORE_IDEMPOTENZA`}
Improve fault-detection by fault-code
---
=> [PAGOPA-1912] feat(nodo): Add alert on fault-code

src/domains/pay-wallet-app/api/io-payment-wallet/v1/_post_wallets.xml.tpl
* set expiration time for token for onboarding wallets to 15 minutes
See also pagopa/pagopa-wallet-service#178
---
=> fix: set expiration time for token for onboarding wallets to 15 minutes

src/domains/nodo-app/00_alert_wisp_dismantling.tf, src/domains/nodo-app/README.md
-  Add `opex_pagopa-wisp-converter-availability`: query on APIM for `/redirect` monitoring
- Add `opex_pagopa-wisp-converter-ai-availability`: query on AI for `receiptKo`, `receiptOk`, `createTimer`, `deleteTimer` monitoring
- Add `opex_pagopa-wisp-converter-ai-error`: query on AI for `receiptKo`, `receiptOk`, `createTimer`, `deleteTimer` error monitoring
- WISP-dismantling services monitoring via OpsGenie alerts
---
=> [PAGOPA-1913] feat(nodo-app): Add WISP-dismantling alerts

src/domains/nodo-app/env/weu-uat/terraform.tfvars
This PR contains some changes on CI-stations relation for WISP dismantling, where the previous confiuguration were wrong.
The changes were applied in UAT with the following command:  
```
terraform.sh apply weu-uat \
--target=azurerm_api_management_named_value.wisp_station_whitelist_named_value
```
---
=> [PAGOPA-1994] fix: changed wrong stations for WISP dismantling

src/domains/pay-wallet-common/03_cosmosdb.tf
- add new collection for log event with partitionKey
The goal of this PR is to introduce a first remediation for this [incident](https://pagopa.app.opsgenie.com/reports/post-mortem/445e9e31-9653-4396-a512-94b2e6b8b71c/detail).
The new collection is equals the last one but with partitionKey, in order to scale with new event (However, an analysis will be necessary to evaluate a retention policy).
---
=> fix: add new collection for log event with partition key

src/next-core/env/uat/terraform.tfvars
This PR contains the registration of a new API set on `upload.uat.platform.pagopa.it` domain. This fix is a temporarily workaround made in order to resolve an issue on long-time communication on FdR flows. The same fix, on near future, will be rollbacked and the API set will use standard `api.uat.platform.pagopa.it` domain.
- Add API set, starting with `/fdr-psp` to `upload.uat.platform.pagopa.it` domain
This change is required in order to temporarily and rapidly set a longer timeout on FdR APIs before a future major change on service logic.
---
=> fix: [PAGOPA-2263] temporarily added `/fdr-psp` under AppGW's upload domain

src/core/api/nodopagamenti_api/nodoPerPa/v1/wisp_nodoInviaRPT_nodoInviaCarrelloRPT_outbound_policy.xml, src/domains/nodo-app/00_alert_wisp_dismantling.tf
Changing call create rpt timer in wisp conv from async to sync
`sh terraform.sh apply <env> -target=azapi_resource.wisp_nodoinviarpt_nodoinviacarrellorpt_outbound_policy -target=terraform_data.sha256_nodoinviarpt_wisp_nodoinviacarrellorpt_outbound_policy`
Update alert, exclude wic error 1300
`sh terraform.sh apply weu-prod -target=azurerm_monitor_scheduled_query_rules_alert.opex_pagopa-wisp-converter-wic-error`
Needed in order to correctly execute flow.
The request cannot be executed in one way mode because timer creation could be consecutive to the timer deletion in the case of unfortunate interleaving in wisp-converter.
There cannot be concurrency between the `POST /rpt/timer` request and the `GET /wisp-converter/redirect/api/v1/payments` request (these are 2 calls that the user might …
=> fix: sync call to rpt timer WISP Conv PAGOPA-2292

src/domains/observability/04_datafactory_dataset.tf
- fix datasets container name the location was `weu` instead of `itn`
depend on https://github.com/pagopa/pagopa-infra/pull/2507
GEC data ingestion
---
=> fix: [PAGOPA-2280] datafactory-ingestion-gec

src/aks-platform/05_tls_checker.tf
Add OpsGenie action group to TLS checker alerts
Included OpsGenie in the list of action groups for Application Insights alerts. This ensures critical TLS checker alerts are sent to OpsGenie, enhancing incident response capability.
---
=> feat: [PAYMCLOUD-138] aks platform add tls checker under opsgenie monitor group

src/core/api/nodopagamenti_api/nodoPerPM/v2/_openapi.json.tpl
Remove UUUD format constraint since GEC idBundle has no constraint into it's bundleId field
Remove UUUD format constraint since GEC idBundle has no constraint into it's bundleId field
---
=> fix: remove UUID format constraint on bundle id

src/domains/aca-common/02_security.tf, src/domains/aca-common/99_locals.tf
Error in UAT
```
│ Error: A resource with the ID "${{uat-id}}" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.
│ 
│   with azurerm_key_vault_access_policy.azdevops_iac_policy[0],
│   on 02_security.tf line 73, in resource "azurerm_key_vault_access_policy" "azdevops_iac_policy":
│   73: resource "azurerm_key_vault_access_policy" "azdevops_iac_policy" {
```
---
=> [PAGOPA-2196] feat(aca-common): Create subkey for aca-service

src/domains/nodo-app/00_alert_wisp_dismantling.tf, src/domains/nodo-app/README.md
This PR contains a new alert made for WISP Dismantling in order to generate an alarm if the redirect API call ends too much with an unsuccess.
- Add new Opsgenie alert for WISP Dismantling project
- Updated existing one, removing client errors from excluded exceptions
This feature is required in order to enhance alarms on WISP dismantling project
---
=> feat: [PAGOPA-2425] add alert on D-WISP's redirect API availability

src/domains/printit-app/01_app_service_pdf_engine_clone.tf, src/domains/printit-app/04_apim_pdf_engine.tf, src/domains/printit-app/99_variables.tf, src/domains/printit-app/README.md, src/domains/printit-app/env/itn-prod/terraform.tfvars, src/domains/shared-app/01_app_service_pdf_engine.tf, src/domains/shared-app/04_apim_pdf_engine.tf, src/domains/shared-app/99_variables.tf, src/domains/shared-app/README.md, src/domains/shared-app/env/weu-prod/terraform.tfvars
=> feat: Paymcloud 152 printit mono az

src/domains/gps-common/03_postgresql_gpd_db.tf
=> feat: Add `high_availability_enabled`  gpd-pgflex weu

src/domains/ecommerce-common/03_storage.tf, src/domains/ecommerce-common/README.md
- new storage in ecommerce
The goal of the PR is to create a new azure storage to support the migration of PM transactions to `ecommerce-history,` in order to assist the `helpdesk-service`. 
This storage will remain public during the migration process and will then be set to private afterward
---
=> feat: new storage to support pm migration in history ecommerce

src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
Fixed content-type in case of response coming from the on-error api product policy
```
sh terraform.sh apply <ENV> \
-target=terraform_data.sha256_on_erro_soap_handler \
-target=azapi_resource.on_erro_soap_handler
```
In case of some kind of error in the main api policy, the on-error policy inherited from the product didn't set the content-type correctly, causing problems to those clients who have strict checks on it.
---
=> fix(on-error): [MAIN-14] fix content-type

src/aks-platform/02_aks.tf
**Description:**
- Updated the `cost_analysis_enabled` flag to ensure it is active in both UAT and PROD environments.
This change is required to enable the cost analysis feature in both the UAT and PROD environments. Ensuring that the `cost_analysis_enabled` flag is active aligns with the intended feature rollout.
---
=> feat: [PAYMCLOUD-185] Enable cost analysis feature in UAT and PROD environments

src/aks-platform/.terraform.lock.hcl, src/aks-platform/02_aks.tf, src/aks-platform/05_monitoring.tf, src/aks-platform/README.md, src/next-core/02_monitor.tf, src/next-core/README.md
- Added Azure Monitor Workspace for development environments to `next-core`.
- Enabled Prometheus managed addon in `aks-platform` DEV with integration to the Azure Monitor Workspace.
- Updated Terraform module and provider constraints to accommodate the new features.
This change introduces enhanced monitoring capabilities for development environments via Azure Monitor Workspace. Prometheus integration helps in unified metrics collection and visualization, improving infrastructure observability.
N/A
=> feat: [PAYMCLOUD-253] Add Azure Monitor Workspace and Prometheus integration

src/aks-platform/05_monitoring.tf
**Description:**
- Added a conditional `count` to the `prometheus_managed_addon` module.
- Ensures the addon is deployed only in the development environment.
The change prevents unnecessary deployment of the Prometheus addon in non-development environments, optimizing resource usage.
###
=> chore: [PAYMCLOUD-253] Enable conditional deployment of Prometheus addon for aks weu dev environment

src/domains/fdr-app/00_data.tf, src/domains/fdr-app/04_apim_aux.tf, src/domains/fdr-app/04_apim_fdr_fase1.tf, src/domains/fdr-app/04_apim_fdr_fase1_auth.tf, src/domains/fdr-app/99_variables.tf, src/domains/fdr-app/README.md, src/domains/fdr-app/api/fdr-fase1/nodoPerPa/v1/fdr_pagopa_cached_response.xml.tpl, src/domains/fdr-app/api/fdr-fase1/nodoPerPa/v1/fdr_pagopa_nodoChiediElencoFlussiRendicontazione.xml.tpl, src/domains/fdr-app/env/weu-dev/terraform.tfvars, src/domains/fdr-app/env/weu-prod/terraform.tfvars, src/domains/fdr-app/env/weu-uat/terraform.tfvars, src/domains/fdr-common/03_storage_account_fdr.tf, src/domains/fdr-common/99_variables.tf, src/domains/fdr-common/README.md
- added inbound and outbound policies to manage caching for `nodoChiediElencoFlussiRendicontazione`. Cache is executed saving response on a blob storage, while on redis is saved the name of the related blob file according to the request.
---
=> feat: [PAGOPA-2647] defining response caching for `nodoChiediElencoFlussiRendicontazione` primitive

src/domains/qi-app/api/qi-observability-perf-kpi/v1/_openapi.yaml.tpl, src/domains/qi-secrets/secret/weu-prod/noedit_secret_enc.json, src/domains/qi-secrets/secret/weu-uat/noedit_secret_enc.json
=> fix: [PQ-317] fix openapi for perf-data endpoint

src/domains/bizevents-common/10_github_identity.tf
- added missing permission con key vault for GHA on `biz-event` domain
[PIDM-192](https://pagopa.atlassian.net/browse/PIDM-192)
---
[PIDM-192]: https://pagopa.atlassian.net/browse/PIDM-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [PIDM-192] Add missing permission on biz event GHA

src/core-itn/70_monitoring.tf, src/core-itn/README.md
**Description:**
This pull request introduces a new resource to link the Prometheus private DNS zone to the virtual network in non-production environments. This addition ensures proper DNS resolution for Prometheus services while maintaining isolation in production. 
- Added configuration for the vNet link to the Prometheus private DNS zone in non-production.
This change is required to enable accurate DNS resolution for Prometheus services in non-production environments, improving development and testing workflows while preserving production environment integrity.
No additional information.
=> fix: [PAYMCLOUD-222] Add vNet link for Prometheus private DNS zone in non-prod

src/aks-leonardo/03_aks_0.tf, src/aks-leonardo/README.md, src/aks-platform/02_aks.tf, src/aks-platform/README.md
- Upgraded the Terraform AKS module from v8.80.0 to v8.84.1.
- Added support for new node critical alerts.
This update introduces improvements and fixes to enhance compatibility and reliability for the AKS infrastructure. The new node critical alerts provide better insights into infrastructure health.
N/A
=> feat: [PAYMCLOUD-35] Update AKS module to version v8.84.1 and add new critical node alerts.

.github/workflows/static_analysis_pr.yml, src/aks-platform/05_monitoring.tf
- Added a lifecycle block to the Helm release configuration to ignore metadata changes, improving resource management stability.
- Updated the GitHub Action for modified folders to version 1.22.0 for incorporating the latest enhancements and bug fixes.
This update ensures consistent behavior in the Helm deployment by ignoring unnecessary metadata changes. Additionally, the GitHub Action version update provides access to recent performance improvements and fixes.
=> feat: Add lifecycle ignore_changes and update GitHub Action version  

src/domains/checkout-app/api/checkout/checkout_carts_auth/v1/_base_policy.xml.tpl
Configured `ebollo` `x-client-id` on checkout apim policy.
This change is necessary to properly manage the invocations coming from `ebollo` client to `POST /carts` api.
---
=> feat: [PQ-257] add ebollo configuration to checkout policy apim

src/aks-leonardo/03_monitoring.tf, src/aks-leonardo/README.md, src/aks-platform/05_monitoring.tf, src/aks-platform/README.md, src/next-core-secrets/secret/prod/noedit_secret_enc.json
- Removed the Kubernetes Event Exporter module from the configuration.
- Deleted related webhook token and updated the encrypted secrets file.
This change aims to simplify monitoring configurations and improve maintainability by removing obsolete components.
No further updates or additional modifications needed.
=> feat: [PAYMCLOUD-305] Remove Kubernetes Event Exporter module

.github/workflows/static_analysis_pr.yml
- Added `.github`, `.devops`, `.vscode`, and `.terraform-version` to ignored patterns in the `get-modified-folders` action.
- Prevents unnecessary checks on these folders during workflow execution.
This change ensures that the static analysis workflow targets only necessary folders, improving accuracy and efficiency by ignoring unrelated patterns.
No additional impact or changes beyond the targeted workflow optimization.
=> fix: Update static analysis workflow to optimize folder checks

src/domains/ecommerce-app/api/ecommerce-checkout/v3/_transaction_policy.xml.tpl
Use same api key used for IO wallet flows so that user id is tokenized as for IO flow and can be de-tokenized successfully during close payment processing eCommerce side 
Use same api key used for IO wallet flows so that user id is tokenized as for IO flow and can be de-tokenized successfully during close payment processing eCommerce side
---
=> fix: use wallet session pdv api key for CF tokenization

src/next-core/04_appgw.tf, src/next-core/04_appgw_integration.tf
- Introduced a critical `severity 1` alert for compute units exceeding a threshold of 45.
- Adjusted the severity of an existing alert from 1 to 2 for better prioritization.
- Modified `04_appgw.tf` and `04_appgw_integration.tf` to incorporate the changes.
This change ensures a critical alert is raised when compute unit usage surpasses a defined threshold, addressing potential issues caused by traffic spikes. Updating severity levels helps improve alert prioritization and response.
Ensure that all relevant stakeholders are informed of these configuration changes to align with updated alerting and response protocols.
=> feat: [PAYMCLOUD-336] Add critical alert for high compute units usage

src/domains/gps-common/README.md, src/next-core/04_appgw.tf, src/next-core/04_appgw_integration.tf
- Updated alert rule thresholds to dynamically calculate 90% of the respective App Gateway's max capacity.
This change ensures more adaptable and environment-specific alerting by dynamically setting alert thresholds based on actual resource capacity. It reduces manual configuration and improves alert accuracy.
N/A
=> chore: [PAYMCLOUD-338] Set dynamic thresholds for App Gateway alert rules

src/domains/fdr-app/00_alert_fdr_json_to_xml.tf
- Remove `| summarize Total=count()` from alert query 
- The alert item count is always greater than 1 when `Total is 0`
---
=> fix(FdR): PAGOPA-2766 Update fdr_json2xml alert

src/core/api_product/nodo_pagamenti_api/on_error_soap_req.xml
Fixing retry to nexi for apis soap in FdR
Needed in order to avoid retries to nexi nodo for FdR soap calls
---
=> fix: modify retry nodoInviaFlusso to nexi FdR PAGOPA-2985

.github/workflows/static_analysis_pr.yml, src/aks-platform/05_monitoring.tf
- Updated the GitHub Action reference for `get-modified-folders` to version v1.22.3 to ensure compatibility with the latest improvements and bug fixes.
- No additional changes have been made to the workflow.
The update is necessary to leverage the latest features and fixes provided in `get-modified-folders` v1.22.3, ensuring optimal performance and compatibility of the workflow.
None.
---
=> fix: Update action to use get-modified-folders v1.22.3

src/domains/ecommerce-app/api/ecommerce-checkout/v1/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v2/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-checkout/v3/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-io/v2/_openapi.json.tpl, src/domains/ecommerce-app/api/ecommerce-payment-requests-service/v1/_openapi.json.tpl
- update api spec for eCommerce
The goal of thi PR is to update max amount to `999999999` for eCommerce  specification according to nodo `VerifyPaymentNotice` and `ActivatePaymentNotice`.
---
=> fix(amount-ecommerce): PIDM-614 update amount max for eCommerce workflow

src/domains/checkout-app/04_apim_checkout_carts_auth.tf, src/domains/checkout-app/04_apim_checkout_ec.tf, src/domains/checkout-app/api/checkout/checkout_carts_auth/v1/_base_policy.xml.tpl, src/domains/checkout-app/api/checkout/checkout_ec/v1/_base_policy.xml.tpl, src/domains/checkout-common/02_security.tf
Remove duplicated named value for invoke eCommerce payment request service into checkout domain
make use of the single named value
those modifications are needed to remove useless named value duplication that can lead to misalignment in api key values
```code
//dominio app
sh terraform.sh apply weu-dev \
--target=azurerm_api_management_named_value.azurerm_api_management_named_value \
--target=azurerm_api_management_named_value.ecommerce_payment_requests_api_key_value_for_checkout_ec \
--target=module.apim_checkout_carts_auth_v1 \
--target=module.apim_checkout_ec_api_v1
//dominio core
sh terraform.sh apply weu-dev \
--target=azurerm_key_vault_secret.ecommerce_payment_requests_active_api_key
```
---
=> fix: remove duplicated named values

src/domains/checkout-common/03_redis_std.tf
- Removed the "HA" suffix from Redis standard instance name.
- The change aligns with naming conventions and avoids unnecessary redundancy in the Redis instance name.
None.
---
=> chore: [PAYMCLOUD-463] Remove HA suffix from Redis instance name

src/domains/nodo-app/00_alert_nodo.tf, src/domains/nodo-app/00_alert_nodo_pagopa.tf
- the time window was updated from 5 to 7 because the delay between the call and log sometimes can be 2 minutes, this can affect the alert query;
- threshold update;
- Reduce thresholdTrafficMin, thresholdTrafficLinear because there will be less traffic
---
=> fix(nodo-app): PAGOPA-3209 Alerts' tuning

src/domains/gps-app/yaml/debezium-health-checker-cron.yaml
Avoid to use the latest images, and change docker registry to avoid problem with binami migration
---
=> fix: PAYMCLOUD-528 update debezium health checker image to specific version
